-- ============================================
-- Import phrasal verbs: ID 51-100 (50 wpisów)
-- Wklej ten SQL w Supabase SQL Editor i kliknij Run
-- ============================================

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pick up', 'To acquire or learn something, often gradually. Also means to improve or increase after a period of decline.', 'podchwycić, nauczyć się; poprawić się', 'both', '{daily,finance}', 'neutral', 'B2', '[{"sentence": "She picked up the basics of accounting during her first week at the firm.", "context": "new employee learning on the job", "tense": "Past Simple", "grammar_note": "picked up + noun phrase (object after particle)"}, {"sentence": "Sales have picked up significantly since we launched the new marketing campaign.", "context": "quarterly sales review meeting", "tense": "Present Perfect", "grammar_note": "have/has + picked up (intransitive, no object)"}, {"sentence": "If the economy picks up, we will be hiring more staff by Q3.", "context": "workforce planning discussion", "tense": "Future Simple (first conditional)", "grammar_note": "if + Present Simple, will + base verb"}, {"sentence": "Picking up new software skills is essential for career advancement.", "context": "professional development advice", "tense": "Gerund as subject", "grammar_note": "picking up + noun phrase used as subject of sentence"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pull off', 'To succeed in doing something difficult or unexpected. Often used when the outcome was uncertain.', 'udać się, dopiąć; osiągnąć coś trudnego', 'business', '{negotiations,presentations}', 'informal', 'B2', '[{"sentence": "The team pulled off the product launch despite having only two weeks to prepare.", "context": "post-launch debrief meeting", "tense": "Past Simple", "grammar_note": "pulled off + noun phrase (separable phrasal verb)"}, {"sentence": "If we coordinate properly, we will pull off this merger without losing key staff.", "context": "M&A strategy discussion", "tense": "Future Simple", "grammar_note": "will + pull off + noun phrase"}, {"sentence": "The deal was pulled off thanks to months of careful negotiation.", "context": "partnership announcement", "tense": "Passive Voice (Past Simple)", "grammar_note": "was/were + pulled off (passive construction)"}, {"sentence": "She is pulling off an incredibly complex restructuring of the entire division.", "context": "executive leadership update", "tense": "Present Continuous", "grammar_note": "is/are + pulling off + noun phrase"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('put together', 'To create or assemble something by combining different parts or elements. Commonly used for reports, teams, and plans.', 'zestawić, przygotować, złożyć', 'business', '{meetings,presentations}', 'neutral', 'B2', '[{"sentence": "We put together a detailed proposal for the client over the weekend.", "context": "preparing a pitch for a new client", "tense": "Past Simple", "grammar_note": "put together + noun phrase (separable phrasal verb)"}, {"sentence": "The presentation is being put together by the marketing department right now.", "context": "preparing for an investor meeting", "tense": "Present Continuous Passive", "grammar_note": "is being + put together (passive progressive)"}, {"sentence": "Have you put together the shortlist of candidates for the interview?", "context": "recruitment process coordination", "tense": "Present Perfect", "grammar_note": "have/has + put together + noun phrase (question form)"}, {"sentence": "Put together a summary of the key findings and email it to the board.", "context": "manager delegating tasks after a research phase", "tense": "Imperative", "grammar_note": "base form as command + noun phrase"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('run out of', 'To use up the entire supply of something so that none remains. Can refer to physical items, time, money, or abstract things like patience.', 'wyczerpać zapas czegoś, skończyć się (o czymś)', 'both', '{finance,daily}', 'neutral', 'B2', '[{"sentence": "We ran out of budget before the project was completed.", "context": "project review after cost overrun", "tense": "Past Simple", "grammar_note": "ran out of + noun (inseparable three-word phrasal verb)"}, {"sentence": "The company is running out of time to meet the regulatory deadline.", "context": "compliance team status update", "tense": "Present Continuous", "grammar_note": "is/are + running out of + noun"}, {"sentence": "If we don''t secure new funding, we will run out of cash by March.", "context": "financial planning session with investors", "tense": "Future Simple (first conditional)", "grammar_note": "if + Present Simple, will + run out of + noun"}, {"sentence": "Having run out of options, the board decided to accept the takeover bid.", "context": "corporate takeover scenario", "tense": "Past Perfect (perfect participle clause)", "grammar_note": "having + past participle used as participle clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('scale up', 'To increase the size, amount, or extent of something, especially a business operation or production process.', 'zwiększyć skalę, rozszerzyć działalność', 'business', '{finance,presentations}', 'formal', 'C1', '[{"sentence": "The startup scaled up its operations after receiving Series B funding.", "context": "company growth milestone announcement", "tense": "Past Simple", "grammar_note": "scaled up + noun phrase (separable phrasal verb)"}, {"sentence": "We have been scaling up production to meet growing demand in Asian markets.", "context": "quarterly earnings call", "tense": "Present Perfect Continuous", "grammar_note": "have/has been + scaling up + noun phrase"}, {"sentence": "Operations will be scaled up once the new factory is operational.", "context": "board meeting on expansion plans", "tense": "Future Simple Passive", "grammar_note": "will be + scaled up (passive construction)"}, {"sentence": "Scaling up too quickly can strain a company''s resources and culture.", "context": "business strategy seminar", "tense": "Gerund as subject", "grammar_note": "scaling up + adverb as gerund subject"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('send out', 'To distribute or dispatch something to multiple recipients. Commonly used for emails, invitations, or communications.', 'rozesłać, wysłać (do wielu odbiorców)', 'business', '{emails,meetings}', 'neutral', 'B2', '[{"sentence": "The HR department sent out the updated employee handbook last Friday.", "context": "distribution of new company policies", "tense": "Past Simple", "grammar_note": "sent out + noun phrase (separable phrasal verb)"}, {"sentence": "Please send out the meeting agenda at least 24 hours in advance.", "context": "office communication protocol", "tense": "Imperative", "grammar_note": "please + base form + particle + noun phrase"}, {"sentence": "The invitations have already been sent out to all stakeholders.", "context": "event planning coordination", "tense": "Present Perfect Passive", "grammar_note": "have/has been + sent out (passive construction)"}, {"sentence": "She is sending out the quarterly financial reports to all department heads today.", "context": "end-of-quarter reporting process", "tense": "Present Continuous", "grammar_note": "is/are + sending out + noun phrase + to + recipient"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('sign off', 'To give formal approval or authorization for something. Also means to end a communication or broadcast.', 'zatwierdzić, podpisać (zgodę); zakończyć (rozmowę/korespondencję)', 'business', '{emails,meetings}', 'formal', 'B2', '[{"sentence": "The director signed off on the budget proposal after reviewing the figures.", "context": "budget approval process", "tense": "Past Simple", "grammar_note": "signed off on + noun phrase (inseparable with ''on'')"}, {"sentence": "The contract cannot be executed until management has signed off on it.", "context": "legal compliance procedure", "tense": "Present Perfect", "grammar_note": "until + has/have + signed off on + pronoun"}, {"sentence": "We are still waiting for the CEO to sign off on the acquisition.", "context": "M&A process status update", "tense": "Infinitive (after ''waiting for someone to'')", "grammar_note": "waiting for + object + to + sign off on"}, {"sentence": "I will sign off now and follow up with you by email tomorrow.", "context": "ending a video conference call", "tense": "Future Simple", "grammar_note": "will + sign off (intransitive use)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('sign up', 'To register or enroll for something, such as a service, course, or event. Can also mean to recruit someone.', 'zapisać się, zarejestrować się', 'both', '{hr,daily}', 'neutral', 'B2', '[{"sentence": "Over fifty employees signed up for the leadership training workshop.", "context": "professional development program registration", "tense": "Past Simple", "grammar_note": "signed up for + noun phrase (intransitive + preposition)"}, {"sentence": "Have you signed up for the annual company retreat yet?", "context": "colleague reminding another about event registration", "tense": "Present Perfect", "grammar_note": "have/has + signed up for (question form)"}, {"sentence": "New clients are signing up for our premium service at a record rate.", "context": "sales team performance review", "tense": "Present Continuous", "grammar_note": "are/is + signing up for + noun phrase"}, {"sentence": "She would have signed up for the conference if it had not been so expensive.", "context": "discussing a missed networking opportunity", "tense": "Conditional (Third Conditional)", "grammar_note": "would have + signed up + if + Past Perfect"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('slow down', 'To reduce speed or pace. In business, it means to decrease the rate of activity, growth, or progress.', 'zwolnić, spowolnić', 'both', '{finance,daily}', 'neutral', 'B2', '[{"sentence": "Economic growth slowed down considerably in the second half of the year.", "context": "annual economic review report", "tense": "Past Simple", "grammar_note": "slowed down + adverb (intransitive use)"}, {"sentence": "The project is slowing down because of delays in getting regulatory approval.", "context": "project status meeting", "tense": "Present Continuous", "grammar_note": "is/are + slowing down + because of + noun phrase"}, {"sentence": "If hiring slows down, we should focus on retaining our best talent.", "context": "HR strategy planning session", "tense": "Conditional (First Conditional)", "grammar_note": "if + Present Simple, should + base verb"}, {"sentence": "They had slowed down the expansion plan before the market crash even happened.", "context": "post-crisis analysis of prudent decisions", "tense": "Past Perfect", "grammar_note": "had + slowed down + noun phrase (transitive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('speed up', 'To increase the rate or pace of something. Used when a process, activity, or development needs to happen faster.', 'przyspieszyć', 'business', '{meetings,daily}', 'neutral', 'B2', '[{"sentence": "We need to speed up the approval process to meet the launch deadline.", "context": "product development timeline discussion", "tense": "Infinitive (need to + base form)", "grammar_note": "need to + speed up + noun phrase"}, {"sentence": "The new automation software has sped up our order processing by 40%.", "context": "operations efficiency review", "tense": "Present Perfect", "grammar_note": "has/have + sped up + noun phrase + by + percentage"}, {"sentence": "Production was being sped up when the quality control issue was discovered.", "context": "manufacturing incident report", "tense": "Past Continuous Passive", "grammar_note": "was being + sped up (passive progressive)"}, {"sentence": "Speed up the delivery schedule or we will lose the contract.", "context": "urgent directive from a senior manager", "tense": "Imperative", "grammar_note": "base form as command + or + consequence clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('stand out', 'To be noticeably different or superior compared to others. To attract attention because of distinctive qualities.', 'wyróżniać się, odznaczać się', 'both', '{presentations,hr}', 'neutral', 'B2', '[{"sentence": "Her proposal stood out from the rest because of its innovative approach.", "context": "competitive bid evaluation", "tense": "Past Simple", "grammar_note": "stood out from + noun phrase + because of"}, {"sentence": "Candidates who stand out in the interview process are those who demonstrate leadership skills.", "context": "recruitment best practices training", "tense": "Present Simple", "grammar_note": "who + stand out (relative clause with defining clause)"}, {"sentence": "Our brand has always stood out for its commitment to sustainability.", "context": "marketing strategy presentation", "tense": "Present Perfect", "grammar_note": "has/have + always + stood out for + noun phrase"}, {"sentence": "To stand out in a crowded market, you must offer something unique.", "context": "business coaching session for entrepreneurs", "tense": "Infinitive of purpose", "grammar_note": "to + stand out + in + noun phrase (infinitive of purpose)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('sum up', 'To give a brief summary of the main points. To describe something concisely.', 'podsumować, streścić', 'business', '{meetings,presentations}', 'neutral', 'B2', '[{"sentence": "The chairman summed up the key decisions made during the board meeting.", "context": "end of a board of directors meeting", "tense": "Past Simple", "grammar_note": "summed up + noun phrase (separable phrasal verb)"}, {"sentence": "Let me sum up the main findings before we move to the Q&A session.", "context": "conclusion of a research presentation", "tense": "Imperative (let me + base form)", "grammar_note": "let me + sum up + noun phrase"}, {"sentence": "To sum up, the project is on track and within budget.", "context": "project status email to stakeholders", "tense": "Infinitive (as discourse marker)", "grammar_note": "to + sum up used as introductory phrase"}, {"sentence": "The situation can be summed up in three words: we need investment.", "context": "candid discussion with potential investors", "tense": "Passive Voice (modal + be + past participle)", "grammar_note": "can be + summed up + in + noun phrase"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('take off', 'To begin to be successful or popular very quickly. Also means to leave quickly or to remove something.', 'odnieść nagły sukces, wystartować; odlecieć', 'both', '{finance,travel}', 'neutral', 'B2', '[{"sentence": "The new product line really took off after the celebrity endorsement.", "context": "reviewing a successful marketing campaign", "tense": "Past Simple", "grammar_note": "took off (intransitive, no object needed)"}, {"sentence": "Online sales have been taking off since we redesigned the website.", "context": "e-commerce performance review", "tense": "Present Perfect Continuous", "grammar_note": "have/has been + taking off (intransitive progressive)"}, {"sentence": "If the subscription model takes off, it will transform our revenue structure.", "context": "business model strategy discussion", "tense": "Conditional (First Conditional)", "grammar_note": "if + Present Simple, will + base verb"}, {"sentence": "I need to take off early today because my flight to the conference leaves at six.", "context": "informing a colleague about leaving the office", "tense": "Infinitive (need to + base form)", "grammar_note": "need to + take off + adverb (informal: to leave)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('think over', 'To consider something carefully before making a decision. To reflect on all aspects of an issue.', 'przemyśleć, rozważyć', 'business', '{negotiations,meetings}', 'neutral', 'B2', '[{"sentence": "We thought over the merger proposal carefully before giving our response.", "context": "corporate merger negotiations", "tense": "Past Simple", "grammar_note": "thought over + noun phrase (separable phrasal verb)"}, {"sentence": "I need some time to think it over before committing to the partnership.", "context": "strategic partnership discussion", "tense": "Infinitive (need + to + think over)", "grammar_note": "to + think + pronoun + over (object between verb and particle)"}, {"sentence": "The board is still thinking over the proposed restructuring plan.", "context": "internal communications about organizational change", "tense": "Present Continuous", "grammar_note": "is/are + thinking over + noun phrase"}, {"sentence": "Think it over carefully and let us know your decision by Friday.", "context": "job offer to a senior candidate", "tense": "Imperative", "grammar_note": "base form + pronoun + over + and + imperative"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('touch on', 'To mention or deal with a subject briefly, without going into detail.', 'poruszyć (temat), napomknąć o', 'business', '{meetings,presentations}', 'formal', 'B2', '[{"sentence": "The CEO briefly touched on the company''s plans for international expansion.", "context": "annual shareholders meeting", "tense": "Past Simple", "grammar_note": "touched on + noun phrase (inseparable phrasal verb)"}, {"sentence": "I would like to touch on a few key issues before we open the floor to questions.", "context": "beginning of a quarterly review presentation", "tense": "Conditional (would like to + base form)", "grammar_note": "would like to + touch on + noun phrase"}, {"sentence": "The report has only touched on the surface of the compliance problem.", "context": "audit review discussion", "tense": "Present Perfect", "grammar_note": "has/have + only + touched on + noun phrase"}, {"sentence": "Several important topics were touched on during the leadership summit.", "context": "summary email after an executive event", "tense": "Passive Voice (Past Simple)", "grammar_note": "were + touched on (passive construction)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('turn around', 'To make a failing business or situation successful again. Also means to complete a task within a specified time.', 'odwrócić sytuację, postawić na nogi; zrealizować (w określonym czasie)', 'business', '{finance,presentations}', 'neutral', 'C1', '[{"sentence": "The new CEO turned around the struggling company within two years.", "context": "business case study analysis", "tense": "Past Simple", "grammar_note": "turned around + noun phrase (separable phrasal verb)"}, {"sentence": "The company is being turned around by a team of experienced consultants.", "context": "restructuring progress report", "tense": "Present Continuous Passive", "grammar_note": "is being + turned around + by + agent"}, {"sentence": "We can turn around the order in 48 hours if you confirm by noon.", "context": "client requesting urgent delivery", "tense": "Conditional (modal: can)", "grammar_note": "can + turn around + noun phrase + in + time period"}, {"sentence": "Having turned around three failing divisions, she was promoted to COO.", "context": "executive appointment announcement", "tense": "Perfect Participle Clause", "grammar_note": "having + turned around + noun phrase (participle clause)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('turn out', 'To happen in a particular way or to have a particular result, especially one that was not expected.', 'okazać się, wypaść (o rezultacie)', 'both', '{meetings,daily}', 'neutral', 'B2', '[{"sentence": "The investment turned out to be far more profitable than anyone had predicted.", "context": "investment portfolio review", "tense": "Past Simple", "grammar_note": "turned out + to be + adjective (linking verb pattern)"}, {"sentence": "It turns out that the supplier had been overcharging us for months.", "context": "procurement audit findings", "tense": "Present Simple", "grammar_note": "it turns out that + clause (impersonal subject)"}, {"sentence": "If things turn out well, we should see a return on investment by next year.", "context": "strategic planning discussion", "tense": "Conditional (First Conditional)", "grammar_note": "if + things + turn out + adverb, should + base verb"}, {"sentence": "No one expected the restructuring to turn out so smoothly.", "context": "post-restructuring employee town hall", "tense": "Infinitive (expected + object + to + base form)", "grammar_note": "expected + noun + to + turn out + adverb"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('work out', 'To find a solution or resolve a problem through calculation or effort. Also means to develop or end in a satisfactory way.', 'rozwiązać, wypracować; ułożyć się, wypaść (pomyślnie)', 'both', '{negotiations,finance}', 'neutral', 'B2', '[{"sentence": "We worked out a compromise that satisfied both parties in the negotiation.", "context": "contract negotiation between two companies", "tense": "Past Simple", "grammar_note": "worked out + noun phrase (separable phrasal verb)"}, {"sentence": "The analysts are working out the projected costs for the new facility.", "context": "financial planning for a new office building", "tense": "Present Continuous", "grammar_note": "are/is + working out + noun phrase"}, {"sentence": "I hope the partnership works out for both our companies.", "context": "signing ceremony for a joint venture", "tense": "Present Simple", "grammar_note": "hope + (that) + subject + works out (intransitive)"}, {"sentence": "The details of the contract would need to be worked out by the legal team.", "context": "preliminary agreement discussion", "tense": "Conditional Passive", "grammar_note": "would need to be + worked out + by + agent"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('bail out', 'To rescue someone or an organization from financial difficulty, often by providing money. Also means to abandon a difficult situation.', 'ratować finansowo, dofinansować; wycofać się', 'business', '{finance,negotiations}', 'neutral', 'C1', '[{"sentence": "The government bailed out several major banks during the financial crisis.", "context": "economic history discussion", "tense": "Past Simple", "grammar_note": "bailed out + noun phrase (separable phrasal verb)"}, {"sentence": "The company would have gone bankrupt if its parent corporation had not bailed it out.", "context": "corporate restructuring case study", "tense": "Third Conditional", "grammar_note": "would have + past participle + if + had not + bailed out"}, {"sentence": "Investors are reluctant to bail out companies that have poor governance records.", "context": "investment committee meeting", "tense": "Infinitive (reluctant to + base form)", "grammar_note": "reluctant to + bail out + noun phrase + relative clause"}, {"sentence": "Several key partners have bailed out of the joint venture this quarter.", "context": "partnership review meeting", "tense": "Present Perfect", "grammar_note": "have/has + bailed out of + noun phrase"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('branch out', 'To expand activities or interests into new areas or directions, especially in business.', 'rozgałęziać się, rozszerzać działalność na nowe obszary', 'business', '{finance,presentations}', 'neutral', 'C1', '[{"sentence": "The company branched out into renewable energy after years of focusing on oil.", "context": "corporate strategy shift announcement", "tense": "Past Simple", "grammar_note": "branched out into + noun phrase (intransitive + preposition)"}, {"sentence": "We have been branching out into new markets across Southeast Asia.", "context": "investor relations presentation", "tense": "Present Perfect Continuous", "grammar_note": "have/has been + branching out into + noun phrase"}, {"sentence": "Branching out into consulting services could diversify our revenue streams.", "context": "business development brainstorming session", "tense": "Gerund as subject", "grammar_note": "branching out into + noun phrase + modal (could)"}, {"sentence": "If we branch out too quickly, we risk overextending our resources.", "context": "risk assessment meeting", "tense": "Conditional (First Conditional)", "grammar_note": "if + Present Simple, Present Simple (risk + gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('bring in', 'To introduce something new, such as a policy, product, or person. Also means to generate revenue or profit.', 'wprowadzić; sprowadzić (kogoś); przynosić (dochód)', 'business', '{hr,finance}', 'neutral', 'B2', '[{"sentence": "The firm brought in an external auditor to review the financial statements.", "context": "annual audit process", "tense": "Past Simple", "grammar_note": "brought in + noun phrase + to + infinitive (purpose)"}, {"sentence": "The new product line is expected to bring in over two million in revenue this year.", "context": "revenue forecast presentation", "tense": "Passive Infinitive (is expected to + base form)", "grammar_note": "is expected to + bring in + amount"}, {"sentence": "We are bringing in a new performance management system next quarter.", "context": "HR policy update announcement", "tense": "Present Continuous (planned future)", "grammar_note": "are/is + bringing in + noun phrase + time expression"}, {"sentence": "Had they brought in a turnaround specialist sooner, the division might have survived.", "context": "post-mortem analysis of a closed business unit", "tense": "Past Perfect (Third Conditional, inverted)", "grammar_note": "had + subject + brought in (inverted conditional)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('buy out', 'To purchase all the shares or ownership of a business or a partner''s stake in a company.', 'wykupić (udziały), przejąć (firmę)', 'business', '{finance,negotiations}', 'formal', 'C1', '[{"sentence": "A private equity firm bought out the company for $3.5 billion last year.", "context": "corporate acquisition news", "tense": "Past Simple", "grammar_note": "bought out + noun phrase + for + amount (separable)"}, {"sentence": "The founders are considering buying out their minority shareholders.", "context": "ownership restructuring discussion", "tense": "Present Continuous (considering + gerund)", "grammar_note": "are considering + buying out + noun phrase"}, {"sentence": "If the offer is high enough, the partners will agree to be bought out.", "context": "partnership dissolution negotiations", "tense": "Future Passive (First Conditional)", "grammar_note": "will agree to be + bought out (passive infinitive)"}, {"sentence": "The competitor had already been bought out before we could make our bid.", "context": "failed acquisition attempt review", "tense": "Past Perfect Passive", "grammar_note": "had been + bought out (past perfect passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('cash in', 'To take advantage of a situation to make money. Also means to convert an investment or asset into cash.', 'spieniężyć, zarobić na czymś; wykorzystać okazję finansowo', 'business', '{finance,negotiations}', 'informal', 'C1', '[{"sentence": "Several early investors cashed in their shares when the stock price peaked.", "context": "stock market investment discussion", "tense": "Past Simple", "grammar_note": "cashed in + noun phrase (separable phrasal verb)"}, {"sentence": "The company is cashing in on the growing demand for remote work tools.", "context": "tech industry trend analysis", "tense": "Present Continuous", "grammar_note": "is/are + cashing in on + noun phrase (inseparable with ''on'')"}, {"sentence": "You should cash in your bonds before the interest rates drop further.", "context": "financial advisor consultation", "tense": "Modal (should + base form)", "grammar_note": "should + cash in + noun phrase + before + clause"}, {"sentence": "Having cashed in on the property boom, he retired at forty-five.", "context": "profile of a successful entrepreneur", "tense": "Perfect Participle Clause", "grammar_note": "having + cashed in on + noun phrase (participle clause)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('check in', 'To report your arrival at a hotel, airport, or event. In business, it means to make contact briefly to share or receive an update.', 'zameldować się; skontaktować się w celu aktualizacji', 'both', '{travel,meetings}', 'neutral', 'B2', '[{"sentence": "I checked in with the project manager to get an update on the timeline.", "context": "informal project status follow-up", "tense": "Past Simple", "grammar_note": "checked in with + person + to + infinitive (purpose)"}, {"sentence": "We will be checking in at the hotel before heading to the conference venue.", "context": "travel itinerary for a business trip", "tense": "Future Continuous", "grammar_note": "will be + checking in + at + location"}, {"sentence": "The manager checks in with each team member every Monday morning.", "context": "team management routine", "tense": "Present Simple", "grammar_note": "checks in with + person + frequency adverb"}, {"sentence": "Please check in with reception when you arrive at the office.", "context": "visitor instructions email", "tense": "Imperative", "grammar_note": "please + check in + with + noun + when + clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('chip in', 'To contribute money, effort, or ideas to a shared activity or cause. To add a comment to a discussion.', 'dorzucić się, wnieść wkład; wtrącić się (do rozmowy)', 'both', '{meetings,daily}', 'informal', 'B2', '[{"sentence": "Everyone in the office chipped in to buy a farewell gift for the retiring manager.", "context": "colleague leaving celebration", "tense": "Past Simple", "grammar_note": "chipped in + to + infinitive (purpose)"}, {"sentence": "Several departments are chipping in resources to support the charity event.", "context": "corporate social responsibility initiative", "tense": "Present Continuous", "grammar_note": "are/is + chipping in + noun phrase (contributing resources)"}, {"sentence": "If everyone chips in with ideas, we can develop a stronger marketing strategy.", "context": "creative brainstorming meeting", "tense": "Conditional (First Conditional)", "grammar_note": "if + Present Simple, can + base verb"}, {"sentence": "He had not planned to speak, but he chipped in with a useful suggestion.", "context": "unexpected contribution during a team meeting", "tense": "Past Simple (with contrast clause)", "grammar_note": "chipped in with + noun phrase (adding a comment)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('come along', 'To make progress or develop. Also means to arrive or appear, or to accompany someone.', 'posuwać się naprzód, robić postępy; pojawić się', 'both', '{meetings,daily}', 'neutral', 'B2', '[{"sentence": "The new website redesign is coming along nicely and should be ready by March.", "context": "project progress update meeting", "tense": "Present Continuous", "grammar_note": "is/are + coming along + adverb (intransitive, progress meaning)"}, {"sentence": "How has the training programme been coming along since we last spoke?", "context": "follow-up call with an HR consultant", "tense": "Present Perfect Continuous", "grammar_note": "has/have been + coming along (question form)"}, {"sentence": "A great opportunity came along just when we were about to close that product line.", "context": "explaining a lucky business break", "tense": "Past Simple", "grammar_note": "came along + time clause (intransitive, appear meaning)"}, {"sentence": "Would you like to come along to the trade fair in Berlin next week?", "context": "inviting a colleague to a business event", "tense": "Conditional (would like to + base form, question)", "grammar_note": "would + subject + like to + come along + to + event"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('come down to', 'To be essentially a matter of something; when the most important factor is identified. The core issue or deciding factor.', 'sprowadzać się do', 'business', '{negotiations,meetings}', 'neutral', 'C1', '[{"sentence": "In the end, the decision came down to cost versus quality.", "context": "supplier selection meeting", "tense": "Past Simple", "grammar_note": "came down to + noun phrase (inseparable three-word phrasal verb)"}, {"sentence": "It always comes down to whether we can deliver on time and within budget.", "context": "client relationship management discussion", "tense": "Present Simple", "grammar_note": "comes down to + whether clause"}, {"sentence": "The success of this merger will come down to how well we integrate the two cultures.", "context": "post-merger integration planning", "tense": "Future Simple", "grammar_note": "will + come down to + how clause"}, {"sentence": "What the negotiation came down to was a disagreement over intellectual property rights.", "context": "analysis of failed contract talks", "tense": "Past Simple (cleft sentence)", "grammar_note": "what + clause + was + noun phrase (cleft sentence)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('come up', 'To be mentioned or arise in conversation or discussion. Also means for a problem or situation to occur unexpectedly.', 'pojawić się, zostać poruszonym (w rozmowie); wyniknąć', 'both', '{meetings,daily}', 'neutral', 'B2', '[{"sentence": "The issue of employee wellbeing came up during the management meeting.", "context": "human resources discussion", "tense": "Past Simple", "grammar_note": "came up + during + noun phrase (intransitive)"}, {"sentence": "Something urgent has come up, so I will need to reschedule our appointment.", "context": "last-minute schedule change email", "tense": "Present Perfect", "grammar_note": "has/have + come up (intransitive, present result)"}, {"sentence": "If any questions come up during the presentation, please note them down for the end.", "context": "presenter instructions before a seminar", "tense": "Conditional (First Conditional)", "grammar_note": "if + come up, imperative (first conditional with imperative)"}, {"sentence": "We were discussing the budget when a compliance concern came up unexpectedly.", "context": "interrupted planning meeting", "tense": "Past Continuous + Past Simple", "grammar_note": "were + -ing + when + came up (interrupted action)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('crack down on', 'To take strict action to stop or limit undesirable behaviour, often involving enforcement of rules or laws.', 'zastosować surowe środki wobec, zaostrzać przepisy przeciwko', 'business', '{hr,finance}', 'formal', 'C1', '[{"sentence": "The regulator cracked down on companies that had been misreporting their emissions data.", "context": "environmental compliance enforcement", "tense": "Past Simple", "grammar_note": "cracked down on + noun phrase (inseparable three-word phrasal verb)"}, {"sentence": "The company is cracking down on unauthorized expense claims with a new approval system.", "context": "finance department policy update", "tense": "Present Continuous", "grammar_note": "is/are + cracking down on + noun phrase + with + method"}, {"sentence": "Tax authorities have cracked down on corporations using offshore tax havens.", "context": "international tax policy news", "tense": "Present Perfect", "grammar_note": "have/has + cracked down on + noun phrase + present participle"}, {"sentence": "Management should crack down on late submissions to ensure data accuracy.", "context": "process improvement recommendation", "tense": "Modal (should + base form)", "grammar_note": "should + crack down on + noun phrase + to + infinitive"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('factor in', 'To include something as a relevant element when making a calculation or decision.', 'uwzględnić, wziąć pod uwagę', 'business', '{finance,meetings}', 'formal', 'C1', '[{"sentence": "We factored in the rising cost of raw materials when preparing the annual budget.", "context": "budget planning session", "tense": "Past Simple", "grammar_note": "factored in + noun phrase + when + gerund clause"}, {"sentence": "Currency exchange risks should always be factored in when evaluating international deals.", "context": "international business strategy lecture", "tense": "Passive Voice (modal: should + be + past participle)", "grammar_note": "should be + factored in + when + gerund clause"}, {"sentence": "Have you factored in the cost of employee training for the new system?", "context": "IT implementation review meeting", "tense": "Present Perfect (question form)", "grammar_note": "have/has + factored in + noun phrase (question)"}, {"sentence": "Factoring in all variables, the total investment is estimated at $4.2 million.", "context": "investment proposal document", "tense": "Present Participle Clause", "grammar_note": "factoring in + noun phrase (present participle clause)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('fall behind', 'To fail to keep up with a schedule, standard, or expected level of progress. To lag behind competitors or deadlines.', 'zostać w tyle, mieć opóźnienie', 'business', '{meetings,finance}', 'neutral', 'B2', '[{"sentence": "The project fell behind schedule due to unexpected supply chain disruptions.", "context": "project delay debrief", "tense": "Past Simple", "grammar_note": "fell behind + noun (schedule) + due to + noun phrase"}, {"sentence": "We have fallen behind our competitors in terms of digital innovation.", "context": "strategic review presentation", "tense": "Present Perfect", "grammar_note": "have/has + fallen behind + noun + in terms of"}, {"sentence": "If we fall behind on payments, the supplier may terminate the contract.", "context": "accounts payable warning", "tense": "Conditional (First Conditional)", "grammar_note": "if + fall behind on + noun, may + base verb"}, {"sentence": "The team was falling behind on deadlines before the new project manager stepped in.", "context": "performance improvement narrative", "tense": "Past Continuous", "grammar_note": "was/were + falling behind on + noun + before + clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('gear up', 'To prepare or get ready for an important event, challenge, or increased activity.', 'przygotować się, szykować się', 'business', '{meetings,presentations}', 'neutral', 'B2', '[{"sentence": "The retail sector is gearing up for the busiest shopping season of the year.", "context": "pre-holiday retail industry analysis", "tense": "Present Continuous", "grammar_note": "is/are + gearing up for + noun phrase"}, {"sentence": "We geared up for the product launch by hiring additional customer support staff.", "context": "post-launch review of preparations", "tense": "Past Simple", "grammar_note": "geared up for + noun phrase + by + gerund"}, {"sentence": "The marketing team should gear up for a surge in inquiries after the TV advert airs.", "context": "advertising campaign preparation", "tense": "Modal (should + base form)", "grammar_note": "should + gear up for + noun phrase + after + clause"}, {"sentence": "Having geared up for months, the sales team felt confident about meeting their targets.", "context": "beginning of a new fiscal year", "tense": "Perfect Participle Clause", "grammar_note": "having + geared up (participle clause expressing prior action)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go about', 'To begin or approach a task or activity in a particular way. To take steps toward doing something.', 'zabrać się za coś, podchodzić do czegoś', 'both', '{meetings,daily}', 'neutral', 'B2', '[{"sentence": "How should we go about restructuring the sales department?", "context": "organizational change planning meeting", "tense": "Modal (should + base form, question)", "grammar_note": "how + should + go about + gerund"}, {"sentence": "She went about building the client relationship methodically and patiently.", "context": "account management success story", "tense": "Past Simple", "grammar_note": "went about + gerund + adverb (inseparable + gerund)"}, {"sentence": "The team is going about the audit process in a very thorough manner.", "context": "internal audit progress update", "tense": "Present Continuous", "grammar_note": "is/are + going about + noun phrase + in + manner"}, {"sentence": "If you do not know how to go about filing a complaint, consult the handbook.", "context": "employee onboarding session", "tense": "Conditional (First Conditional with imperative)", "grammar_note": "if + do not know + how to + go about + gerund, imperative"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hammer out', 'To negotiate or discuss something at length until an agreement or solution is reached.', 'wynegocjować, wypracować (po długich dyskusjach)', 'business', '{negotiations,meetings}', 'informal', 'C1', '[{"sentence": "The two companies hammered out a deal after three days of intense negotiations.", "context": "joint venture agreement conclusion", "tense": "Past Simple", "grammar_note": "hammered out + noun phrase + after + time expression"}, {"sentence": "We are still trying to hammer out the details of the distribution agreement.", "context": "ongoing contract negotiation", "tense": "Present Continuous (trying to + base form)", "grammar_note": "are trying to + hammer out + noun phrase"}, {"sentence": "The final terms of the contract were hammered out just hours before the deadline.", "context": "last-minute deal closure", "tense": "Passive Voice (Past Simple)", "grammar_note": "were + hammered out + time expression (passive)"}, {"sentence": "Both sides will need to hammer out a compromise on pricing before we can proceed.", "context": "supplier negotiations strategy briefing", "tense": "Future (will need to + base form)", "grammar_note": "will need to + hammer out + noun phrase + before + clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('iron out', 'To resolve or eliminate problems, difficulties, or disagreements, typically through discussion.', 'rozwiązać (problemy), wygładzić (różnice)', 'business', '{negotiations,meetings}', 'neutral', 'B2', '[{"sentence": "We managed to iron out all the issues before the contract was signed.", "context": "contract finalization discussion", "tense": "Past Simple (managed to + base form)", "grammar_note": "managed to + iron out + noun phrase + before + clause"}, {"sentence": "A few technical problems still need to be ironed out before the system goes live.", "context": "IT system implementation meeting", "tense": "Passive Infinitive (need to be + past participle)", "grammar_note": "need to be + ironed out + before + clause"}, {"sentence": "The team has been ironing out the inconsistencies in the new policy document.", "context": "policy review working session", "tense": "Present Perfect Continuous", "grammar_note": "has/have been + ironing out + noun phrase"}, {"sentence": "Iron out any disagreements before presenting the unified proposal to the client.", "context": "team leader instruction before a client pitch", "tense": "Imperative", "grammar_note": "base form + noun phrase + before + gerund clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('kick off', 'To start or begin an event, project, or activity. Often used for the initial launch of something.', 'rozpocząć, zainaugurować', 'business', '{meetings,presentations}', 'informal', 'B2', '[{"sentence": "We kicked off the new marketing campaign with a live event in London.", "context": "campaign launch review", "tense": "Past Simple", "grammar_note": "kicked off + noun phrase + with + noun phrase"}, {"sentence": "The project is being kicked off next Monday with a team-wide meeting.", "context": "project initiation announcement email", "tense": "Present Continuous Passive (planned future)", "grammar_note": "is being + kicked off + time expression (passive, planned future)"}, {"sentence": "Who will kick off the meeting with the opening remarks?", "context": "conference planning logistics", "tense": "Future Simple (question form)", "grammar_note": "who + will + kick off + noun phrase + with + noun phrase"}, {"sentence": "Kicking off the year with strong sales gave the team tremendous confidence.", "context": "mid-year performance discussion", "tense": "Gerund as subject", "grammar_note": "kicking off + noun phrase + with + noun phrase (gerund subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('line up', 'To arrange or organize something, especially events, activities, or people, in preparation for something.', 'ustawić, zorganizować; zaplanować (w kolejności)', 'business', '{meetings,hr}', 'neutral', 'B2', '[{"sentence": "The recruiter lined up five interviews for the senior management position.", "context": "executive recruitment process", "tense": "Past Simple", "grammar_note": "lined up + number + noun phrase + for + noun phrase"}, {"sentence": "We have several exciting product demos lined up for the trade show.", "context": "event preparation briefing", "tense": "Present Perfect (have + object + lined up)", "grammar_note": "have + noun phrase + lined up + for + event"}, {"sentence": "The PR team is lining up a series of media interviews for the CEO.", "context": "public relations campaign coordination", "tense": "Present Continuous", "grammar_note": "is/are + lining up + noun phrase + for + person"}, {"sentence": "If we can line up the right speakers, the conference will be a huge success.", "context": "event planning committee discussion", "tense": "Conditional (First Conditional with modal)", "grammar_note": "if + can + line up + noun phrase, will + be"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('map out', 'To plan something in detail, showing the steps or stages involved. To outline a strategy or route.', 'zaplanować szczegółowo, nakreślić plan', 'business', '{meetings,presentations}', 'neutral', 'B2', '[{"sentence": "The executive team mapped out a five-year growth strategy during the retreat.", "context": "strategic planning offsite meeting", "tense": "Past Simple", "grammar_note": "mapped out + noun phrase + during + noun phrase"}, {"sentence": "We need to map out the customer journey before designing the new app interface.", "context": "UX design kickoff meeting", "tense": "Infinitive (need to + base form)", "grammar_note": "need to + map out + noun phrase + before + gerund"}, {"sentence": "The entire migration process has been carefully mapped out by the IT department.", "context": "system migration project update", "tense": "Present Perfect Passive", "grammar_note": "has/have been + mapped out + by + agent (passive)"}, {"sentence": "Once we have mapped out the workflow, we can identify bottlenecks.", "context": "process improvement workshop", "tense": "Present Perfect (time clause with ''once'')", "grammar_note": "once + have + mapped out, can + base verb"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('mark down', 'To reduce the price of an item. Also means to note or record something in writing.', 'obniżyć cenę, przecenić; zanotować', 'business', '{finance,daily}', 'neutral', 'B2', '[{"sentence": "The store marked down all winter stock by 30% to clear inventory.", "context": "end-of-season retail clearance", "tense": "Past Simple", "grammar_note": "marked down + noun phrase + by + percentage (separable)"}, {"sentence": "These items have been marked down because they are last season''s collection.", "context": "explaining sale prices to a customer", "tense": "Present Perfect Passive", "grammar_note": "have been + marked down + because + clause (passive)"}, {"sentence": "Mark down the key deadlines in your planner so you do not miss them.", "context": "project manager instruction to the team", "tense": "Imperative", "grammar_note": "base form + noun phrase + in + location + so + clause"}, {"sentence": "If products are not selling, we will mark them down to attract more buyers.", "context": "pricing strategy meeting", "tense": "Future Simple (First Conditional)", "grammar_note": "if + are not selling, will + mark + pronoun + down (separated)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('measure up', 'To be good enough to meet a required standard or expectation. To compare favorably.', 'spełniać oczekiwania, dorównywać (standardom)', 'business', '{hr,meetings}', 'neutral', 'C1', '[{"sentence": "The candidate did not measure up to the expectations set by the hiring panel.", "context": "recruitment debrief after interviews", "tense": "Past Simple", "grammar_note": "did not + measure up to + noun phrase (intransitive + preposition)"}, {"sentence": "Our customer service must measure up to industry-leading standards.", "context": "quality assurance strategy presentation", "tense": "Modal (must + base form)", "grammar_note": "must + measure up to + noun phrase"}, {"sentence": "The new supplier has measured up well against our quality benchmarks.", "context": "vendor performance evaluation", "tense": "Present Perfect", "grammar_note": "has/have + measured up + adverb + against + noun phrase"}, {"sentence": "It remains to be seen whether the product will measure up to consumer expectations.", "context": "pre-launch product review article", "tense": "Future Simple (whether clause)", "grammar_note": "whether + will + measure up to + noun phrase"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('open up', 'To create new opportunities or possibilities. Also means to begin operating a new business or to become more communicative.', 'otworzyć (nowe możliwości/rynek); uruchomić (firmę); otworzyć się', 'business', '{finance,negotiations}', 'neutral', 'B2', '[{"sentence": "The trade agreement opened up new markets for domestic manufacturers.", "context": "international trade policy analysis", "tense": "Past Simple", "grammar_note": "opened up + noun phrase + for + beneficiary"}, {"sentence": "New technologies are opening up opportunities that did not exist a decade ago.", "context": "technology innovation conference keynote", "tense": "Present Continuous", "grammar_note": "are/is + opening up + noun phrase + relative clause"}, {"sentence": "We plan to open up a regional office in Singapore by the end of the year.", "context": "expansion strategy announcement", "tense": "Infinitive (plan to + base form)", "grammar_note": "plan to + open up + noun phrase + by + time expression"}, {"sentence": "Once the new regulations are in place, the sector will open up to foreign investment.", "context": "regulatory reform discussion", "tense": "Future Simple (time clause with ''once'')", "grammar_note": "once + Present Simple, will + open up + to + noun phrase"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('opt in', 'To choose to participate in something or to agree to be included in a scheme or programme.', 'zdecydować się na udział, wyrazić zgodę na włączenie', 'business', '{hr,emails}', 'formal', 'C1', '[{"sentence": "Employees can opt in to the enhanced pension scheme during the enrollment period.", "context": "benefits enrollment communication", "tense": "Modal (can + base form)", "grammar_note": "can + opt in to + noun phrase + during + time expression"}, {"sentence": "Over 80% of staff have opted in to the flexible working arrangements.", "context": "HR report on workplace flexibility", "tense": "Present Perfect", "grammar_note": "have/has + opted in to + noun phrase"}, {"sentence": "Users must actively opt in before their data can be shared with third parties.", "context": "data privacy policy compliance", "tense": "Modal (must + base form, before clause)", "grammar_note": "must + opt in + before + passive clause"}, {"sentence": "If you opted in to the programme last year, your enrolment renews automatically.", "context": "annual benefits renewal notice", "tense": "Past Simple (First Conditional with past reference)", "grammar_note": "if + opted in to, Present Simple (factual conditional)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pencil in', 'To schedule something tentatively, with the understanding that it may change later.', 'wstępnie zaplanować, wpisać ołówkiem (do kalendarza)', 'business', '{meetings,emails}', 'informal', 'B2', '[{"sentence": "I have pencilled you in for a meeting at 3 p.m. on Thursday.", "context": "scheduling an initial meeting with a client", "tense": "Present Perfect", "grammar_note": "have + pencilled + person + in + for + time (separated)"}, {"sentence": "Let us pencil in a follow-up call for next week and confirm the details later.", "context": "wrapping up a preliminary discussion", "tense": "Imperative (let us + base form)", "grammar_note": "let us + pencil in + noun phrase + for + time"}, {"sentence": "The conference was pencilled in for June, but it may be moved to September.", "context": "event logistics email update", "tense": "Passive Voice (Past Simple)", "grammar_note": "was + pencilled in + for + time (passive)"}, {"sentence": "Could you pencil in a slot for the quarterly review before the end of the month?", "context": "assistant scheduling on behalf of a manager", "tense": "Modal (could + base form, polite request)", "grammar_note": "could + subject + pencil in + noun phrase (polite question)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pitch in', 'To contribute effort or help with a task, especially when working as part of a team. Similar to ''chip in'' but with more emphasis on effort.', 'przyłożyć się, pomóc (w zespołowej pracy)', 'both', '{meetings,daily}', 'informal', 'B2', '[{"sentence": "The whole team pitched in to finish the report before the Friday deadline.", "context": "end-of-week crunch to meet a deliverable", "tense": "Past Simple", "grammar_note": "pitched in + to + infinitive (purpose)"}, {"sentence": "If everyone pitches in, we can get the office ready for the client visit by noon.", "context": "preparing for an important client visit", "tense": "Conditional (First Conditional)", "grammar_note": "if + Present Simple, can + base verb"}, {"sentence": "Even senior managers are pitching in with the preparations for the annual gala.", "context": "company-wide event organization", "tense": "Present Continuous", "grammar_note": "are/is + pitching in + with + noun phrase"}, {"sentence": "She was happy to pitch in whenever extra help was needed on the project.", "context": "performance review praising teamwork", "tense": "Infinitive (happy to + base form)", "grammar_note": "happy to + pitch in + whenever + clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('ramp up', 'To increase or expand something rapidly, especially production, activity, or effort.', 'gwałtownie zwiększyć, zintensyfikować', 'business', '{finance,presentations}', 'neutral', 'C1', '[{"sentence": "The factory ramped up production to meet the holiday season demand.", "context": "manufacturing operations review", "tense": "Past Simple", "grammar_note": "ramped up + noun phrase + to + infinitive (purpose)"}, {"sentence": "We have been ramping up our recruitment efforts to fill critical positions.", "context": "HR department quarterly update", "tense": "Present Perfect Continuous", "grammar_note": "have/has been + ramping up + noun phrase + to + infinitive"}, {"sentence": "Security measures will be ramped up ahead of the international summit.", "context": "event security briefing", "tense": "Future Simple Passive", "grammar_note": "will be + ramped up + ahead of + noun phrase (passive)"}, {"sentence": "Ramping up too fast without adequate quality controls can damage the brand.", "context": "operations risk management seminar", "tense": "Gerund as subject", "grammar_note": "ramping up + adverb + without + noun phrase (gerund subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('run by', 'To tell someone about an idea or plan in order to get their opinion or approval.', 'przedstawić (komuś pomysł do oceny), skonsultować', 'business', '{meetings,emails}', 'informal', 'B2', '[{"sentence": "I ran the proposal by my manager before submitting it to the client.", "context": "ensuring internal approval before client submission", "tense": "Past Simple", "grammar_note": "ran + noun phrase + by + person (separated: object between verb and particle)"}, {"sentence": "Can I run something by you quickly before the meeting starts?", "context": "quick check with a colleague before a presentation", "tense": "Modal (can + base form, question)", "grammar_note": "can + subject + run + something + by + person (polite question)"}, {"sentence": "The legal team wants to run the contract terms by external counsel first.", "context": "contract review process", "tense": "Present Simple (wants to + base form)", "grammar_note": "wants to + run + noun phrase + by + person"}, {"sentence": "You should have run the idea by the finance team before announcing it publicly.", "context": "feedback after an unauthorized announcement", "tense": "Modal Perfect (should have + past participle)", "grammar_note": "should have + run + noun phrase + by + person"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('sell out', 'To sell all available stock of a product. Also means to abandon one''s principles for personal gain.', 'wyprzedać (cały zapas); sprzeniewierzyć się zasadom', 'business', '{finance,daily}', 'neutral', 'B2', '[{"sentence": "The limited edition collection sold out within hours of going on sale.", "context": "product launch performance analysis", "tense": "Past Simple", "grammar_note": "sold out + within + time expression (intransitive)"}, {"sentence": "Tickets for the company''s annual charity gala have already sold out.", "context": "event management update", "tense": "Present Perfect", "grammar_note": "have/has + already + sold out (intransitive)"}, {"sentence": "If we do not increase production, the product will sell out before the holiday season.", "context": "supply chain planning meeting", "tense": "Future Simple (First Conditional)", "grammar_note": "if + do not + base verb, will + sell out + before + time"}, {"sentence": "The event was completely sold out, so we had to arrange an overflow venue.", "context": "post-event logistics report", "tense": "Passive Voice (Past Simple)", "grammar_note": "was + sold out (passive/adjectival use)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('size up', 'To assess or evaluate someone or something carefully in order to form a judgement.', 'ocenić, oszacować, zmierzyć wzrokiem', 'business', '{negotiations,meetings}', 'informal', 'C1', '[{"sentence": "The investors sized up the startup before deciding whether to fund it.", "context": "venture capital due diligence process", "tense": "Past Simple", "grammar_note": "sized up + noun phrase + before + gerund clause"}, {"sentence": "She is sizing up the competition to identify gaps in their product offering.", "context": "competitive analysis research", "tense": "Present Continuous", "grammar_note": "is/are + sizing up + noun phrase + to + infinitive"}, {"sentence": "The market opportunity needs to be sized up before we commit any resources.", "context": "new market entry evaluation", "tense": "Passive (needs to be + past participle)", "grammar_note": "needs to be + sized up + before + clause (passive infinitive)"}, {"sentence": "Having sized up the situation, the negotiator adjusted her strategy accordingly.", "context": "midpoint of a high-stakes negotiation", "tense": "Perfect Participle Clause", "grammar_note": "having + sized up + noun phrase (participle clause)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('smooth over', 'To make a problem, disagreement, or difficult situation seem less serious or to resolve it diplomatically.', 'załagodzić, wygładzić (sytuację/konflikt)', 'business', '{negotiations,meetings}', 'neutral', 'C1', '[{"sentence": "The account manager smoothed over the dispute with the client by offering a discount.", "context": "client retention after a complaint", "tense": "Past Simple", "grammar_note": "smoothed over + noun phrase + by + gerund (separable)"}, {"sentence": "It will take more than an apology to smooth over the damage caused by the data breach.", "context": "PR crisis management discussion", "tense": "Infinitive (it will take + to + base form)", "grammar_note": "it will take + noun + to + smooth over + noun phrase"}, {"sentence": "She has smoothed over tensions between the two departments on many occasions.", "context": "leadership review highlighting interpersonal skills", "tense": "Present Perfect", "grammar_note": "has/have + smoothed over + noun phrase + on + frequency"}, {"sentence": "The situation cannot simply be smoothed over; it requires a formal investigation.", "context": "compliance officer responding to misconduct allegations", "tense": "Passive Voice (modal: cannot + be + past participle)", "grammar_note": "cannot + be + smoothed over (passive with negative modal)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('stake out', 'To define or claim a position, territory, or area of interest. To establish one''s stance clearly.', 'wyznaczyć, zająć (stanowisko/pozycję); zarezerwować (dla siebie)', 'business', '{negotiations,presentations}', 'formal', 'C1', '[{"sentence": "The company staked out its position as the market leader in sustainable packaging.", "context": "brand positioning press release", "tense": "Past Simple", "grammar_note": "staked out + noun phrase + as + role/identity"}, {"sentence": "We are staking out new territory in the fintech space with our latest product.", "context": "product launch presentation to investors", "tense": "Present Continuous", "grammar_note": "are/is + staking out + noun phrase + in + area + with + means"}, {"sentence": "Each division has staked out its own area of expertise within the broader organization.", "context": "organizational review and restructuring", "tense": "Present Perfect", "grammar_note": "has/have + staked out + noun phrase + within + context"}, {"sentence": "To stake out a competitive advantage, the firm invested heavily in R&D.", "context": "annual report narrative on innovation strategy", "tense": "Infinitive of purpose", "grammar_note": "to + stake out + noun phrase (infinitive of purpose) + main clause"}]');
