-- ============================================
-- Import phrasal verbs: ID 101-150 (50 wpisów)
-- Wklej ten SQL w Supabase SQL Editor i kliknij Run
-- ============================================

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('break up', 'To end a romantic relationship. Also, to separate into smaller parts or pieces.', 'zerwać (związek); rozpadać się na części', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "They broke up after five years of dating.", "context": "telling a friend about a couple''s separation", "tense": "Past Simple", "grammar_note": "intransitive use — no direct object"}, {"sentence": "She has broken up with her boyfriend and moved back home.", "context": "sharing recent personal news with a colleague", "tense": "Present Perfect", "grammar_note": "phrasal verb + with + object (break up with someone)"}, {"sentence": "If you keep arguing like this, you will break up sooner or later.", "context": "warning a friend about relationship problems", "tense": "Future Simple", "grammar_note": "conditional-style prediction with will + base form"}, {"sentence": "The ice on the lake is breaking up as spring arrives.", "context": "describing seasonal changes in nature", "tense": "Present Continuous", "grammar_note": "intransitive use — literal meaning of separating into pieces"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('bring about', 'To cause something to happen. Often used for significant changes or events.', 'spowodować; doprowadzić do (czegoś)', 'both', '{daily,meetings}', 'neutral', 'C1', '[{"sentence": "The new policy brought about major improvements in employee satisfaction.", "context": "reviewing the effects of a workplace policy", "tense": "Past Simple", "grammar_note": "transitive — separable phrasal verb with noun object after particle"}, {"sentence": "Technology has brought about enormous changes in how we communicate.", "context": "discussing social trends in a class debate", "tense": "Present Perfect", "grammar_note": "transitive with noun phrase as direct object"}, {"sentence": "The reforms are expected to bring about lasting economic stability.", "context": "political commentary in a newspaper article", "tense": "Future Simple", "grammar_note": "passive voice (be expected to) + infinitive"}, {"sentence": "Bringing about real change requires patience and persistence.", "context": "motivational speech about social activism", "tense": "Present Simple", "grammar_note": "gerund as subject of the sentence"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('calm down', 'To become less agitated, anxious, or emotional. Also used transitively to help someone else relax.', 'uspokoić się; uspokajać (kogoś)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "He calmed down after taking a few deep breaths.", "context": "describing how someone managed stress before an exam", "tense": "Past Simple", "grammar_note": "intransitive use — no object needed"}, {"sentence": "Calm down and think about this rationally.", "context": "advising an upset friend during an argument", "tense": "Imperative", "grammar_note": "imperative mood — direct command"}, {"sentence": "She has been trying to calm the children down all afternoon.", "context": "a parent dealing with overexcited kids at a party", "tense": "Present Perfect Continuous", "grammar_note": "transitive separable — object between verb and particle"}, {"sentence": "If you calmed down, you would see the situation more clearly.", "context": "giving advice during a heated discussion", "tense": "Second Conditional", "grammar_note": "conditional clause with past tense for hypothetical present"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('catch up', 'To reach the same level or position as someone who is ahead. Also, to spend time learning about things you missed.', 'dogonić; nadrobić zaległości', 'both', '{daily,meetings}', 'neutral', 'B2', '[{"sentence": "I was behind on the project, but I caught up over the weekend.", "context": "explaining progress on a work assignment", "tense": "Past Simple", "grammar_note": "intransitive — used with adverbial phrase of time"}, {"sentence": "We should catch up for coffee sometime next week.", "context": "suggesting a social meeting with an old friend", "tense": "Present Simple", "grammar_note": "modal should + base form for suggestion"}, {"sentence": "She has finally caught up with the rest of the class after being ill.", "context": "teacher updating a parent about a student''s progress", "tense": "Present Perfect", "grammar_note": "phrasal verb + with + object (catch up with someone)"}, {"sentence": "He is catching up on all the episodes he missed during his holiday.", "context": "talking about watching a TV series", "tense": "Present Continuous", "grammar_note": "phrasal verb + on (catch up on something)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('check out', 'To examine or look at something interesting. Also, to leave a hotel or to pay and leave a shop.', 'sprawdzić; wymeldować się; obejrzeć (coś ciekawego)', 'general', '{daily,travel}', 'informal', 'B2', '[{"sentence": "We checked out of the hotel at ten o''clock this morning.", "context": "describing departure from accommodation while travelling", "tense": "Past Simple", "grammar_note": "intransitive + preposition of (check out of a place)"}, {"sentence": "You should check out that new restaurant on the corner.", "context": "recommending a place to a friend", "tense": "Imperative", "grammar_note": "modal should + base form for strong recommendation"}, {"sentence": "Have you checked out the new art exhibition at the gallery?", "context": "asking about a cultural event in town", "tense": "Present Perfect", "grammar_note": "transitive — direct object after the particle"}, {"sentence": "Guests must check out before noon or they will be charged extra.", "context": "hotel policy notice at reception", "tense": "Present Simple", "grammar_note": "modal must + base form expressing obligation"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('clean up', 'To make a place tidy by removing dirt or mess. Also, to remove unwanted elements from something.', 'posprzątać; uporządkować', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "We cleaned up the entire kitchen after the dinner party.", "context": "describing post-event tidying at home", "tense": "Past Simple", "grammar_note": "transitive — direct object after particle"}, {"sentence": "The beach is being cleaned up by volunteers this Saturday.", "context": "community announcement about an environmental event", "tense": "Present Continuous", "grammar_note": "passive voice — is being + past participle"}, {"sentence": "If everyone helps, we will clean up in no time.", "context": "motivating a group to tidy a shared space", "tense": "Future Simple", "grammar_note": "first conditional — if + present, will + base form"}, {"sentence": "He had cleaned up the mess before his parents arrived.", "context": "teenager tidying after a party before parents come home", "tense": "Past Perfect", "grammar_note": "past perfect for an action completed before another past event"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('come back', 'To return to a place where you were before. Also, to become popular or fashionable again.', 'wrócić; powrócić', 'general', '{daily,travel}', 'neutral', 'B2', '[{"sentence": "She came back from her trip feeling completely refreshed.", "context": "describing how someone felt after a holiday", "tense": "Past Simple", "grammar_note": "intransitive + from + noun (indicating origin)"}, {"sentence": "Vinyl records have come back into fashion in recent years.", "context": "discussing cultural trends in music", "tense": "Present Perfect", "grammar_note": "intransitive — figurative use meaning to become popular again"}, {"sentence": "Will you come back before dinner or should I eat without you?", "context": "asking a family member about their plans", "tense": "Future Simple", "grammar_note": "yes/no question with will — asking about future plans"}, {"sentence": "I was coming back from the shop when I saw the accident.", "context": "reporting an incident to a friend", "tense": "Past Continuous", "grammar_note": "past continuous for background action interrupted by another event"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('cross out', 'To draw a line through written words to show they are wrong or no longer needed.', 'skreślić; wykreślić; przekreślić', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She crossed out her old address and wrote the new one above it.", "context": "updating personal details on a form", "tense": "Past Simple", "grammar_note": "transitive separable — object between verb and particle"}, {"sentence": "Cross out any items on the list that you have already completed.", "context": "instructions for managing a to-do list", "tense": "Imperative", "grammar_note": "imperative with direct object after particle"}, {"sentence": "Several names had been crossed out before the final version was printed.", "context": "reviewing a document with prior edits", "tense": "Past Perfect", "grammar_note": "passive voice — had been + past participle"}, {"sentence": "He is crossing out the incorrect answers on his exam paper.", "context": "student correcting mistakes during a test", "tense": "Present Continuous", "grammar_note": "transitive — object after particle in progressive form"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('cut off', 'To stop the supply of something, such as electricity or water. Also, to interrupt someone who is speaking.', 'odciąć; przerwać (komuś wypowiedź); odłączyć', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "The electricity was cut off because they hadn''t paid the bill.", "context": "explaining why a household lost power", "tense": "Past Simple", "grammar_note": "passive voice — was + past participle"}, {"sentence": "Please don''t cut me off — let me finish what I''m saying.", "context": "asking someone not to interrupt during a conversation", "tense": "Imperative", "grammar_note": "negative imperative with pronoun between verb and particle"}, {"sentence": "The village has been cut off from the main road by heavy flooding.", "context": "news report about a natural disaster", "tense": "Present Perfect", "grammar_note": "passive voice — has been + past participle + from"}, {"sentence": "If they cut off our internet, we won''t be able to work from home.", "context": "discussing potential service disruptions", "tense": "First Conditional", "grammar_note": "first conditional — if + present simple, will + base form"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('do over', 'To do something again from the beginning, usually because it was done incorrectly the first time.', 'zrobić od nowa; powtórzyć', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "The teacher asked him to do the assignment over because of too many errors.", "context": "school situation where work needs to be redone", "tense": "Past Simple", "grammar_note": "transitive separable — object between verb and particle"}, {"sentence": "If I could do it over, I would choose a different university.", "context": "reflecting on past life decisions", "tense": "Second Conditional", "grammar_note": "conditional with could + base form for hypothetical past"}, {"sentence": "The entire project will have to be done over from scratch.", "context": "manager delivering bad news about a failed project", "tense": "Future Simple", "grammar_note": "passive voice with modal — will have to be + past participle"}, {"sentence": "She has done the report over three times and it''s still not perfect.", "context": "expressing frustration about repeated work", "tense": "Present Perfect", "grammar_note": "transitive separable — object between verb and particle with adverb"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('dress up', 'To wear formal or fancy clothes. Also, to wear a costume or disguise.', 'wystroić się; przebrać się (za kogoś/coś)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Everyone dressed up for the New Year''s Eve gala.", "context": "describing a formal party", "tense": "Past Simple", "grammar_note": "intransitive — no object needed"}, {"sentence": "The children are dressing up as superheroes for the school play.", "context": "preparing for a costume event at school", "tense": "Present Continuous", "grammar_note": "intransitive + as (dress up as something)"}, {"sentence": "You don''t need to dress up — it''s a casual dinner.", "context": "reassuring a guest about a dress code", "tense": "Present Simple", "grammar_note": "negative with need to + base form"}, {"sentence": "She had dressed up the room with fairy lights and balloons before the guests arrived.", "context": "decorating a space for a birthday party", "tense": "Past Perfect", "grammar_note": "transitive separable — figurative meaning to decorate"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('eat out', 'To have a meal at a restaurant or somewhere other than at home.', 'jeść na mieście; jeść w restauracji', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "We ate out at a lovely Italian place last Friday.", "context": "telling a friend about a recent dinner experience", "tense": "Past Simple", "grammar_note": "intransitive + at + place"}, {"sentence": "They have been eating out almost every night since the kitchen renovation started.", "context": "explaining why someone spends a lot on food", "tense": "Present Perfect Continuous", "grammar_note": "continuous form emphasising duration of repeated action"}, {"sentence": "Shall we eat out tonight or cook something at home?", "context": "making plans for the evening with a partner", "tense": "Future Simple", "grammar_note": "shall for suggestion/offer in question form"}, {"sentence": "Eating out every day can become quite expensive.", "context": "discussing budgeting and lifestyle choices", "tense": "Present Simple", "grammar_note": "gerund as subject of the sentence"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('fall apart', 'To break into pieces or stop working properly. Also used figuratively when something or someone collapses emotionally.', 'rozpadać się; rozlecieć się; załamać się', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "The old bookcase finally fell apart after years of use.", "context": "describing furniture breaking at home", "tense": "Past Simple", "grammar_note": "intransitive — no object; literal meaning"}, {"sentence": "Their marriage has been falling apart for months.", "context": "discussing a couple''s relationship difficulties", "tense": "Present Perfect Continuous", "grammar_note": "continuous form emphasising ongoing deterioration"}, {"sentence": "If the deal falls apart, we''ll need to find another buyer.", "context": "discussing contingency plans in a business context", "tense": "First Conditional", "grammar_note": "first conditional — if + present simple, will + base form"}, {"sentence": "She was falling apart emotionally after hearing the terrible news.", "context": "describing someone''s reaction to a shocking event", "tense": "Past Continuous", "grammar_note": "past continuous for ongoing emotional state — figurative meaning"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('fill out', 'To complete a form, questionnaire, or document by writing the required information.', 'wypełnić (formularz, ankietę)', 'both', '{daily,hr}', 'neutral', 'B2', '[{"sentence": "Please fill out this application form and return it to the front desk.", "context": "receptionist giving instructions to a visitor", "tense": "Imperative", "grammar_note": "imperative with direct object after particle"}, {"sentence": "She filled out the visa application without making a single mistake.", "context": "completing official paperwork for travel", "tense": "Past Simple", "grammar_note": "transitive — direct object after particle"}, {"sentence": "All the forms must be filled out before the interview begins.", "context": "HR process for new job candidates", "tense": "Present Simple", "grammar_note": "passive voice with modal must — must be + past participle"}, {"sentence": "Have you filled out the survey that was sent to you by email?", "context": "following up on a customer feedback request", "tense": "Present Perfect", "grammar_note": "yes/no question in present perfect with relative clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('find out', 'To discover or learn new information, often something that was previously unknown or hidden.', 'dowiedzieć się; odkryć', 'both', '{daily,meetings}', 'neutral', 'B2', '[{"sentence": "We found out that the flight had been cancelled when we arrived at the airport.", "context": "describing a travel problem", "tense": "Past Simple", "grammar_note": "transitive + that-clause as object"}, {"sentence": "She is trying to find out who is responsible for the leak.", "context": "investigating a problem at work", "tense": "Present Continuous", "grammar_note": "trying to + find out + embedded wh-clause"}, {"sentence": "If he finds out the truth, he will be furious.", "context": "warning someone about possible consequences", "tense": "First Conditional", "grammar_note": "first conditional — if + present simple, will + adjective"}, {"sentence": "I had already found out about the surprise party before they told me.", "context": "recounting how a secret was revealed too early", "tense": "Past Perfect", "grammar_note": "past perfect + about + noun phrase"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get away', 'To escape from a place or a person. Also, to go somewhere for a holiday or break.', 'uciec; wyrwać się (na wakacje); oddalić się', 'general', '{daily,travel}', 'informal', 'B2', '[{"sentence": "The thief got away before the police arrived.", "context": "describing a crime scene", "tense": "Past Simple", "grammar_note": "intransitive — no object needed"}, {"sentence": "We need to get away for a few days — I''m completely exhausted.", "context": "suggesting a short holiday to a partner", "tense": "Present Simple", "grammar_note": "need to + base form expressing necessity"}, {"sentence": "She has gotten away with being late to class so many times.", "context": "commenting on someone who avoids consequences", "tense": "Present Perfect", "grammar_note": "phrasal verb + with + gerund (get away with doing something)"}, {"sentence": "If we had left earlier, we would have gotten away from the traffic.", "context": "regretting not leaving sooner for a road trip", "tense": "Third Conditional", "grammar_note": "third conditional — if + past perfect, would have + past participle"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get by', 'To manage to survive or live with difficulty, especially with limited money or resources.', 'dawać sobie radę; wiązać koniec z końcem', 'general', '{daily,finance}', 'neutral', 'B2', '[{"sentence": "They got by on a single income while she was studying.", "context": "describing financial hardship during university years", "tense": "Past Simple", "grammar_note": "intransitive + on + noun phrase (source of income)"}, {"sentence": "We can get by without a car if we use public transport.", "context": "discussing ways to reduce household expenses", "tense": "Present Simple", "grammar_note": "modal can + base form + without + noun"}, {"sentence": "She has been getting by with freelance work until she finds a permanent job.", "context": "explaining a temporary employment situation", "tense": "Present Perfect Continuous", "grammar_note": "continuous form + with + noun phrase"}, {"sentence": "If prices keep rising, many families won''t be able to get by.", "context": "discussing the impact of inflation on society", "tense": "First Conditional", "grammar_note": "first conditional with negative — won''t be able to + base form"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get over', 'To recover from an illness, shock, or emotional upset. Also, to overcome a difficulty.', 'dojść do siebie; pogodzić się z czymś; przejść (chorobę)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "It took him weeks to get over the flu.", "context": "describing recovery from an illness", "tense": "Past Simple", "grammar_note": "it takes + person + time + to + infinitive"}, {"sentence": "She still hasn''t gotten over the loss of her dog.", "context": "talking about grief and emotional recovery", "tense": "Present Perfect", "grammar_note": "negative present perfect with still for emphasis"}, {"sentence": "You''ll get over it eventually — everyone goes through tough times.", "context": "consoling a friend after a breakup", "tense": "Future Simple", "grammar_note": "will + base form for reassurance about the future"}, {"sentence": "Getting over your fear of public speaking takes practice.", "context": "advice about personal development", "tense": "Present Simple", "grammar_note": "gerund phrase as subject of the sentence"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get up', 'To rise from bed after sleeping. Also, to stand up from a sitting or lying position.', 'wstać (z łóżka); podnieść się', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "I got up at six o''clock to catch the early train.", "context": "explaining a morning routine on a workday", "tense": "Past Simple", "grammar_note": "intransitive + at + time expression"}, {"sentence": "She usually gets up before everyone else in the family.", "context": "describing someone''s daily habits", "tense": "Present Simple", "grammar_note": "adverb of frequency + present simple for habitual action"}, {"sentence": "He was getting up from his chair when the phone rang.", "context": "narrating a sequence of events at home", "tense": "Past Continuous", "grammar_note": "past continuous interrupted by past simple event"}, {"sentence": "If you got up earlier, you wouldn''t always be late for work.", "context": "giving advice to someone with punctuality issues", "tense": "Second Conditional", "grammar_note": "second conditional — if + past simple, would + base form"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('give away', 'To give something to someone for free. Also, to reveal a secret or hidden information accidentally.', 'oddać za darmo; rozdać; zdradzić (sekret)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She gave away all her old clothes to charity.", "context": "describing a decluttering effort at home", "tense": "Past Simple", "grammar_note": "transitive separable — object after particle + to + recipient"}, {"sentence": "Don''t give the ending away — I haven''t seen the film yet!", "context": "asking someone not to spoil a movie", "tense": "Imperative", "grammar_note": "negative imperative with object between verb and particle"}, {"sentence": "The company has given away thousands of free samples this month.", "context": "marketing promotion for a new product", "tense": "Present Perfect", "grammar_note": "transitive — object after particle with quantifier"}, {"sentence": "His nervous smile was giving away the fact that he was lying.", "context": "noticing someone''s dishonesty through body language", "tense": "Past Continuous", "grammar_note": "past continuous — ongoing action revealing something gradually"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('give up', 'To stop trying to do something because it is too difficult. Also, to quit a habit or activity.', 'poddać się; zrezygnować; rzucić (nałóg)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "He gave up smoking ten years ago and hasn''t touched a cigarette since.", "context": "talking about overcoming a bad habit", "tense": "Past Simple", "grammar_note": "transitive — gerund as direct object (give up doing something)"}, {"sentence": "Never give up on your dreams, no matter how hard things get.", "context": "motivational advice to a younger person", "tense": "Imperative", "grammar_note": "negative imperative + on + noun (give up on something)"}, {"sentence": "She has given up trying to convince him to change his mind.", "context": "describing someone''s resignation after many attempts", "tense": "Present Perfect", "grammar_note": "present perfect + gerund complement (give up trying)"}, {"sentence": "If I were you, I wouldn''t give up so easily.", "context": "encouraging a friend who feels defeated", "tense": "Second Conditional", "grammar_note": "second conditional with if I were you for advice"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go back', 'To return to a place you were before. Also, to return to a previous topic or point in time.', 'wracać; cofnąć się (do tematu, w czasie)', 'general', '{daily,travel}', 'neutral', 'B2', '[{"sentence": "We went back to the same hotel we stayed at five years ago.", "context": "revisiting a favourite holiday destination", "tense": "Past Simple", "grammar_note": "intransitive + to + place"}, {"sentence": "I would love to go back to Japan someday.", "context": "expressing a travel wish in conversation", "tense": "Present Simple", "grammar_note": "would love to + base form for wishes"}, {"sentence": "Let''s go back to what you were saying about the budget.", "context": "redirecting a meeting discussion to a previous point", "tense": "Imperative", "grammar_note": "let''s + base form for suggestion"}, {"sentence": "Their friendship goes back to when they were in primary school.", "context": "describing the length of a long friendship", "tense": "Present Simple", "grammar_note": "intransitive + to — figurative meaning of dating back"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go on', 'To continue doing something or to happen. Also, to proceed to the next thing.', 'kontynuować; dziać się; trwać dalej', 'both', '{daily,presentations}', 'neutral', 'B2', '[{"sentence": "The meeting went on for three hours without a break.", "context": "complaining about a long meeting at work", "tense": "Past Simple", "grammar_note": "intransitive + for + duration"}, {"sentence": "Please go on — I didn''t mean to interrupt.", "context": "apologising for cutting in during a conversation", "tense": "Imperative", "grammar_note": "imperative — polite request to continue"}, {"sentence": "What''s going on over there? I can hear a lot of noise.", "context": "asking about a commotion nearby", "tense": "Present Continuous", "grammar_note": "wh-question with continuous form — meaning to happen"}, {"sentence": "She had gone on talking even after the bell rang.", "context": "describing a teacher who continued past the end of class", "tense": "Past Perfect", "grammar_note": "past perfect + gerund (go on doing something — continue)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go out', 'To leave home for entertainment or social activities. Also, when a light or fire stops burning.', 'wychodzić (z domu); wygasać (o ogniu, świetle)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "We went out for dinner and a movie last Saturday night.", "context": "talking about weekend plans with friends", "tense": "Past Simple", "grammar_note": "intransitive + for + noun (purpose)"}, {"sentence": "She doesn''t go out as much as she used to since the baby was born.", "context": "discussing lifestyle changes after becoming a parent", "tense": "Present Simple", "grammar_note": "negative + comparative structure (as much as)"}, {"sentence": "The candle had gone out by the time we got back to the room.", "context": "noticing a change after returning to a place", "tense": "Past Perfect", "grammar_note": "past perfect — literal meaning of a flame extinguishing"}, {"sentence": "Are you going out tonight or staying in?", "context": "asking a flatmate about evening plans", "tense": "Present Continuous", "grammar_note": "present continuous for near-future plans — or-question"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('grow up', 'To develop from a child into an adult. Also used to tell someone to behave more maturely.', 'dorastać; dorosnąć; wyrosnąć', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "He grew up in a small village in the south of Poland.", "context": "sharing childhood background with new friends", "tense": "Past Simple", "grammar_note": "intransitive + in + place"}, {"sentence": "Oh, grow up! You''re acting like a five-year-old.", "context": "telling someone to stop being childish", "tense": "Imperative", "grammar_note": "imperative — used to scold someone for immature behaviour"}, {"sentence": "Children who grow up bilingual often find it easier to learn additional languages.", "context": "discussing language development in an educational context", "tense": "Present Simple", "grammar_note": "relative clause with who + present simple for general truth"}, {"sentence": "By the time you see them again, the kids will have grown up so much.", "context": "commenting on how quickly children change", "tense": "Future Perfect", "grammar_note": "future perfect — will have + past participle for completion by a future time"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hang out', 'To spend time relaxing or socialising in a casual way, often without a specific plan.', 'spędzać czas (luźno); spotykać się towarzysko', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "We hung out at the park all afternoon doing nothing.", "context": "describing a lazy day with friends", "tense": "Past Simple", "grammar_note": "intransitive + at + place"}, {"sentence": "She has been hanging out with her university friends a lot lately.", "context": "commenting on someone''s social life", "tense": "Present Perfect Continuous", "grammar_note": "continuous + with + person for ongoing social activity"}, {"sentence": "Do you want to hang out this weekend?", "context": "casually inviting a friend to spend time together", "tense": "Present Simple", "grammar_note": "do you want to + infinitive for informal invitation"}, {"sentence": "They were hanging out at the cafe when the rainstorm started.", "context": "narrating events during a sudden change of weather", "tense": "Past Continuous", "grammar_note": "past continuous for background activity interrupted by an event"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hang up', 'To end a phone call by putting the phone down or pressing a button. Also, to put something on a hook or hanger.', 'rozłączyć się (telefon); powiesić (na wieszaku)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She hung up the phone before I could say goodbye.", "context": "describing an abruptly ended phone call", "tense": "Past Simple", "grammar_note": "transitive — direct object after particle"}, {"sentence": "Don''t hang up — I have one more thing to tell you.", "context": "trying to keep someone on the phone", "tense": "Imperative", "grammar_note": "negative imperative — intransitive use"}, {"sentence": "He always hangs up his coat as soon as he gets home.", "context": "describing a daily habit", "tense": "Present Simple", "grammar_note": "transitive separable — object between verb and particle"}, {"sentence": "If she hangs up on me again, I won''t call back.", "context": "expressing frustration about someone''s phone behaviour", "tense": "First Conditional", "grammar_note": "first conditional + hang up on someone (ending call rudely)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('head out', 'To leave a place and start going somewhere. A casual way of saying to depart.', 'wychodzić; ruszać (w drogę); wyruszać', 'general', '{daily,travel}', 'informal', 'B2', '[{"sentence": "We headed out early in the morning to avoid the traffic.", "context": "starting a road trip", "tense": "Past Simple", "grammar_note": "intransitive + adverb of time"}, {"sentence": "I''m heading out now — see you later!", "context": "saying goodbye to colleagues at the end of the day", "tense": "Present Continuous", "grammar_note": "present continuous for immediate action"}, {"sentence": "What time are you planning to head out tomorrow?", "context": "asking about departure plans", "tense": "Present Continuous", "grammar_note": "planning to + base form for future arrangement"}, {"sentence": "We should head out before it gets dark.", "context": "suggesting departure while hiking in the countryside", "tense": "Present Simple", "grammar_note": "modal should + base form for suggestion with time clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hold up', 'To delay or cause a delay. Also, to raise something for others to see, or to rob a place using threats.', 'opóźniać; wstrzymywać; podnosić (do góry); napadać (na bank)', 'both', '{daily,meetings}', 'neutral', 'B2', '[{"sentence": "The heavy rain held up traffic for over two hours.", "context": "explaining why someone was late", "tense": "Past Simple", "grammar_note": "transitive — object after particle"}, {"sentence": "Sorry I''m late — I was held up at the office.", "context": "apologising for arriving late to a dinner", "tense": "Past Simple", "grammar_note": "passive voice — was + past participle"}, {"sentence": "Could you hold up that document so everyone can see it?", "context": "asking someone to display something during a meeting", "tense": "Present Simple", "grammar_note": "polite request with could + base form — literal meaning"}, {"sentence": "The project has been held up due to a lack of funding.", "context": "explaining delays in a business project", "tense": "Present Perfect", "grammar_note": "passive voice — has been + past participle + due to"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hurry up', 'To do something more quickly or to move faster. Often used to urge someone to be quicker.', 'pospieszyć się; pośpiesz się', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "Hurry up or we''ll miss the bus!", "context": "rushing a family member in the morning", "tense": "Imperative", "grammar_note": "imperative + or + consequence clause"}, {"sentence": "She hurried up and finished packing just in time.", "context": "getting ready for a trip at the last moment", "tense": "Past Simple", "grammar_note": "intransitive + and + coordinated clause"}, {"sentence": "I wish they would hurry up — we''ve been waiting for an hour.", "context": "expressing impatience while waiting for friends", "tense": "Present Simple", "grammar_note": "wish + would + base form for desire about others'' behaviour"}, {"sentence": "He was hurrying up to get everything ready before the guests arrived.", "context": "preparing for a dinner party under time pressure", "tense": "Past Continuous", "grammar_note": "past continuous + to-infinitive of purpose"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('keep away', 'To stay at a distance from something or someone. Also, to prevent someone from coming near.', 'trzymać się z daleka; trzymać z dala (od czegoś/kogoś)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Keep away from the edge — it''s dangerous!", "context": "warning someone near a cliff while hiking", "tense": "Imperative", "grammar_note": "imperative + from + noun (source of danger)"}, {"sentence": "The fence keeps wild animals away from the garden.", "context": "explaining the purpose of a garden fence", "tense": "Present Simple", "grammar_note": "transitive separable — object between verb and particle"}, {"sentence": "She had kept away from sugary food for months before her diet failed.", "context": "describing a failed attempt at healthy eating", "tense": "Past Perfect", "grammar_note": "past perfect + from + noun for duration before another event"}, {"sentence": "If you keep away from negative people, you''ll feel much happier.", "context": "giving life advice to a friend", "tense": "First Conditional", "grammar_note": "first conditional — if + present simple, will + base form"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('knock out', 'To make someone unconscious, especially by hitting them. Also, to eliminate someone from a competition.', 'znokautować; powalić; wyeliminować (z konkursu)', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "The boxer knocked out his opponent in the third round.", "context": "describing a boxing match result", "tense": "Past Simple", "grammar_note": "transitive separable — object after particle"}, {"sentence": "Our team was knocked out of the tournament in the semi-finals.", "context": "discussing sports competition results", "tense": "Past Simple", "grammar_note": "passive voice — was + past participle + out of"}, {"sentence": "The sleeping pill will knock you out for at least eight hours.", "context": "doctor explaining the effect of medication", "tense": "Future Simple", "grammar_note": "transitive separable — pronoun between verb and particle"}, {"sentence": "That spicy food really knocked me out — I fell asleep on the sofa.", "context": "joking about feeling sleepy after a heavy meal", "tense": "Past Simple", "grammar_note": "transitive separable — figurative informal meaning"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('leave out', 'To not include something or someone, either intentionally or by mistake.', 'pominąć; wykluczyć; nie uwzględnić', 'both', '{daily,emails}', 'neutral', 'B2', '[{"sentence": "You left out an important detail in your report.", "context": "pointing out a missing element in a work document", "tense": "Past Simple", "grammar_note": "transitive separable — object after particle"}, {"sentence": "Make sure no one is left out of the invitation list.", "context": "organising a team event at work", "tense": "Imperative", "grammar_note": "passive voice with make sure — is + past participle + of"}, {"sentence": "She always feels left out when her friends make plans without her.", "context": "describing someone who feels excluded socially", "tense": "Present Simple", "grammar_note": "feels + past participle used as adjective"}, {"sentence": "Several key figures had been left out of the documentary.", "context": "reviewing a historical film and noting omissions", "tense": "Past Perfect", "grammar_note": "passive voice — had been + past participle + of"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('let in', 'To allow someone or something to enter a place.', 'wpuścić (do środka)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Could you let me in? I forgot my keys.", "context": "asking a flatmate to open the door", "tense": "Present Simple", "grammar_note": "polite request with could — pronoun between verb and particle"}, {"sentence": "The security guard let us in after checking our tickets.", "context": "entering a venue for a concert", "tense": "Past Simple", "grammar_note": "transitive separable — pronoun between verb and particle + after + gerund"}, {"sentence": "Don''t let the cat in — she''ll make a mess.", "context": "warning someone not to open the door for a pet", "tense": "Imperative", "grammar_note": "negative imperative with object between verb and particle"}, {"sentence": "If we hadn''t been let in early, we would have missed the opening act.", "context": "discussing how lucky it was to enter a show early", "tense": "Third Conditional", "grammar_note": "third conditional passive — if + past perfect passive, would have + past participle"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('lie down', 'To put yourself in a flat, horizontal position, usually on a bed or the floor.', 'położyć się; kłaść się', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "I need to lie down for a few minutes — I have a terrible headache.", "context": "feeling unwell and wanting to rest", "tense": "Present Simple", "grammar_note": "need to + base form expressing necessity"}, {"sentence": "She lay down on the sofa and fell asleep almost immediately.", "context": "describing someone resting after a long day", "tense": "Past Simple", "grammar_note": "intransitive + on + place (note irregular past: lay)"}, {"sentence": "The doctor told him to lie down and rest for at least two days.", "context": "medical advice after a minor procedure", "tense": "Past Simple", "grammar_note": "reported speech with to-infinitive (told someone to do something)"}, {"sentence": "The dog is lying down in the shade to escape the heat.", "context": "observing a pet''s behaviour on a hot day", "tense": "Present Continuous", "grammar_note": "present continuous + to-infinitive of purpose"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('look after', 'To take care of someone or something by keeping them safe, healthy, or in good condition.', 'opiekować się; zajmować się (kimś/czymś)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She looked after her elderly mother for several years.", "context": "describing a period of caregiving within a family", "tense": "Past Simple", "grammar_note": "inseparable phrasal verb + direct object"}, {"sentence": "Who is looking after the children while you''re at work?", "context": "asking about childcare arrangements", "tense": "Present Continuous", "grammar_note": "wh-question with present continuous"}, {"sentence": "Can you look after my plants while I''m on holiday?", "context": "asking a neighbour for a favour before travelling", "tense": "Present Simple", "grammar_note": "polite request with can + base form"}, {"sentence": "The house had been well looked after by the previous owners.", "context": "commenting on the condition of a property during a viewing", "tense": "Past Perfect", "grammar_note": "passive voice — had been + adverb + past participle"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('look for', 'To try to find something or someone by searching or investigating.', 'szukać (czegoś/kogoś)', 'both', '{daily,hr}', 'neutral', 'B2', '[{"sentence": "I''ve been looking for my car keys all morning.", "context": "frustrated about a lost item before leaving the house", "tense": "Present Perfect Continuous", "grammar_note": "continuous form emphasising duration of the search"}, {"sentence": "She is looking for a new job in the tech industry.", "context": "discussing someone''s career plans", "tense": "Present Continuous", "grammar_note": "inseparable phrasal verb + direct object"}, {"sentence": "What exactly are you looking for in a candidate?", "context": "HR interview question about ideal qualifications", "tense": "Present Continuous", "grammar_note": "wh-question with preposition at the end"}, {"sentence": "They looked for the missing dog for three days before finding it.", "context": "telling a story about a lost pet", "tense": "Past Simple", "grammar_note": "past simple + for + duration + before + gerund"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('look forward to', 'To feel excited and happy about something that is going to happen in the future.', 'nie móc się doczekać; cieszyć się na (coś)', 'both', '{daily,emails}', 'neutral', 'B2', '[{"sentence": "I''m really looking forward to the summer holidays.", "context": "expressing excitement about upcoming time off", "tense": "Present Continuous", "grammar_note": "inseparable three-word phrasal verb + noun"}, {"sentence": "We look forward to hearing from you soon.", "context": "closing line in a formal email", "tense": "Present Simple", "grammar_note": "formal use + gerund (look forward to + -ing)"}, {"sentence": "She had been looking forward to the concert for months before it was cancelled.", "context": "expressing disappointment about a cancelled event", "tense": "Past Perfect Continuous", "grammar_note": "past perfect continuous emphasising duration before a past event"}, {"sentence": "Are you looking forward to starting your new job next week?", "context": "asking a friend about an upcoming career change", "tense": "Present Continuous", "grammar_note": "yes/no question + gerund as object of the preposition to"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('look up', 'To search for information in a reference source such as a dictionary, book, or the internet.', 'sprawdzić; wyszukać (w słowniku, internecie)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "I looked up the word in the dictionary because I didn''t know the meaning.", "context": "studying vocabulary while reading a book", "tense": "Past Simple", "grammar_note": "transitive separable — object after particle + in + source"}, {"sentence": "You can look it up online if you''re not sure about the answer.", "context": "suggesting someone research a fact", "tense": "Present Simple", "grammar_note": "modal can + pronoun between verb and particle"}, {"sentence": "She has been looking up flights to Barcelona all evening.", "context": "planning a trip by browsing the internet", "tense": "Present Perfect Continuous", "grammar_note": "continuous form + object after particle"}, {"sentence": "Things are finally looking up after a really difficult year.", "context": "expressing optimism about an improving situation", "tense": "Present Continuous", "grammar_note": "intransitive — figurative meaning of improving"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('make out', 'To manage to see, hear, or understand something with difficulty. Also, to claim or pretend something is the case.', 'dostrzec; rozeznać; zrozumieć (z trudem)', 'general', '{daily}', 'informal', 'C1', '[{"sentence": "I couldn''t make out what he was saying because of the noise.", "context": "struggling to hear someone in a loud environment", "tense": "Past Simple", "grammar_note": "could not + base form + wh-clause"}, {"sentence": "She is trying to make out the small text on the medicine bottle.", "context": "struggling to read fine print", "tense": "Present Continuous", "grammar_note": "trying to + base form + direct object"}, {"sentence": "He made himself out to be an expert, but he knew very little.", "context": "describing someone who exaggerated their abilities", "tense": "Past Simple", "grammar_note": "reflexive + out + to be (make oneself out to be something)"}, {"sentence": "Can you make out that sign in the distance?", "context": "driving and trying to read a road sign from far away", "tense": "Present Simple", "grammar_note": "modal can + transitive with object after particle"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('mix up', 'To confuse two or more things or people with each other. Also, to put things in the wrong order.', 'pomylić; pomieszać; pokręcić', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "I always mix up their names because they look so alike.", "context": "confusing identical twins", "tense": "Present Simple", "grammar_note": "transitive separable — object after particle"}, {"sentence": "The documents got mixed up during the move to the new office.", "context": "explaining disorganised paperwork after relocation", "tense": "Past Simple", "grammar_note": "passive-like structure with get + past participle"}, {"sentence": "She had mixed up the dates and arrived a day early for the appointment.", "context": "describing an embarrassing scheduling mistake", "tense": "Past Perfect", "grammar_note": "past perfect — action before another past event"}, {"sentence": "Be careful not to mix up the salt and the sugar when you''re baking.", "context": "giving cooking advice to a beginner", "tense": "Imperative", "grammar_note": "be careful not to + base form — warning"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('move in', 'To start living in a new home or to begin occupying a new space.', 'wprowadzić się; zamieszkać', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "They moved in together after dating for two years.", "context": "a couple starting to share a home", "tense": "Past Simple", "grammar_note": "intransitive + together — adverb of manner"}, {"sentence": "We are moving in next Friday, so there''s a lot to organise.", "context": "preparing for a house move", "tense": "Present Continuous", "grammar_note": "present continuous for planned future event"}, {"sentence": "She has already moved in and started decorating her new flat.", "context": "updating friends about a recent relocation", "tense": "Present Perfect", "grammar_note": "present perfect with already + coordinated clause"}, {"sentence": "Once we move in, we''ll need to set up the internet immediately.", "context": "planning practical steps for a new home", "tense": "Future Simple", "grammar_note": "time clause with once + present simple, main clause with will"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('move out', 'To leave a home or place where you have been living and go somewhere else.', 'wyprowadzić się', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "He moved out of his parents'' house when he turned eighteen.", "context": "describing a young person becoming independent", "tense": "Past Simple", "grammar_note": "intransitive + out of + place"}, {"sentence": "She is moving out at the end of the month because the rent is too high.", "context": "explaining a decision to leave a rental property", "tense": "Present Continuous", "grammar_note": "present continuous for planned future event + because clause"}, {"sentence": "If the neighbours don''t stop making noise, I''ll move out.", "context": "threatening to leave due to noise problems", "tense": "First Conditional", "grammar_note": "first conditional — if + present simple, will + base form"}, {"sentence": "By the time the new tenants arrive, we will have moved out completely.", "context": "planning the transition between tenants in a flat", "tense": "Future Perfect", "grammar_note": "future perfect — will have + past participle with by-clause"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pass away', 'To die. This is a polite, indirect way of saying that someone has died.', 'odejść; umrzeć (eufemizm)', 'general', '{daily}', 'formal', 'B2', '[{"sentence": "Her grandfather passed away peacefully in his sleep last night.", "context": "sharing sad news about a family member''s death", "tense": "Past Simple", "grammar_note": "intransitive + adverb of manner"}, {"sentence": "It has been five years since he passed away, and we still miss him.", "context": "remembering a loved one on an anniversary", "tense": "Present Perfect", "grammar_note": "it has been + time + since + past simple"}, {"sentence": "When her mother passed away, the whole community came together to support her.", "context": "describing community solidarity during grief", "tense": "Past Simple", "grammar_note": "when-clause + past simple in both clauses"}, {"sentence": "Many traditions are passing away as younger generations adopt new customs.", "context": "discussing cultural change in a sociological context", "tense": "Present Continuous", "grammar_note": "figurative meaning — traditions disappearing over time"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pass out', 'To lose consciousness or faint. Also, to distribute items to a group of people.', 'zemdleć; stracić przytomność; rozdawać', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "He passed out from the heat and had to be taken to hospital.", "context": "describing a medical incident on a hot day", "tense": "Past Simple", "grammar_note": "intransitive + from + cause"}, {"sentence": "The teacher is passing out the exam papers to the students.", "context": "distributing tests at the beginning of an exam", "tense": "Present Continuous", "grammar_note": "transitive — object after particle + to + recipient"}, {"sentence": "If you don''t drink enough water, you might pass out during the marathon.", "context": "warning a runner about dehydration", "tense": "First Conditional", "grammar_note": "first conditional with might instead of will for possibility"}, {"sentence": "She had passed out on the sofa after working a double shift.", "context": "finding someone asleep from exhaustion", "tense": "Past Perfect", "grammar_note": "past perfect — figurative meaning of falling into deep sleep"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pay back', 'To return money that you owe to someone. Also, to take revenge on someone for something they did.', 'oddać (pieniądze); spłacić; odpłacić się (zemsta)', 'both', '{daily,finance}', 'neutral', 'B2', '[{"sentence": "I''ll pay you back as soon as I get my salary.", "context": "promising to return borrowed money to a friend", "tense": "Future Simple", "grammar_note": "transitive separable — pronoun between verb and particle"}, {"sentence": "She paid back the entire loan within two years.", "context": "discussing someone''s financial responsibility", "tense": "Past Simple", "grammar_note": "transitive — object after particle + within + time frame"}, {"sentence": "The money must be paid back by the end of the month.", "context": "formal loan repayment conditions", "tense": "Present Simple", "grammar_note": "passive voice with modal — must be + past participle"}, {"sentence": "He has been paying back his student debt for over ten years.", "context": "discussing the burden of educational loans", "tense": "Present Perfect Continuous", "grammar_note": "continuous form emphasising duration of ongoing repayment"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pick out', 'To choose or select something from a group or collection.', 'wybrać; wyselekcjonować', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She picked out a beautiful dress for the wedding.", "context": "shopping for a special occasion outfit", "tense": "Past Simple", "grammar_note": "transitive separable — object after particle"}, {"sentence": "Can you help me pick out a birthday gift for my sister?", "context": "asking for help choosing a present", "tense": "Present Simple", "grammar_note": "help + object + base form + phrasal verb"}, {"sentence": "The winners will be picked out from the entries by a panel of judges.", "context": "explaining the selection process for a competition", "tense": "Future Simple", "grammar_note": "passive voice — will be + past participle + from"}, {"sentence": "He had already picked out the restaurant before I even suggested going out.", "context": "describing someone who planned ahead", "tense": "Past Perfect", "grammar_note": "past perfect with already — action completed before another past event"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('plug in', 'To connect an electrical device to a power supply by inserting a plug into a socket.', 'podłączyć (do prądu); włożyć wtyczkę', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Don''t forget to plug in your phone before you go to bed.", "context": "reminding someone to charge their device", "tense": "Imperative", "grammar_note": "negative imperative with don''t forget to + base form"}, {"sentence": "She plugged in the laptop and started working immediately.", "context": "setting up a workspace at a cafe", "tense": "Past Simple", "grammar_note": "transitive — object after particle + coordinated clause"}, {"sentence": "The speaker isn''t working because it hasn''t been plugged in.", "context": "troubleshooting audio equipment before a presentation", "tense": "Present Perfect", "grammar_note": "passive voice — hasn''t been + past participle"}, {"sentence": "Once you plug it in, the device will automatically start updating.", "context": "explaining how to set up a new gadget", "tense": "Future Simple", "grammar_note": "time clause with once + present simple, will + base form"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pop up', 'To appear suddenly or unexpectedly. Also used for windows or messages that appear on a screen.', 'pojawić się (nagle/niespodziewanie); wyskoczyć', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "A strange error message popped up on my screen while I was working.", "context": "describing a computer problem", "tense": "Past Simple", "grammar_note": "intransitive + on + location"}, {"sentence": "New coffee shops keep popping up all over the neighbourhood.", "context": "commenting on changes in a local area", "tense": "Present Simple", "grammar_note": "keep + gerund for repeated ongoing action"}, {"sentence": "He has a habit of popping up when you least expect it.", "context": "describing someone who arrives unannounced", "tense": "Present Simple", "grammar_note": "have a habit of + gerund"}, {"sentence": "An opportunity like this won''t just pop up again anytime soon.", "context": "urging someone to seize an opportunity", "tense": "Future Simple", "grammar_note": "negative future with won''t + just for emphasis"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pull out', 'To remove something from inside a place or container. Also, to withdraw from an activity, agreement, or commitment.', 'wyciągnąć; wycofać się (z czegoś)', 'both', '{daily,negotiations}', 'neutral', 'B2', '[{"sentence": "He pulled out his wallet and paid for everyone''s dinner.", "context": "a generous gesture at a restaurant", "tense": "Past Simple", "grammar_note": "transitive separable — object after particle"}, {"sentence": "The company has pulled out of the deal due to financial concerns.", "context": "business news about a cancelled agreement", "tense": "Present Perfect", "grammar_note": "intransitive + out of (withdraw from something)"}, {"sentence": "If the main investor pulls out, the entire project will collapse.", "context": "discussing risks in a business meeting", "tense": "First Conditional", "grammar_note": "first conditional — if + present simple, will + base form"}, {"sentence": "She was pulling out of the driveway when she noticed the flat tyre.", "context": "describing a driving situation", "tense": "Past Continuous", "grammar_note": "past continuous for background action + when clause — literal driving meaning"}]');
