-- ============================================
-- Import phrasal verbs: ID 1-50 (50 wpisów)
-- Wklej ten SQL w Supabase SQL Editor i kliknij Run
-- ============================================

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('bring up', 'To mention or introduce a topic in a conversation or meeting.', 'poruszyć temat, wspomnieć o czymś', 'business', '{meetings,emails}', 'neutral', 'B2', '[{"sentence": "She brought up an important issue during the meeting.", "context": "business meeting", "tense": "Past Simple", "grammar_note": "brought up + noun"}, {"sentence": "I will bring up your suggestion with the board tomorrow.", "context": "corporate communication", "tense": "Future Simple", "grammar_note": "will bring up + noun + with someone"}, {"sentence": "This topic has been brought up several times already.", "context": "recurring discussion", "tense": "Present Perfect Passive", "grammar_note": "has been brought up (passive voice)"}, {"sentence": "If anyone brings up the budget, let me handle it.", "context": "strategy planning", "tense": "Present Simple (conditional)", "grammar_note": "if + brings up (third person)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('carry out', 'To perform or complete a task, plan, or instruction.', 'przeprowadzić, wykonać, zrealizować', 'business', '{meetings,daily}', 'formal', 'B2', '[{"sentence": "The team carried out a thorough market analysis last quarter.", "context": "project management", "tense": "Past Simple", "grammar_note": "carried out + noun"}, {"sentence": "We have carried out all the necessary safety inspections.", "context": "compliance review", "tense": "Present Perfect", "grammar_note": "have carried out + noun"}, {"sentence": "The audit is being carried out by an external firm.", "context": "financial audit", "tense": "Present Continuous Passive", "grammar_note": "is being carried out (passive voice)"}, {"sentence": "Carrying out this plan will require additional funding.", "context": "budget meeting", "tense": "Gerund", "grammar_note": "carrying out (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('come up with', 'To think of or produce an idea, plan, or solution.', 'wymyślić, wpaść na pomysł', 'business', '{meetings,presentations}', 'neutral', 'B2', '[{"sentence": "The marketing team came up with a brilliant campaign idea.", "context": "creative brainstorming", "tense": "Past Simple", "grammar_note": "came up with + noun"}, {"sentence": "We need to come up with a solution before the deadline.", "context": "project crisis", "tense": "Infinitive (need to)", "grammar_note": "need to come up with + noun"}, {"sentence": "She has come up with three viable proposals so far.", "context": "strategy meeting", "tense": "Present Perfect", "grammar_note": "has come up with + noun"}, {"sentence": "They were coming up with ideas when the client called.", "context": "team collaboration", "tense": "Past Continuous", "grammar_note": "were coming up with (past continuous)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('deal with', 'To handle, manage, or take action regarding a situation or problem.', 'radzić sobie z czymś, zajmować się czymś', 'business', '{daily,meetings,emails}', 'neutral', 'B2', '[{"sentence": "The manager dealt with the complaint immediately.", "context": "customer service", "tense": "Past Simple", "grammar_note": "dealt with + noun"}, {"sentence": "We are currently dealing with a supply chain disruption.", "context": "operations management", "tense": "Present Continuous", "grammar_note": "are dealing with + noun"}, {"sentence": "This issue must be dealt with before the product launch.", "context": "product development", "tense": "Modal Passive", "grammar_note": "must be dealt with (modal + passive)"}, {"sentence": "Having dealt with similar cases before, she knew what to do.", "context": "HR dispute resolution", "tense": "Perfect Participle", "grammar_note": "having dealt with (perfect participle)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('draw up', 'To prepare or create a formal document, plan, or agreement.', 'sporządzić, opracować (dokument, plan, umowę)', 'business', '{negotiations,finance}', 'formal', 'B2', '[{"sentence": "The legal team drew up a new contract for the partnership.", "context": "contract negotiation", "tense": "Past Simple", "grammar_note": "drew up + noun"}, {"sentence": "We will draw up a detailed project plan by Friday.", "context": "project planning", "tense": "Future Simple", "grammar_note": "will draw up + noun + by (deadline)"}, {"sentence": "The agreement has already been drawn up and is ready for signing.", "context": "deal closing", "tense": "Present Perfect Passive", "grammar_note": "has been drawn up (passive voice)"}, {"sentence": "She is drawing up a list of potential investors.", "context": "fundraising", "tense": "Present Continuous", "grammar_note": "is drawing up + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('figure out', 'To understand or solve something after thinking about it.', 'rozgryźć, dowiedzieć się, znaleźć rozwiązanie', 'both', '{daily,meetings}', 'informal', 'B2', '[{"sentence": "We finally figured out why sales dropped last month.", "context": "sales analysis", "tense": "Past Simple", "grammar_note": "figured out + why-clause"}, {"sentence": "I have been trying to figure out the discrepancy in the report.", "context": "financial reporting", "tense": "Present Perfect Continuous", "grammar_note": "have been trying to figure out + noun"}, {"sentence": "Let''s figure out the best approach before the meeting.", "context": "team preparation", "tense": "Imperative", "grammar_note": "let''s figure out + noun"}, {"sentence": "Once we figure out the root cause, we can fix the process.", "context": "quality improvement", "tense": "Present Simple (conditional)", "grammar_note": "once + figure out (time clause)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('fill in', 'To complete a form or document by adding required information, or to inform someone about something they missed.', 'wypełnić (formularz), uzupełnić kogoś o szczegóły', 'business', '{hr,emails,daily}', 'neutral', 'B2', '[{"sentence": "Please fill in the expense report before the end of the day.", "context": "finance administration", "tense": "Imperative", "grammar_note": "fill in + noun (imperative)"}, {"sentence": "She filled me in on what happened at the board meeting.", "context": "colleague update", "tense": "Past Simple", "grammar_note": "filled someone in on + noun"}, {"sentence": "All forms must be filled in completely before submission.", "context": "HR onboarding", "tense": "Modal Passive", "grammar_note": "must be filled in (modal + passive)"}, {"sentence": "I will fill you in on the details after lunch.", "context": "informal office chat", "tense": "Future Simple", "grammar_note": "will fill someone in on + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('follow up', 'To take further action or make additional contact after an initial meeting, email, or event.', 'kontynuować sprawę, podjąć dalsze działania, upomnieć się', 'business', '{emails,negotiations,daily}', 'neutral', 'B2', '[{"sentence": "I followed up with the client regarding the proposal.", "context": "sales process", "tense": "Past Simple", "grammar_note": "followed up with + person + regarding + topic"}, {"sentence": "Could you follow up on the invoice that hasn''t been paid?", "context": "accounts receivable", "tense": "Modal (request)", "grammar_note": "could you follow up on + noun"}, {"sentence": "She has been following up with leads all week.", "context": "business development", "tense": "Present Perfect Continuous", "grammar_note": "has been following up with + noun"}, {"sentence": "Following up promptly shows professionalism and reliability.", "context": "professional development advice", "tense": "Gerund", "grammar_note": "following up (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get back to', 'To respond to someone at a later time, or to return to a previous topic or activity.', 'odezwać się do kogoś, wrócić do tematu', 'business', '{emails,meetings,daily}', 'neutral', 'B2', '[{"sentence": "I''ll get back to you with the figures by tomorrow morning.", "context": "email correspondence", "tense": "Future Simple", "grammar_note": "will get back to + person + with + noun"}, {"sentence": "He never got back to us about the contract changes.", "context": "negotiation follow-up", "tense": "Past Simple", "grammar_note": "got back to + person + about + noun"}, {"sentence": "Let''s get back to the main agenda item.", "context": "business meeting", "tense": "Imperative", "grammar_note": "let''s get back to + noun"}, {"sentence": "She is getting back to all the applicants this week.", "context": "recruitment process", "tense": "Present Continuous", "grammar_note": "is getting back to + person"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go over', 'To review, examine, or discuss something carefully.', 'przejrzeć, omówić, przeanalizować', 'business', '{meetings,presentations,finance}', 'neutral', 'B2', '[{"sentence": "Let''s go over the quarterly results one more time.", "context": "financial review meeting", "tense": "Imperative", "grammar_note": "let''s go over + noun"}, {"sentence": "We went over every detail of the proposal before submitting it.", "context": "proposal preparation", "tense": "Past Simple", "grammar_note": "went over + noun"}, {"sentence": "The report has been gone over by three different managers.", "context": "quality assurance", "tense": "Present Perfect Passive", "grammar_note": "has been gone over (passive voice)"}, {"sentence": "She was going over the presentation slides when the power went out.", "context": "presentation rehearsal", "tense": "Past Continuous", "grammar_note": "was going over (past continuous)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go through', 'To examine or review something in detail, or to experience a process or difficult situation.', 'przejrzeć dokładnie, przejść przez coś', 'business', '{meetings,hr,daily}', 'neutral', 'B2', '[{"sentence": "We went through all the applications and shortlisted five candidates.", "context": "recruitment process", "tense": "Past Simple", "grammar_note": "went through + noun"}, {"sentence": "The company is going through a major restructuring.", "context": "organizational change", "tense": "Present Continuous", "grammar_note": "is going through + noun"}, {"sentence": "I need to go through the contract before signing it.", "context": "contract review", "tense": "Infinitive (need to)", "grammar_note": "need to go through + noun"}, {"sentence": "Having gone through the data, the analyst presented her findings.", "context": "data analysis presentation", "tense": "Perfect Participle", "grammar_note": "having gone through (perfect participle)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hand over', 'To give responsibility, control, or possession of something to another person.', 'przekazać, oddać (obowiązki, kontrolę)', 'business', '{hr,meetings,daily}', 'neutral', 'B2', '[{"sentence": "She handed over all her projects before leaving the company.", "context": "employee departure", "tense": "Past Simple", "grammar_note": "handed over + noun"}, {"sentence": "The CEO will hand over leadership to his successor next month.", "context": "leadership transition", "tense": "Future Simple", "grammar_note": "will hand over + noun + to + person"}, {"sentence": "All confidential files must be handed over to the compliance team.", "context": "regulatory compliance", "tense": "Modal Passive", "grammar_note": "must be handed over to (modal + passive)"}, {"sentence": "Handing over responsibilities properly ensures a smooth transition.", "context": "management best practices", "tense": "Gerund", "grammar_note": "handing over (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hold off', 'To delay or postpone an action or decision.', 'wstrzymać się, odłożyć na później', 'business', '{negotiations,meetings,finance}', 'neutral', 'B2', '[{"sentence": "We held off on the investment until market conditions improved.", "context": "investment decision", "tense": "Past Simple", "grammar_note": "held off on + noun + until"}, {"sentence": "Let''s hold off on making a decision until we have more data.", "context": "strategy meeting", "tense": "Imperative", "grammar_note": "let''s hold off on + gerund"}, {"sentence": "They have been holding off on hiring due to budget constraints.", "context": "HR planning", "tense": "Present Perfect Continuous", "grammar_note": "have been holding off on + gerund"}, {"sentence": "If we hold off any longer, we might lose the opportunity.", "context": "deal negotiation", "tense": "Present Simple (conditional)", "grammar_note": "if + hold off (first conditional)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('keep up with', 'To stay informed about or maintain the same pace as something that is changing or developing.', 'nadążać za czymś, być na bieżąco', 'business', '{daily,meetings}', 'neutral', 'B2', '[{"sentence": "It''s hard to keep up with all the regulatory changes in our industry.", "context": "compliance discussion", "tense": "Infinitive", "grammar_note": "to keep up with + noun"}, {"sentence": "Our competitors have kept up with the latest technology trends.", "context": "market analysis", "tense": "Present Perfect", "grammar_note": "have kept up with + noun"}, {"sentence": "She was struggling to keep up with the increasing workload.", "context": "performance review", "tense": "Past Continuous", "grammar_note": "was struggling to keep up with + noun"}, {"sentence": "Keeping up with industry news is essential for every manager.", "context": "professional development", "tense": "Gerund", "grammar_note": "keeping up with (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('lay off', 'To dismiss employees from their jobs, usually because there is not enough work or money.', 'zwolnić (pracowników), przeprowadzić redukcję etatów', 'business', '{hr,finance}', 'formal', 'B2', '[{"sentence": "The company laid off 200 employees during the recession.", "context": "economic downturn", "tense": "Past Simple", "grammar_note": "laid off + number + noun"}, {"sentence": "Several staff members are being laid off due to automation.", "context": "technology-driven restructuring", "tense": "Present Continuous Passive", "grammar_note": "are being laid off (passive voice)"}, {"sentence": "If revenue doesn''t improve, we may have to lay off more people.", "context": "financial planning meeting", "tense": "Modal (conditional)", "grammar_note": "may have to lay off (modal + infinitive)"}, {"sentence": "Having been laid off twice, he decided to start his own business.", "context": "entrepreneurship motivation", "tense": "Perfect Participle Passive", "grammar_note": "having been laid off (perfect participle passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('look into', 'To investigate or examine something to find out more information.', 'zbadać, przyjrzeć się czemuś, sprawdzić', 'business', '{meetings,emails,daily}', 'neutral', 'B2', '[{"sentence": "We are looking into the cause of the system failure.", "context": "IT incident response", "tense": "Present Continuous", "grammar_note": "are looking into + noun"}, {"sentence": "The auditors looked into the financial discrepancies last week.", "context": "financial audit", "tense": "Past Simple", "grammar_note": "looked into + noun"}, {"sentence": "I will look into this matter and report back by Friday.", "context": "email response to a complaint", "tense": "Future Simple", "grammar_note": "will look into + noun"}, {"sentence": "This issue should have been looked into much sooner.", "context": "management criticism", "tense": "Modal Perfect Passive", "grammar_note": "should have been looked into (modal perfect passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pass on', 'To transfer information, a message, or a task to someone else.', 'przekazać (informację, wiadomość), przesłać dalej', 'business', '{emails,meetings,daily}', 'neutral', 'B2', '[{"sentence": "Could you pass on this message to the finance department?", "context": "office communication", "tense": "Modal (request)", "grammar_note": "could you pass on + noun + to + person"}, {"sentence": "He passed on the client''s feedback to the design team.", "context": "project coordination", "tense": "Past Simple", "grammar_note": "passed on + noun + to + person"}, {"sentence": "The information has been passed on to all relevant departments.", "context": "internal communication", "tense": "Present Perfect Passive", "grammar_note": "has been passed on to (passive voice)"}, {"sentence": "I''m passing on the lead to our sales team since it''s their territory.", "context": "sales handoff", "tense": "Present Continuous", "grammar_note": "am passing on + noun + to + person"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('phase out', 'To gradually stop using, producing, or providing something over a period of time.', 'stopniowo wycofywać, wygaszać', 'business', '{finance,meetings,presentations}', 'formal', 'C1', '[{"sentence": "The company is phasing out its legacy software systems.", "context": "digital transformation", "tense": "Present Continuous", "grammar_note": "is phasing out + noun"}, {"sentence": "They phased out the old product line to make room for new offerings.", "context": "product portfolio management", "tense": "Past Simple", "grammar_note": "phased out + noun + to (purpose)"}, {"sentence": "The outdated policy will be phased out over the next six months.", "context": "organizational policy update", "tense": "Future Simple Passive", "grammar_note": "will be phased out (passive voice)"}, {"sentence": "Phasing out paper-based processes has saved us thousands of euros.", "context": "efficiency report", "tense": "Gerund (Perfect)", "grammar_note": "phasing out (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('point out', 'To draw attention to a fact, mistake, or important detail.', 'zwrócić uwagę na coś, wskazać', 'business', '{meetings,presentations,emails}', 'neutral', 'B2', '[{"sentence": "The consultant pointed out several weaknesses in our strategy.", "context": "strategy review", "tense": "Past Simple", "grammar_note": "pointed out + noun"}, {"sentence": "I''d like to point out that we are over budget this quarter.", "context": "budget meeting", "tense": "Modal (would like to)", "grammar_note": "would like to point out + that-clause"}, {"sentence": "It has been pointed out by several team members that the deadline is unrealistic.", "context": "project planning discussion", "tense": "Present Perfect Passive", "grammar_note": "has been pointed out (passive voice)"}, {"sentence": "She keeps pointing out errors in the financial reports.", "context": "quality control", "tense": "Present Simple (habitual)", "grammar_note": "keeps pointing out + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('put forward', 'To propose or suggest an idea, plan, or candidate for consideration.', 'wysunąć (propozycję), zaproponować, przedstawić', 'business', '{meetings,negotiations,presentations}', 'formal', 'C1', '[{"sentence": "She put forward a compelling argument for expanding into new markets.", "context": "board meeting", "tense": "Past Simple", "grammar_note": "put forward + noun + for + gerund"}, {"sentence": "Several proposals have been put forward by the strategy team.", "context": "strategic planning", "tense": "Present Perfect Passive", "grammar_note": "have been put forward (passive voice)"}, {"sentence": "We will put forward our recommendations at the next meeting.", "context": "consulting engagement", "tense": "Future Simple", "grammar_note": "will put forward + noun"}, {"sentence": "Putting forward innovative ideas is encouraged in our company culture.", "context": "employee engagement", "tense": "Gerund", "grammar_note": "putting forward (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('put off', 'To postpone or delay something to a later time.', 'odłożyć, przełożyć na później', 'both', '{meetings,daily}', 'neutral', 'B2', '[{"sentence": "They put off the product launch until the software bugs were fixed.", "context": "product management", "tense": "Past Simple", "grammar_note": "put off + noun + until"}, {"sentence": "We can''t keep putting off this decision forever.", "context": "management discussion", "tense": "Present Simple (habitual)", "grammar_note": "can''t keep putting off + noun"}, {"sentence": "The meeting has been put off until next Wednesday.", "context": "scheduling change", "tense": "Present Perfect Passive", "grammar_note": "has been put off (passive voice)"}, {"sentence": "If we put off the negotiation, we risk losing the deal.", "context": "deal negotiation", "tense": "Present Simple (conditional)", "grammar_note": "if + put off (first conditional)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('reach out', 'To make contact or communicate with someone, especially to offer help or establish a connection.', 'skontaktować się, nawiązać kontakt', 'business', '{emails,negotiations,daily}', 'neutral', 'B2', '[{"sentence": "We reached out to several potential partners last month.", "context": "business development", "tense": "Past Simple", "grammar_note": "reached out to + person"}, {"sentence": "I will reach out to the supplier to negotiate better terms.", "context": "procurement", "tense": "Future Simple", "grammar_note": "will reach out to + person + to (purpose)"}, {"sentence": "The HR department has been reaching out to candidates all week.", "context": "recruitment", "tense": "Present Perfect Continuous", "grammar_note": "has been reaching out to + person"}, {"sentence": "Don''t hesitate to reach out if you have any questions.", "context": "client email", "tense": "Imperative (negative)", "grammar_note": "don''t hesitate to reach out"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('roll out', 'To officially launch or introduce a new product, service, or plan.', 'wdrożyć, wprowadzić (na rynek), uruchomić', 'business', '{presentations,meetings,daily}', 'neutral', 'C1', '[{"sentence": "The company rolled out its new CRM system across all departments.", "context": "technology implementation", "tense": "Past Simple", "grammar_note": "rolled out + noun + across + noun"}, {"sentence": "We are rolling out the updated branding strategy next quarter.", "context": "marketing campaign", "tense": "Present Continuous", "grammar_note": "are rolling out + noun"}, {"sentence": "The new policy will be rolled out in phases to minimize disruption.", "context": "change management", "tense": "Future Simple Passive", "grammar_note": "will be rolled out (passive voice)"}, {"sentence": "Rolling out a product globally requires careful market research.", "context": "international expansion", "tense": "Gerund", "grammar_note": "rolling out (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('run into', 'To encounter an unexpected problem, difficulty, or person.', 'natknąć się na (problem), napotkać', 'both', '{daily,meetings}', 'informal', 'B2', '[{"sentence": "We ran into some unexpected technical issues during the migration.", "context": "IT project", "tense": "Past Simple", "grammar_note": "ran into + noun"}, {"sentence": "If you run into any problems, contact the support team immediately.", "context": "onboarding instructions", "tense": "Present Simple (conditional)", "grammar_note": "if + run into + noun (conditional)"}, {"sentence": "The project has run into delays because of supply shortages.", "context": "project status update", "tense": "Present Perfect", "grammar_note": "has run into + noun"}, {"sentence": "They were running into compliance issues when the regulations changed.", "context": "regulatory environment", "tense": "Past Continuous", "grammar_note": "were running into + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('set up', 'To establish, arrange, or organize something such as a meeting, system, or business.', 'założyć, zorganizować, skonfigurować', 'business', '{meetings,daily,hr}', 'neutral', 'B2', '[{"sentence": "She set up a meeting with the stakeholders for next Tuesday.", "context": "scheduling", "tense": "Past Simple", "grammar_note": "set up + noun + with + person"}, {"sentence": "We have set up a dedicated team to handle the new account.", "context": "client management", "tense": "Present Perfect", "grammar_note": "have set up + noun + to (purpose)"}, {"sentence": "The new office is being set up and should be ready by March.", "context": "office relocation", "tense": "Present Continuous Passive", "grammar_note": "is being set up (passive voice)"}, {"sentence": "Could you set up a conference call with the London office?", "context": "international coordination", "tense": "Modal (request)", "grammar_note": "could you set up + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('sort out', 'To resolve a problem or organize something that is confused or untidy.', 'rozwiązać, uporządkować, ogarnąć', 'both', '{daily,meetings,emails}', 'informal', 'B2', '[{"sentence": "We need to sort out the scheduling conflict before the conference.", "context": "event planning", "tense": "Infinitive (need to)", "grammar_note": "need to sort out + noun"}, {"sentence": "The IT department sorted out the server issue within an hour.", "context": "technical support", "tense": "Past Simple", "grammar_note": "sorted out + noun"}, {"sentence": "Once everything has been sorted out, we can proceed with the launch.", "context": "product launch preparation", "tense": "Present Perfect Passive", "grammar_note": "has been sorted out (passive voice)"}, {"sentence": "She is sorting out the paperwork for the new partnership agreement.", "context": "administrative work", "tense": "Present Continuous", "grammar_note": "is sorting out + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('step down', 'To resign from an important position or role, especially voluntarily.', 'ustąpić ze stanowiska, zrezygnować z funkcji', 'business', '{hr,meetings}', 'formal', 'C1', '[{"sentence": "The chairman stepped down after fifteen years of service.", "context": "executive leadership change", "tense": "Past Simple", "grammar_note": "stepped down + after + time"}, {"sentence": "She has decided to step down from her position as CFO.", "context": "corporate announcement", "tense": "Present Perfect", "grammar_note": "has decided to step down from + noun"}, {"sentence": "If he steps down, the board will need to appoint a successor.", "context": "succession planning", "tense": "Present Simple (conditional)", "grammar_note": "if + steps down (first conditional)"}, {"sentence": "Stepping down was the right decision given the circumstances.", "context": "post-resignation reflection", "tense": "Gerund", "grammar_note": "stepping down (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('take on', 'To accept or begin to handle a new responsibility, task, or challenge.', 'podjąć się (zadania), przyjąć (obowiązki), zatrudnić', 'business', '{hr,meetings,daily}', 'neutral', 'B2', '[{"sentence": "She took on the role of project manager after the reorganization.", "context": "organizational restructuring", "tense": "Past Simple", "grammar_note": "took on + noun"}, {"sentence": "We are taking on five new employees to support the expansion.", "context": "recruitment drive", "tense": "Present Continuous", "grammar_note": "are taking on + number + noun"}, {"sentence": "He has taken on too many responsibilities and is feeling overwhelmed.", "context": "workload management", "tense": "Present Perfect", "grammar_note": "has taken on + noun"}, {"sentence": "Before taking on a new client, make sure you have the capacity.", "context": "business advice", "tense": "Imperative with Gerund", "grammar_note": "before taking on (gerund after preposition)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('take over', 'To assume control or responsibility for something from someone else, or to acquire a company.', 'przejąć (kontrolę, firmę, obowiązki)', 'business', '{finance,hr,negotiations}', 'neutral', 'B2', '[{"sentence": "The new director took over the department in January.", "context": "management change", "tense": "Past Simple", "grammar_note": "took over + noun"}, {"sentence": "A larger corporation is taking over our company.", "context": "merger and acquisition", "tense": "Present Continuous", "grammar_note": "is taking over + noun"}, {"sentence": "The subsidiary had been taken over by a foreign investor.", "context": "corporate acquisition", "tense": "Past Perfect Passive", "grammar_note": "had been taken over (passive voice)"}, {"sentence": "Who will take over when the CEO retires?", "context": "succession planning", "tense": "Future Simple (question)", "grammar_note": "will take over (interrogative)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('turn down', 'To reject or refuse an offer, proposal, or request.', 'odrzucić, odmówić', 'business', '{negotiations,hr,emails}', 'neutral', 'B2', '[{"sentence": "She turned down the job offer because the salary was too low.", "context": "job negotiation", "tense": "Past Simple", "grammar_note": "turned down + noun + because"}, {"sentence": "Our proposal has been turned down by the committee.", "context": "proposal submission", "tense": "Present Perfect Passive", "grammar_note": "has been turned down (passive voice)"}, {"sentence": "We might have to turn down the partnership if the terms don''t improve.", "context": "negotiation strategy", "tense": "Modal (might have to)", "grammar_note": "might have to turn down + noun"}, {"sentence": "Turning down a lucrative offer was a bold move.", "context": "business decision analysis", "tense": "Gerund", "grammar_note": "turning down (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('wrap up', 'To finish or complete something, especially a meeting, project, or discussion.', 'zakończyć, podsumować, domknąć', 'business', '{meetings,presentations,daily}', 'neutral', 'B2', '[{"sentence": "Let''s wrap up this meeting so everyone can get back to work.", "context": "end of meeting", "tense": "Imperative", "grammar_note": "let''s wrap up + noun"}, {"sentence": "We wrapped up the project two weeks ahead of schedule.", "context": "project completion", "tense": "Past Simple", "grammar_note": "wrapped up + noun + time expression"}, {"sentence": "The negotiations should be wrapped up by the end of the month.", "context": "deal timeline", "tense": "Modal Passive", "grammar_note": "should be wrapped up (modal + passive)"}, {"sentence": "She is wrapping up her quarterly report right now.", "context": "report preparation", "tense": "Present Continuous", "grammar_note": "is wrapping up + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('write off', 'To cancel a debt or accept a loss as unrecoverable, or to dismiss something as having no value.', 'odpisać (dług, stratę), umorzyć, spisać na straty', 'business', '{finance,meetings}', 'formal', 'C1', '[{"sentence": "The bank wrote off millions in bad loans last year.", "context": "financial loss management", "tense": "Past Simple", "grammar_note": "wrote off + amount + in + noun"}, {"sentence": "The debt has been written off as unrecoverable.", "context": "accounting procedure", "tense": "Present Perfect Passive", "grammar_note": "has been written off as (passive voice)"}, {"sentence": "Don''t write off the project just because of one setback.", "context": "team motivation meeting", "tense": "Imperative (negative)", "grammar_note": "don''t write off + noun"}, {"sentence": "They had written off the investment before the unexpected recovery.", "context": "investment review", "tense": "Past Perfect", "grammar_note": "had written off + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('back out', 'To withdraw from an agreement, commitment, or deal.', 'wycofać się (z umowy, zobowiązania)', 'business', '{negotiations,finance}', 'neutral', 'C1', '[{"sentence": "The investor backed out of the deal at the last minute.", "context": "deal collapse", "tense": "Past Simple", "grammar_note": "backed out of + noun"}, {"sentence": "If they back out now, we will need to find an alternative partner.", "context": "contingency planning", "tense": "Present Simple (conditional)", "grammar_note": "if + back out (first conditional)"}, {"sentence": "The supplier has backed out of the contract without notice.", "context": "supply chain disruption", "tense": "Present Perfect", "grammar_note": "has backed out of + noun"}, {"sentence": "Backing out of a signed agreement can lead to legal consequences.", "context": "legal advisory", "tense": "Gerund", "grammar_note": "backing out of (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('break down', 'To divide something into smaller parts for analysis, or to stop functioning properly.', 'rozbić na części, przeanalizować szczegółowo; zepsuć się, zawieść', 'business', '{meetings,presentations,finance}', 'neutral', 'B2', '[{"sentence": "Let''s break down the budget into individual cost categories.", "context": "budget planning", "tense": "Imperative", "grammar_note": "let''s break down + noun + into + noun"}, {"sentence": "The negotiations broke down after both sides refused to compromise.", "context": "failed negotiation", "tense": "Past Simple", "grammar_note": "broke down (intransitive)"}, {"sentence": "The costs have been broken down in the attached spreadsheet.", "context": "financial reporting", "tense": "Present Perfect Passive", "grammar_note": "have been broken down (passive voice)"}, {"sentence": "She is breaking down the quarterly figures for the board presentation.", "context": "presentation preparation", "tense": "Present Continuous", "grammar_note": "is breaking down + noun + for + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('build up', 'To gradually develop, increase, or strengthen something over time.', 'budować, rozwijać, gromadzić (stopniowo)', 'business', '{finance,daily,presentations}', 'neutral', 'B2', '[{"sentence": "The company has built up a strong reputation over the past decade.", "context": "brand building", "tense": "Present Perfect", "grammar_note": "has built up + noun + over + time"}, {"sentence": "We are building up our client base in the Asian market.", "context": "market expansion", "tense": "Present Continuous", "grammar_note": "are building up + noun"}, {"sentence": "They built up enough reserves to weather the economic downturn.", "context": "financial planning", "tense": "Past Simple", "grammar_note": "built up + noun + to (purpose)"}, {"sentence": "Building up trust with clients takes years of consistent service.", "context": "relationship management", "tense": "Gerund", "grammar_note": "building up (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('call off', 'To cancel a planned event, meeting, or arrangement.', 'odwołać, anulować', 'business', '{meetings,negotiations,daily}', 'neutral', 'B2', '[{"sentence": "The CEO called off the merger after discovering hidden liabilities.", "context": "M&A deal", "tense": "Past Simple", "grammar_note": "called off + noun + after + gerund"}, {"sentence": "The conference has been called off due to the travel restrictions.", "context": "event cancellation", "tense": "Present Perfect Passive", "grammar_note": "has been called off (passive voice)"}, {"sentence": "We may have to call off the launch if testing is not completed.", "context": "product launch risk", "tense": "Modal (may have to)", "grammar_note": "may have to call off + noun"}, {"sentence": "Calling off the partnership was a difficult but necessary decision.", "context": "post-decision review", "tense": "Gerund", "grammar_note": "calling off (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('carry on', 'To continue doing something, especially after an interruption or difficulty.', 'kontynuować, prowadzić dalej', 'both', '{meetings,daily}', 'neutral', 'B2', '[{"sentence": "Despite the setbacks, the team carried on with the project.", "context": "project resilience", "tense": "Past Simple", "grammar_note": "carried on with + noun"}, {"sentence": "We will carry on operating under the current guidelines until further notice.", "context": "corporate policy communication", "tense": "Future Simple", "grammar_note": "will carry on + gerund"}, {"sentence": "Please carry on with the presentation while I take this call.", "context": "meeting interruption", "tense": "Imperative", "grammar_note": "carry on with + noun (imperative)"}, {"sentence": "She has been carrying on the work of her predecessor effectively.", "context": "role transition", "tense": "Present Perfect Continuous", "grammar_note": "has been carrying on + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('close down', 'To permanently shut a business, factory, or operation.', 'zamknąć (firmę, zakład), zlikwidować', 'business', '{finance,hr}', 'formal', 'B2', '[{"sentence": "The factory was closed down because it failed to meet environmental standards.", "context": "regulatory compliance", "tense": "Past Simple Passive", "grammar_note": "was closed down (passive voice)"}, {"sentence": "If profits don''t recover, we will have to close down the branch.", "context": "financial turnaround discussion", "tense": "Future Simple (conditional)", "grammar_note": "will have to close down + noun"}, {"sentence": "The company has closed down three of its regional offices.", "context": "corporate restructuring", "tense": "Present Perfect", "grammar_note": "has closed down + noun"}, {"sentence": "Closing down a business involves many legal and financial steps.", "context": "business dissolution advice", "tense": "Gerund", "grammar_note": "closing down (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('come across', 'To find or encounter something or someone unexpectedly, or to give a particular impression.', 'natknąć się na coś, napotkać; sprawiać wrażenie', 'both', '{daily,meetings,presentations}', 'neutral', 'B2', '[{"sentence": "I came across an interesting article about market trends in Asia.", "context": "research and reading", "tense": "Past Simple", "grammar_note": "came across + noun"}, {"sentence": "She comes across as very confident during client presentations.", "context": "presentation feedback", "tense": "Present Simple", "grammar_note": "comes across as + adjective"}, {"sentence": "We have come across several potential risks in the due diligence process.", "context": "M&A due diligence", "tense": "Present Perfect", "grammar_note": "have come across + noun"}, {"sentence": "If you come across any relevant data, please share it with the team.", "context": "collaborative research", "tense": "Present Simple (conditional)", "grammar_note": "if + come across (conditional + imperative)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('count on', 'To rely on or trust someone or something to do what is expected.', 'liczyć na kogoś/coś, polegać na', 'both', '{meetings,daily,emails}', 'neutral', 'B2', '[{"sentence": "You can always count on her to deliver high-quality work.", "context": "employee recognition", "tense": "Present Simple (modal)", "grammar_note": "can count on + person + to (infinitive)"}, {"sentence": "We counted on the supplier to deliver on time, but they didn''t.", "context": "supply chain management", "tense": "Past Simple", "grammar_note": "counted on + person + to (infinitive)"}, {"sentence": "The team is counting on the funding being approved by the board.", "context": "project funding", "tense": "Present Continuous", "grammar_note": "is counting on + noun + gerund"}, {"sentence": "Having someone you can count on in a negotiation is invaluable.", "context": "team building", "tense": "Gerund clause", "grammar_note": "having someone you can count on (gerund clause)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('cut back', 'To reduce the amount or level of something, especially spending or resources.', 'ograniczyć, zredukować (wydatki, zasoby)', 'business', '{finance,meetings,hr}', 'neutral', 'B2', '[{"sentence": "The company cut back on travel expenses after the quarterly review.", "context": "cost reduction", "tense": "Past Simple", "grammar_note": "cut back on + noun"}, {"sentence": "We have been cutting back on non-essential spending this year.", "context": "annual budget review", "tense": "Present Perfect Continuous", "grammar_note": "have been cutting back on + noun"}, {"sentence": "If we cut back further, it could affect service quality.", "context": "budget meeting", "tense": "Present Simple (conditional)", "grammar_note": "if + cut back (first conditional)"}, {"sentence": "Spending needs to be cut back across all departments.", "context": "executive directive", "tense": "Infinitive Passive", "grammar_note": "needs to be cut back (passive infinitive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('fall through', 'To fail to happen or be completed as planned.', 'nie dojść do skutku, nie wypalić', 'business', '{negotiations,finance,daily}', 'neutral', 'C1', '[{"sentence": "The acquisition deal fell through at the last moment.", "context": "M&A failure", "tense": "Past Simple", "grammar_note": "fell through (intransitive)"}, {"sentence": "Our plans have fallen through due to a lack of investor interest.", "context": "startup funding", "tense": "Present Perfect", "grammar_note": "have fallen through + due to + noun"}, {"sentence": "If the partnership falls through, we need a backup plan.", "context": "risk management meeting", "tense": "Present Simple (conditional)", "grammar_note": "if + falls through (first conditional)"}, {"sentence": "Many promising deals had fallen through before we secured this one.", "context": "deal closing celebration", "tense": "Past Perfect", "grammar_note": "had fallen through (past perfect)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get ahead', 'To make progress or become more successful than others, especially in a career or business.', 'wyprzedzić, odnieść sukces, awansować', 'business', '{hr,daily}', 'neutral', 'B2', '[{"sentence": "To get ahead in this industry, you need to constantly update your skills.", "context": "career advice", "tense": "Infinitive", "grammar_note": "to get ahead + in + noun"}, {"sentence": "She got ahead by networking strategically and delivering results.", "context": "career success story", "tense": "Past Simple", "grammar_note": "got ahead + by + gerund"}, {"sentence": "Companies that embrace innovation are getting ahead of their competitors.", "context": "market analysis", "tense": "Present Continuous", "grammar_note": "are getting ahead of + noun"}, {"sentence": "He has always wanted to get ahead in the corporate world.", "context": "personal ambition", "tense": "Present Perfect", "grammar_note": "has wanted to get ahead (present perfect + infinitive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('give in', 'To stop resisting and agree to something, or to surrender one''s position in a negotiation.', 'ustąpić, poddać się, ugiąć się', 'business', '{negotiations,meetings}', 'neutral', 'B2', '[{"sentence": "After weeks of negotiation, the supplier finally gave in to our demands.", "context": "procurement negotiation", "tense": "Past Simple", "grammar_note": "gave in to + noun"}, {"sentence": "Don''t give in too quickly during salary negotiations.", "context": "HR coaching", "tense": "Imperative (negative)", "grammar_note": "don''t give in (negative imperative)"}, {"sentence": "The union has given in on two of the five key points.", "context": "labor relations", "tense": "Present Perfect", "grammar_note": "has given in on + noun"}, {"sentence": "If we give in on pricing, we''ll lose our profit margin.", "context": "pricing strategy", "tense": "Present Simple (conditional)", "grammar_note": "if + give in on (first conditional)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go ahead', 'To proceed with or begin something, often after receiving permission or approval.', 'kontynuować, przystąpić do czegoś, zaczynać działać', 'business', '{meetings,daily,emails}', 'neutral', 'B2', '[{"sentence": "The board gave us the green light to go ahead with the expansion.", "context": "strategic decision", "tense": "Infinitive", "grammar_note": "to go ahead with + noun"}, {"sentence": "We went ahead with the merger despite some internal opposition.", "context": "M&A execution", "tense": "Past Simple", "grammar_note": "went ahead with + noun + despite + noun"}, {"sentence": "Please go ahead and schedule the client meeting for next week.", "context": "delegation of tasks", "tense": "Imperative", "grammar_note": "go ahead and + verb (imperative)"}, {"sentence": "If the funding is approved, we will go ahead as planned.", "context": "project approval", "tense": "Future Simple (conditional)", "grammar_note": "will go ahead (first conditional)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('lay out', 'To explain or present something clearly and in detail, or to arrange a plan or design.', 'przedstawić, wyłożyć (plan, argumenty), rozplanować', 'business', '{presentations,meetings,negotiations}', 'formal', 'C1', '[{"sentence": "The CEO laid out his vision for the company''s future at the annual meeting.", "context": "corporate keynote", "tense": "Past Simple", "grammar_note": "laid out + noun + for + noun"}, {"sentence": "The strategy has been laid out in the document attached to this email.", "context": "email communication", "tense": "Present Perfect Passive", "grammar_note": "has been laid out (passive voice)"}, {"sentence": "I will lay out the three options and let the committee decide.", "context": "decision-making meeting", "tense": "Future Simple", "grammar_note": "will lay out + noun"}, {"sentence": "Laying out a clear roadmap helps align the entire team.", "context": "project management advice", "tense": "Gerund", "grammar_note": "laying out (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('let down', 'To disappoint someone by failing to meet their expectations or fulfill a commitment.', 'zawieść, rozczarować', 'both', '{daily,meetings,emails}', 'neutral', 'B2', '[{"sentence": "The contractor let us down by missing the delivery deadline.", "context": "vendor management", "tense": "Past Simple", "grammar_note": "let someone down + by + gerund"}, {"sentence": "We have been let down by this supplier too many times.", "context": "supplier review", "tense": "Present Perfect Passive", "grammar_note": "have been let down by (passive voice)"}, {"sentence": "I promise I won''t let the team down on this project.", "context": "team commitment", "tense": "Future Simple (negative)", "grammar_note": "won''t let someone down"}, {"sentence": "Being let down by a partner can seriously damage business relationships.", "context": "partnership management", "tense": "Gerund Passive", "grammar_note": "being let down (passive gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('live up to', 'To meet or fulfill expectations, standards, or promises.', 'sprostać (oczekiwaniom), dorównać, spełnić', 'business', '{daily,meetings,presentations}', 'neutral', 'C1', '[{"sentence": "The product didn''t live up to the marketing team''s promises.", "context": "product review", "tense": "Past Simple (negative)", "grammar_note": "didn''t live up to + noun"}, {"sentence": "We must live up to the high standards our clients expect from us.", "context": "quality commitment meeting", "tense": "Modal (must)", "grammar_note": "must live up to + noun"}, {"sentence": "The new hire has lived up to all our expectations so far.", "context": "performance review", "tense": "Present Perfect", "grammar_note": "has lived up to + noun"}, {"sentence": "Living up to your brand promise is essential for customer loyalty.", "context": "branding strategy", "tense": "Gerund", "grammar_note": "living up to (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('narrow down', 'To reduce the number of options or possibilities to a smaller, more focused set.', 'zawęzić, ograniczyć (wybór, opcje)', 'business', '{meetings,hr,daily}', 'neutral', 'B2', '[{"sentence": "We narrowed down the list of candidates to three finalists.", "context": "recruitment process", "tense": "Past Simple", "grammar_note": "narrowed down + noun + to + number"}, {"sentence": "The options are being narrowed down based on the feasibility study.", "context": "strategic planning", "tense": "Present Continuous Passive", "grammar_note": "are being narrowed down (passive voice)"}, {"sentence": "Once we narrow down the scope, we can start drafting the proposal.", "context": "project scoping", "tense": "Present Simple (time clause)", "grammar_note": "once + narrow down (time clause)"}, {"sentence": "Narrowing down priorities is one of the hardest tasks for any leader.", "context": "leadership discussion", "tense": "Gerund", "grammar_note": "narrowing down (gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pay off', 'To result in success or bring a positive outcome after effort or investment. Also, to finish paying a debt.', 'opłacić się, przynieść efekty; spłacić (dług)', 'business', '{finance,daily,meetings}', 'neutral', 'B2', '[{"sentence": "Our investment in employee training has really paid off.", "context": "ROI analysis", "tense": "Present Perfect", "grammar_note": "has paid off (intransitive)"}, {"sentence": "The company paid off all its debts within five years.", "context": "financial milestone", "tense": "Past Simple", "grammar_note": "paid off + noun + within + time"}, {"sentence": "All the hard work will pay off once we land this contract.", "context": "sales motivation", "tense": "Future Simple", "grammar_note": "will pay off + once (time clause)"}, {"sentence": "Taking calculated risks often pays off in the long run.", "context": "executive coaching session", "tense": "Present Simple (habitual)", "grammar_note": "pays off (third person, habitual)"}]');
