-- ============================================
-- Import phrasal verbs: ID 201-250 (50 wpisów)
-- Wklej ten SQL w Supabase SQL Editor i kliknij Run
-- ============================================

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('jot down', 'To write something quickly.', 'zanotować (szybko)', 'business', '{meetings,notes}', 'informal', 'B2', '[{"sentence": "I''ll just jot down your phone number.", "context": "quick note", "tense": "Future Simple", "grammar_note": "will + jot + down + noun"}, {"sentence": "Did you jot down the key points from the speech?", "context": "lecture review", "tense": "Past Simple", "grammar_note": "jot + down + noun"}, {"sentence": "Let me grab a pen to jot this down.", "context": "phone call", "tense": "Infinitive", "grammar_note": "to + jot + pronoun + down (separable)"}, {"sentence": "She is always jotting down ideas in her notebook.", "context": "creative process", "tense": "Present Continuous", "grammar_note": "jot + noun + down (separable)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('run through', 'To check, practise, or rehearse something quickly.', 'przećwiczyć, przejrzeć (szybko)', 'business', '{presentations,meetings}', 'neutral', 'B2', '[{"sentence": "Let''s run through the presentation one more time.", "context": "rehearsal", "tense": "Imperative", "grammar_note": "run + through + noun"}, {"sentence": "Can we run through the agenda quickly?", "context": "meeting start", "tense": "Modal Question", "grammar_note": "can + run + through + noun"}, {"sentence": "I''ll run through the main points.", "context": "summary", "tense": "Future Simple", "grammar_note": "will + run + through + noun"}, {"sentence": "Running through the checklist is mandatory.", "context": "procedure", "tense": "Gerund", "grammar_note": "running + through + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('stand for', 'To represent or mean (acronyms) OR to tolerate.', 'oznaczać (skrót) / tolerować', 'business', '{general,values}', 'neutral', 'B2', '[{"sentence": "What does CEO stand for?", "context": "definitions", "tense": "Present Simple Question", "grammar_note": "stand + for + noun"}, {"sentence": "Our company stands for integrity and quality.", "context": "brand values", "tense": "Present Simple", "grammar_note": "stand + for + noun"}, {"sentence": "We will not stand for harassment in the workplace.", "context": "policy statement", "tense": "Future Negative", "grammar_note": "will + stand + for + noun"}, {"sentence": "I don''t know what this acronym stands for.", "context": "clarification", "tense": "Present Simple", "grammar_note": "stand + for + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('talk over', 'To discuss a problem or plan.', 'przedyskutować', 'business', '{meetings,discussions}', 'neutral', 'B2', '[{"sentence": "We need to talk over the proposal before deciding.", "context": "decision making", "tense": "Infinitive", "grammar_note": "to + talk + over + noun"}, {"sentence": "They talked it over for hours.", "context": "long meeting", "tense": "Past Simple", "grammar_note": "talked + pronoun + over (separable)"}, {"sentence": "Let''s talk this over lunch.", "context": "informal meeting", "tense": "Imperative", "grammar_note": "talk + pronoun + over (separable)"}, {"sentence": "Talking things over helps clarify the situation.", "context": "collaboration tip", "tense": "Gerund", "grammar_note": "talking + noun + over (gerund) (separable)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('weigh up', 'To compare pros and cons.', 'rozważyć (za i przeciw)', 'business', '{decision making,analysis}', 'neutral', 'C1', '[{"sentence": "We need to weigh up the benefits and risks.", "context": "risk analysis", "tense": "Infinitive", "grammar_note": "to + weigh + up + noun"}, {"sentence": "She weighed up her options before quitting.", "context": "career change", "tense": "Past Simple", "grammar_note": "weighed + up + noun"}, {"sentence": "After weighing everything up, we chose Plan B.", "context": "conclusion", "tense": "Participle clause", "grammar_note": "weighing + noun + up (gerund) (separable)"}, {"sentence": "It''s difficult to weigh up intangible assets.", "context": "valuation", "tense": "Infinitive", "grammar_note": "to + weigh + up + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('account for', 'To explain the reason for something or form a part of a total.', 'stanowić (część), wyjaśnić (przyczynę)', 'business', '{finance,reporting}', 'neutral', 'B2', '[{"sentence": "How do you account for the loss in revenue?", "context": "audit question", "tense": "Present Simple", "grammar_note": "account + for + noun"}, {"sentence": "Sales in Asia account for 30% of our profit.", "context": "financial report", "tense": "Present Simple", "grammar_note": "account + for + noun"}, {"sentence": "They couldn''t account for the missing files.", "context": "investigation", "tense": "Past Modal Negative", "grammar_note": "could + account + for + noun"}, {"sentence": "There are several factors to account for.", "context": "planning", "tense": "Infinitive", "grammar_note": "to + account + for + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('back up', 'To support someone or make a copy of data.', 'poprzeć (kogoś), zrobić kopię zapasową', 'business', '{it,teamwork}', 'neutral', 'B2', '[{"sentence": "Don''t forget to back up your files daily.", "context": "IT policy", "tense": "Imperative", "grammar_note": "to + back + up + noun"}, {"sentence": "My manager backed me up in the meeting.", "context": "support", "tense": "Past Simple", "grammar_note": "backed + pronoun + up (separable)"}, {"sentence": "We need evidence to back up these claims.", "context": "legal / debate", "tense": "Infinitive", "grammar_note": "to + back + up + noun"}, {"sentence": "The traffic was backed up for miles.", "context": "logistics delay", "tense": "Past Passive (adjectival)", "grammar_note": "backed + up (passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('bank on', 'To rely on or count on something happening.', 'liczyć na coś (być pewnym)', 'business', '{planning,finance}', 'neutral', 'C1', '[{"sentence": "We are banking on a sales increase this quarter.", "context": "forecasting", "tense": "Present Continuous", "grammar_note": "be + banking + on + noun"}, {"sentence": "Don''t bank on the loan being approved.", "context": "risk warning", "tense": "Negative Imperative", "grammar_note": "not + bank + on + noun"}, {"sentence": "I wouldn''t bank on it.", "context": "skepticism", "tense": "Conditional", "grammar_note": "would + bank + on + noun"}, {"sentence": "They banked on their competitor failing.", "context": "bad strategy", "tense": "Past Simple", "grammar_note": "banked + on + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('break into', 'To enter a new market or industry successfully.', 'wejść na rynek (z sukcesem)', 'business', '{expansion,marketing}', 'neutral', 'B2', '[{"sentence": "It is difficult to break into the Chinese market.", "context": "international expansion", "tense": "Infinitive", "grammar_note": "to + break + into + noun"}, {"sentence": "They broke into the luxury sector last year.", "context": "market penetration", "tense": "Past Simple", "grammar_note": "broke + into + noun"}, {"sentence": "We are trying to break into a new niche.", "context": "strategy", "tense": "Present Continuous", "grammar_note": "to + break + into + noun"}, {"sentence": "Breaking into this industry requires connections.", "context": "advice", "tense": "Gerund", "grammar_note": "breaking + into + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('bring down', 'To reduce costs or prices.', 'obniżyć (ceny, koszty)', 'business', '{finance,pricing}', 'neutral', 'B2', '[{"sentence": "We aim to bring down production costs.", "context": "manufacturing", "tense": "Infinitive", "grammar_note": "bring + down + noun (gerund)"}, {"sentence": "Competition has brought down prices.", "context": "market analysis", "tense": "Present Perfect", "grammar_note": "has + brought + down + noun"}, {"sentence": "Can you bring down the final offer?", "context": "negotiation", "tense": "Modal Request", "grammar_note": "bring + down + noun (gerund)"}, {"sentence": "The scandal brought down the CEO.", "context": "leadership failure (alt meaning)", "tense": "Past Simple", "grammar_note": "brought + down + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('cash in on', 'To profit from a situation.', 'zarobić na czymś, skorzystać z okazji', 'business', '{finance,strategy}', 'informal', 'C1', '[{"sentence": "The company cashed in on the sudden demand.", "context": "market opportunity", "tense": "Past Simple", "grammar_note": "cashed + in on + noun"}, {"sentence": "We should cash in on our brand popularity.", "context": "branding", "tense": "Modal Advice", "grammar_note": "should + cash + in on + noun"}, {"sentence": "Investors are cashing in on rising tech stocks.", "context": "market trends", "tense": "Present Continuous", "grammar_note": "be + cashing + in on + noun"}, {"sentence": "Don''t miss the chance to cash in.", "context": "investment advice", "tense": "Infinitive", "grammar_note": "to + cash + in on"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('contract out', 'To outsource work to another company.', 'zlecić na zewnątrz (outsourcing)', 'business', '{operations,hr}', 'formal', 'C1', '[{"sentence": "We decided to contract out the cleaning services.", "context": "cost cutting", "tense": "Infinitive", "grammar_note": "to + contract + out + noun"}, {"sentence": "Manufacturing is often contracted out to Asia.", "context": "global supply chain", "tense": "Present Passive", "grammar_note": "contracted + out (passive)"}, {"sentence": "Contracting out this project will save time.", "context": "project mgmt", "tense": "Gerund", "grammar_note": "contracting + out + noun (gerund)"}, {"sentence": "They contract out most of their IT work.", "context": "company structure", "tense": "Present Simple", "grammar_note": "contract + out + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('dip into', 'To use a small amount of savings or resources.', 'sięgnąć do (rezerw, oszczędności)', 'business', '{finance,banking}', 'neutral', 'C1', '[{"sentence": "We had to dip into our reserves.", "context": "cash flow issue", "tense": "Past Simple", "grammar_note": "to + dip + into + noun"}, {"sentence": "avoid dipping into the pension fund.", "context": "financial advice", "tense": "Gerund", "grammar_note": "dip + noun + into (separable)"}, {"sentence": "Sales are down, so we are dipping into savings.", "context": "survival", "tense": "Present Continuous", "grammar_note": "dip + noun + into (separable)"}, {"sentence": "He dipped into his own pocket to pay for it.", "context": "personal expense", "tense": "Past Simple", "grammar_note": "dipped + into + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('do away with', 'To remove or abolish something.', 'zlikwidować, pozbyć się (zwyczaju, przepisu)', 'business', '{policy,change mgmt}', 'neutral', 'C1', '[{"sentence": "We should do away with unnecessary paperwork.", "context": "efficiency", "tense": "Modal Advice", "grammar_note": "should + do + away with + noun"}, {"sentence": "They did away with the old bonus system.", "context": "HR policy", "tense": "Past Simple", "grammar_note": "did + away with + noun"}, {"sentence": "The department was not done away with completely.", "context": "restructuring", "tense": "Past Passive", "grammar_note": "not + done + away with (passive)"}, {"sentence": "Doing away with these rules will boost morale.", "context": "culture", "tense": "Gerund", "grammar_note": "doing + away with + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('drag on', 'To continue for too long.', 'ciągnąć się (w czasie)', 'business', '{meetings,projects}', 'neutral', 'B2', '[{"sentence": "The meeting dragged on for three hours.", "context": "boring meeting", "tense": "Past Simple", "grammar_note": "dragged + on + noun"}, {"sentence": "Don''t let the negotiations drag on.", "context": "advice", "tense": "Negative Imperative", "grammar_note": "drag + on + noun"}, {"sentence": "This project has dragged on long enough.", "context": "frustration", "tense": "Present Perfect", "grammar_note": "has + dragged + on + noun"}, {"sentence": "If the lawsuit drags on, costs will rise.", "context": "legal risk", "tense": "First Conditional", "grammar_note": "drag + on + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('draw on', 'To use experience or resources.', 'czerpać z (doświadczenia, zasobów)', 'business', '{skills,resources}', 'formal', 'C1', '[{"sentence": "I will draw on my experience in marketing.", "context": "interview / pitch", "tense": "Future Simple", "grammar_note": "will + draw + on + noun"}, {"sentence": "The company draws on a global network of experts.", "context": "capability", "tense": "Present Simple", "grammar_note": "draw + on + noun"}, {"sentence": "We can draw on the reserve fund if needed.", "context": "finance", "tense": "Modal Ability", "grammar_note": "can + draw + on + noun"}, {"sentence": "He drew on his savings to start the business.", "context": "startup funding", "tense": "Past Simple", "grammar_note": "drew + on + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('drop in', 'To visit unexpectedly or briefly.', 'wpaść (z wizytą)', 'general', '{social,office}', 'informal', 'B2', '[{"sentence": "Feel free to drop in anytime.", "context": "open door policy", "tense": "Imperative", "grammar_note": "to + drop + in + noun"}, {"sentence": "I''ll drop in on the client while I''m in town.", "context": "relationship building", "tense": "Future Simple", "grammar_note": "will + drop + in + noun"}, {"sentence": "She dropped in to say hello.", "context": "casual visit", "tense": "Past Simple", "grammar_note": "dropped + in + noun"}, {"sentence": "Sales dropped in Q3.", "context": "CAUTION: different meaning (verb + prep)", "tense": "Past Simple", "grammar_note": "dropped + in + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('drop off', 'To deliver someone/something OR to decrease.', 'podrzucić (kogoś/coś), spaść (o sprzedaży)', 'business', '{logistics,sales}', 'neutral', 'B2', '[{"sentence": "Can you drop off these documents at HQ?", "context": "errand", "tense": "Modal Request", "grammar_note": "can + drop + off + noun"}, {"sentence": "Demand dropped off after Christmas.", "context": "sales trend", "tense": "Past Simple", "grammar_note": "dropped + off + noun"}, {"sentence": "I need to drop off a parcel.", "context": "shipping", "tense": "Infinitive", "grammar_note": "to + drop + off + noun"}, {"sentence": "Attendance has dropped off recently.", "context": "participation", "tense": "Present Perfect", "grammar_note": "has + dropped + off + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('face up to', 'To accept and deal with a difficult situation.', 'stawić czoła (prawdzie, problemom)', 'business', '{responsibility,challenges}', 'neutral', 'C1', '[{"sentence": "We must face up to the reality of the market.", "context": "strategic shift", "tense": "Modal Obligation", "grammar_note": "must + face + up to + noun"}, {"sentence": "He finally faced up to his responsibilities.", "context": "maturity", "tense": "Past Simple", "grammar_note": "faced + up to + noun"}, {"sentence": "It''s time to face up to the facts.", "context": "hard truth", "tense": "Infinitive", "grammar_note": "to + face + up to + noun"}, {"sentence": "Companies need to face up to climate change.", "context": "ESG", "tense": "Infinitive", "grammar_note": "to + face + up to + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('fight off', 'To defend against an attack or hostile takeover.', 'odeprzeć (atak, przejęcie)', 'business', '{strategy,competition}', 'neutral', 'B2', '[{"sentence": "They fought off a hostile takeover bid.", "context": "corporate defense", "tense": "Past Simple", "grammar_note": "fought + off + noun"}, {"sentence": "We are fighting off competition from low-cost rivals.", "context": "market struggle", "tense": "Present Continuous", "grammar_note": "be + fighting + off + noun"}, {"sentence": "Fighting off these allegations is our priority.", "context": "PR crisis", "tense": "Gerund", "grammar_note": "fighting + off + noun (gerund)"}, {"sentence": "It was hard to fight off the critics.", "context": "public scrutiny", "tense": "Past Simple (adj construction)", "grammar_note": "to + fight + off + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('focus on', 'To give attention to something.', 'skupić się na', 'general', '{strategy,productivity}', 'neutral', 'B2', '[{"sentence": "We need to focus on our core business.", "context": "strategy meeting", "tense": "Infinitive", "grammar_note": "to + focus + on + noun"}, {"sentence": "She is focusing on improving customer service.", "context": "goal setting", "tense": "Present Continuous", "grammar_note": "be + focusing + on + noun"}, {"sentence": "The report focuses on sustainability.", "context": "document summary", "tense": "Present Simple", "grammar_note": "focus + noun + on (separable)"}, {"sentence": "Let''s keep the focus on sales.", "context": "meeting control", "tense": "Noun usage (related)", "grammar_note": "focus + on + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get down to', 'To start doing something seriously.', 'zabrać się do (pracy, interesów)', 'business', '{meetings,productivity}', 'neutral', 'B2', '[{"sentence": "Let''s get down to business.", "context": "meeting start", "tense": "Imperative", "grammar_note": "get + down to + noun"}, {"sentence": "It''s time to get down to work.", "context": "focus", "tense": "Infinitive", "grammar_note": "to + get + down to + noun"}, {"sentence": "After the break, we got down to the details.", "context": "negotiation", "tense": "Past Simple", "grammar_note": "got + down to + noun"}, {"sentence": "Getting down to the nitty-gritty.", "context": "analysis (idiom)", "tense": "Gerund", "grammar_note": "getting + down to + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go under', 'To go bankrupt.', 'zbankrutować, upaść (o firmie)', 'business', '{finance,bankruptcy}', 'neutral', 'B2', '[{"sentence": "Many businesses went under during the recession.", "context": "economic crisis", "tense": "Past Simple", "grammar_note": "went + under + noun"}, {"sentence": "We are afraid the supplier might go under.", "context": "supply chain risk", "tense": "Modal Possibility", "grammar_note": "might + go + under + noun"}, {"sentence": "Seeing a competitor go under is sobering.", "context": "reflection", "tense": "Infinitive", "grammar_note": "go + under + noun"}, {"sentence": "The firm is in danger of going under.", "context": "financial warning", "tense": "Gerund", "grammar_note": "be + going + under + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hand in', 'To submit an assignment or resignation.', 'złożyć (rezygnację), oddać (pracę)', 'business', '{hr,admin}', 'neutral', 'B2', '[{"sentence": "She handed in her resignation yesterday.", "context": "quitting", "tense": "Past Simple", "grammar_note": "handed + in + noun"}, {"sentence": "Please hand in your reports by Friday.", "context": "deadlines", "tense": "Imperative", "grammar_note": "hand + in + noun"}, {"sentence": "He forgot to hand in the expense claim.", "context": "admin error", "tense": "Infinitive", "grammar_note": "to + hand + in + noun"}, {"sentence": "Handing in notice is a formal process.", "context": "hr procedure", "tense": "Gerund", "grammar_note": "handing + in + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('head up', 'To lead or be in charge of a department/project.', 'kierować (czymś), stać na czele', 'business', '{management,leadership}', 'neutral', 'B2', '[{"sentence": "Who will head up the new division?", "context": "restructuring", "tense": "Future Simple Question", "grammar_note": "will + head + up + noun"}, {"sentence": "She was chosen to head up the project.", "context": "promotion", "tense": "Infinitive", "grammar_note": "to + head + up + noun"}, {"sentence": "He has been heading up sales for 5 years.", "context": "tenure", "tense": "Present Perfect Continuous", "grammar_note": "be + heading + up + noun"}, {"sentence": "Heading up a team requires patience.", "context": "leadership advice", "tense": "Gerund", "grammar_note": "heading + up + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('knuckle down', 'To start working hard.', 'przyłożyć się do pracy, wziąć się do roboty', 'general', '{productivity,focus}', 'informal', 'C1', '[{"sentence": "It''s time to knuckle down and finish this.", "context": "deadline approaching", "tense": "Infinitive", "grammar_note": "to + knuckle + down + noun"}, {"sentence": "They knuckled down after the break.", "context": "work session", "tense": "Past Simple", "grammar_note": "knuckled + down + noun"}, {"sentence": "We need to knuckle down to meet the target.", "context": "team pep talk", "tense": "Infinitive", "grammar_note": "to + knuckle + down + noun"}, {"sentence": "If you knuckle down, you''ll succeed.", "context": "advice", "tense": "First Conditional", "grammar_note": "knuckle + down + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('level with', 'To be honest with someone.', 'być z kimś szczerym', 'general', '{communication,transparency}', 'informal', 'C1', '[{"sentence": "I''ll level with you; the situation is bad.", "context": "bad news", "tense": "Future Simple", "grammar_note": "will + level + with + noun"}, {"sentence": "He didn''t level with us about the risks.", "context": "dishonesty", "tense": "Past Simple Negative", "grammar_note": "not + level + with + noun"}, {"sentence": "Please level with me.", "context": "request for truth", "tense": "Imperative", "grammar_note": "level + with + noun"}, {"sentence": "Leveling with employees builds trust.", "context": "leadership tip", "tense": "Gerund", "grammar_note": "leveling + with + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('note down', 'To write something to remember it.', 'zapisać, zanotować', 'business', '{meetings,admin}', 'neutral', 'B2', '[{"sentence": "Please note down the reference number.", "context": "call center", "tense": "Imperative", "grammar_note": "note + down + noun"}, {"sentence": "I noted down the main points.", "context": "minute taking", "tense": "Past Simple", "grammar_note": "noted + down + noun"}, {"sentence": "She is noting down your suggestions.", "context": "brainstorming", "tense": "Present Continuous", "grammar_note": "note down (contextual)"}, {"sentence": "Make sure to note it down.", "context": "instruction", "tense": "Infinitive", "grammar_note": "to + note + pronoun + down (separable)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('phase in', 'To issue or introduce gradually.', 'wprowadzać stopniowo', 'business', '{strategy,change mgmt}', 'neutral', 'C1', '[{"sentence": "We will phase in the new software over 3 months.", "context": "IT rollout", "tense": "Future Simple", "grammar_note": "will + phase + in + noun"}, {"sentence": "The changes are being phased in.", "context": "status update", "tense": "Present Continuous Passive", "grammar_note": "phased + in (passive)"}, {"sentence": "Phasing in the rules gently is better.", "context": "policy advice", "tense": "Gerund", "grammar_note": "phase in (contextual)"}, {"sentence": "They phased in the price hike.", "context": "pricing strategy", "tense": "Past Simple", "grammar_note": "phased + in + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('plan ahead', 'To prepare for the future.', 'planować z wyprzedzeniem', 'general', '{strategy,planning}', 'neutral', 'B2', '[{"sentence": "We need to plan ahead to avoid delays.", "context": "project mgmt", "tense": "Infinitive", "grammar_note": "to + plan + ahead + noun"}, {"sentence": "He is good at planning ahead.", "context": "appraisal", "tense": "Gerund", "grammar_note": "plan + noun + ahead (separable)"}, {"sentence": "If you don''t plan ahead, you fail.", "context": "proverbial advice", "tense": "First Conditional", "grammar_note": "not + plan + ahead + noun"}, {"sentence": "Planning ahead is essential in this market.", "context": "strategic advice", "tense": "Gerund", "grammar_note": "Imperative: plan + noun + ahead (separable)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('press ahead', 'To continue with determination.', 'napierać, kontynuować (mimo trudności)', 'business', '{strategy,resilience}', 'neutral', 'C1', '[{"sentence": "They pressed ahead with the launch despite the risks.", "context": "bold move", "tense": "Past Simple", "grammar_note": "pressed + ahead + noun"}, {"sentence": "We must press ahead with reform.", "context": "change mgmt", "tense": "Modal Obligation", "grammar_note": "must + press + ahead + noun"}, {"sentence": "Are we pressing ahead or pausing?", "context": "decision point", "tense": "Present Continuous", "grammar_note": "be + pressing + ahead + noun"}, {"sentence": "Pressing ahead regardless can be dangerous.", "context": "risk warning", "tense": "Gerund", "grammar_note": "pressing + ahead + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('report back', 'To return with information.', 'zdać relację', 'business', '{communication,management}', 'neutral', 'B2', '[{"sentence": "Please report back to me by noon.", "context": "delegation", "tense": "Imperative", "grammar_note": "report + back + noun"}, {"sentence": "She reported back on the client meeting.", "context": "follow-up", "tense": "Past Simple", "grammar_note": "reported + back + noun"}, {"sentence": "I''m waiting for the team to report back.", "context": "status", "tense": "Infinitive", "grammar_note": "to + report + back + noun"}, {"sentence": "Reporting back regularly ensures alignment.", "context": "process tip", "tense": "Gerund", "grammar_note": "reporting + back + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('sell off', 'To sell assets, usually because of financial need.', 'wyprzedać (majątek, aktywa)', 'business', '{finance,asset mgmt}', 'neutral', 'B2', '[{"sentence": "The company sold off its real estate assets.", "context": "liquidation", "tense": "Past Simple", "grammar_note": "sold + off + noun"}, {"sentence": "They are selling off the non-core divisions.", "context": "restructuring", "tense": "Present Continuous", "grammar_note": "be + selling + off + noun"}, {"sentence": "A massive sell-off occurred in the market.", "context": "stock market", "tense": "Noun usage", "grammar_note": "selloff (noun/adjective)"}, {"sentence": "Selling off inventory at a discount.", "context": "clearance", "tense": "Gerund", "grammar_note": "selling + off + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('ask around', 'To ask many people the same question.', 'popytać (wśród ludzi)', 'general', '{networking,research}', 'neutral', 'B2', '[{"sentence": "I''ll ask around to see if anyone knows a good developer.", "context": "hiring", "tense": "Future Simple", "grammar_note": "will + ask + around + noun"}, {"sentence": "She asked around the office but nobody knew.", "context": "lost item", "tense": "Past Simple", "grammar_note": "asked + around + noun"}, {"sentence": "Asking around is the best way to find recommendations.", "context": "advice", "tense": "Gerund", "grammar_note": "asking + around + noun (gerund)"}, {"sentence": "Did you ask around before deciding?", "context": "due diligence", "tense": "Past Simple Question", "grammar_note": "ask + around + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('call back', 'To return a phone call.', 'oddzwonić', 'general', '{communication,phone}', 'neutral', 'B2', '[{"sentence": "I will call you back in 5 minutes.", "context": "phone etiquette", "tense": "Future Simple", "grammar_note": "will + call + pronoun + back (separable)"}, {"sentence": "Has he called back yet?", "context": "waiting", "tense": "Present Perfect", "grammar_note": "has + called + back + noun"}, {"sentence": "Please ask him to call me back.", "context": "message", "tense": "Infinitive", "grammar_note": "to + call + pronoun + back (separable)"}, {"sentence": "Calling back customers promptly is vital.", "context": "customer service", "tense": "Gerund", "grammar_note": "calling + back + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('call in', 'To request the presence of a specialist/help.', 'wezwać (specjalistę, pomoc)', 'business', '{management,support}', 'neutral', 'B2', '[{"sentence": "We had to call in a consultant.", "context": "specialist help", "tense": "Past Simple", "grammar_note": "to + call + in + noun"}, {"sentence": "She called in sick today.", "context": "HR / absence", "tense": "Past Simple", "grammar_note": "called + in + noun"}, {"sentence": "They called in the loans.", "context": "banking (demand repayment)", "tense": "Past Simple", "grammar_note": "called + in + noun"}, {"sentence": "Calling in favours is sometimes necessary.", "context": "politics", "tense": "Gerund", "grammar_note": "calling + in + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('check up on', 'To monitor someone or verify their condition.', 'sprawdzać (kogoś), kontrolować', 'general', '{management,supervision}', 'neutral', 'B2', '[{"sentence": "My boss is always checking up on me.", "context": "micromanagement", "tense": "Present Continuous", "grammar_note": "be + checking + up on + noun"}, {"sentence": "I need to check up on the new intern.", "context": "supervision", "tense": "Infinitive", "grammar_note": "to + check + up on + noun"}, {"sentence": "Checking up on progress is part of the job.", "context": "management duty", "tense": "Gerund", "grammar_note": "checking + up on + noun (gerund)"}, {"sentence": "Did you check up on that client?", "context": "sales follow-up", "tense": "Past Simple Question", "grammar_note": "check + up on + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('clear up', 'To tidy OR to clarify a misunderstanding.', 'wyjaśnić (nieporozumienie), posprzątać', 'general', '{communication,organization}', 'neutral', 'B2', '[{"sentence": "We hope to clear up the confusion soon.", "context": "PR statement", "tense": "Infinitive", "grammar_note": "to + clear + up + noun"}, {"sentence": "Can you clear up this mess on your desk?", "context": "cleanliness", "tense": "Modal Request", "grammar_note": "can + clear + up + noun"}, {"sentence": "The weather cleared up later.", "context": "weather", "tense": "Past Simple", "grammar_note": "cleared + up + noun"}, {"sentence": "Let''s clear up any doubts before signing.", "context": "negotiation", "tense": "Imperative", "grammar_note": "clear + up + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('come out', 'To be published/released OR result.', 'wyjść (ukazać się), wyniknąć', 'general', '{marketing,results}', 'neutral', 'B2', '[{"sentence": "The new report comes out next week.", "context": "publication", "tense": "Present Simple (future)", "grammar_note": "come + out + noun"}, {"sentence": "It came out that he was lying.", "context": "revelation", "tense": "Past Simple", "grammar_note": "came + out + noun"}, {"sentence": "How did the figures come out?", "context": "result check", "tense": "Past Simple Question", "grammar_note": "come + out + noun"}, {"sentence": "Everything came out fine in the end.", "context": "reassurance", "tense": "Past Simple", "grammar_note": "came + out + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('count in', 'To include someone.', 'wliczyć kogoś, uwzględnić', 'general', '{social,planning}', 'informal', 'B2', '[{"sentence": "If you''re ordering lunch, count me in.", "context": "social", "tense": "Imperative", "grammar_note": "count + pronoun + in (separable)"}, {"sentence": "Did you count John in for the meeting?", "context": "invitation check", "tense": "Past Simple Question", "grammar_note": "count + noun + in (separable)"}, {"sentence": "Count me in for the project.", "context": "volunteering", "tense": "Imperative", "grammar_note": "Imperative: count + pronoun + in (separable)"}, {"sentence": "You can count us in.", "context": "agreement", "tense": "Modal Ability", "grammar_note": "can + count + pronoun + in (separable)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('do without', 'To manage without something.', 'obejść się bez czegoś', 'general', '{resources,resilience}', 'neutral', 'B2', '[{"sentence": "We''ll have to do without extra staff.", "context": "budget cuts", "tense": "Future Simple", "grammar_note": "will + do + without + noun"}, {"sentence": "I can''t do without my laptop.", "context": "necessity", "tense": "Modal Negative", "grammar_note": "not + do + without + noun"}, {"sentence": "You''ll just have to do without.", "context": "refusal", "tense": "Future Obligation", "grammar_note": "will + do + without + noun"}, {"sentence": "Doing without luxury items saves money.", "context": "finance tip", "tense": "Gerund", "grammar_note": "doing + without + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('drop back', 'To move back or fall behind.', 'zostać w tyle, cofnąć się', 'general', '{movement,position}', 'neutral', 'B2', '[{"sentence": "He dropped back to help his colleague.", "context": "teamwork", "tense": "Past Simple", "grammar_note": "dropped + back + noun"}, {"sentence": "Sales dropped back to 2019 levels.", "context": "regression", "tense": "Past Simple", "grammar_note": "dropped + back + noun"}, {"sentence": "Don''t drop back now.", "context": "encouragement", "tense": "Negative Imperative", "grammar_note": "not + drop + back + noun"}, {"sentence": "The stock dropped back after the rally.", "context": "finance", "tense": "Past Simple", "grammar_note": "dropped + back + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('fill up', 'To make something full.', 'napełnić (np. bak, pokój)', 'general', '{daily,travel}', 'neutral', 'B2', '[{"sentence": "I need to fill up the car with petrol.", "context": "travel", "tense": "Infinitive", "grammar_note": "to + fill + up + noun"}, {"sentence": "The room filled up quickly.", "context": "event attendance", "tense": "Past Simple", "grammar_note": "filled + up + noun"}, {"sentence": "My schedule is filling up.", "context": "busy", "tense": "Present Continuous", "grammar_note": "be + filling + up + noun"}, {"sentence": "Fill it up, please.", "context": "gas station", "tense": "Imperative", "grammar_note": "Imperative: fill + pronoun + up (separable)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get back', 'To return.', 'wrócić', 'general', '{travel,time}', 'neutral', 'B2', '[{"sentence": "When do you get back from New York?", "context": "travel schedule", "tense": "Present Simple", "grammar_note": "get + back + noun"}, {"sentence": "I just got back from lunch.", "context": "status", "tense": "Past Simple", "grammar_note": "got + back + noun"}, {"sentence": "We need to get back to basics.", "context": "strategy reset", "tense": "Infinitive", "grammar_note": "to + get + back + noun"}, {"sentence": "Getting back late makes me tired.", "context": "commute", "tense": "Gerund", "grammar_note": "getting + back + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get in', 'To arrive (train/flight) OR enter (car/building).', 'przyjechać (pociąg), wsiąść, wejść', 'general', '{travel,logistics}', 'neutral', 'B2', '[{"sentence": "What time does your flight get in?", "context": "travel", "tense": "Present Simple", "grammar_note": "get + in + noun"}, {"sentence": "I didn''t get in until midnight.", "context": "late arrival", "tense": "Past Simple Negative", "grammar_note": "not + get + in + noun"}, {"sentence": "Get in the car!", "context": "instruction", "tense": "Imperative", "grammar_note": "Imperative: get + in + noun"}, {"sentence": "We need to get a specialist in.", "context": "hiring (alt)", "tense": "Infinitive", "grammar_note": "to + get + noun + in (separable)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get off', 'To leave a bus/train/etc OR finish work.', 'wysiąść, skończyć pracę', 'general', '{travel,daily}', 'neutral', 'B2', '[{"sentence": "I usually get off work at 5 PM.", "context": "routine", "tense": "Present Simple", "grammar_note": "get + off + noun"}, {"sentence": "We need to get off at the next station.", "context": "travel", "tense": "Infinitive", "grammar_note": "to + get + off + noun"}, {"sentence": "He got off the phone quickly.", "context": "communication", "tense": "Past Simple", "grammar_note": "got + off + noun"}, {"sentence": "Getting off to a good start is important.", "context": "project idiom", "tense": "Gerund", "grammar_note": "getting + off + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get on', 'To board a vehicle OR make progress.', 'wsiąść, radzić sobie', 'general', '{travel,progress}', 'neutral', 'B2', '[{"sentence": "Please get on the bus quickly.", "context": "travel", "tense": "Imperative", "grammar_note": "get + on + noun"}, {"sentence": "How are you getting on with the task?", "context": "check-in", "tense": "Present Continuous", "grammar_note": "be + getting + on + noun"}, {"sentence": "He is getting on well in his new job.", "context": "performance", "tense": "Present Continuous", "grammar_note": "be + getting + on + noun"}, {"sentence": "Let''s get on with it.", "context": "action", "tense": "Imperative", "grammar_note": "get + on + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get out', 'To leave a place OR become known.', 'wyjść, wydostać się (o informacji)', 'general', '{news,exit}', 'neutral', 'B2', '[{"sentence": "We need to get out of this contract.", "context": "legal (informal)", "tense": "Infinitive", "grammar_note": "to + get + out + noun"}, {"sentence": "The secret got out.", "context": "leak", "tense": "Past Simple", "grammar_note": "got + out + noun"}, {"sentence": "Get out of the building immediately!", "context": "safety warning", "tense": "Imperative", "grammar_note": "Imperative: get + out + noun"}, {"sentence": "Getting the product out on time was hard.", "context": "launch", "tense": "Gerund", "grammar_note": "getting + noun + out (gerund) (separable)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get through', 'To finish a task OR connect by phone.', 'przebrnąć (przez coś), dodzwonić się', 'general', '{phone,workload}', 'neutral', 'B2', '[{"sentence": "I finally got through to customer support.", "context": "phone call", "tense": "Past Simple", "grammar_note": "got + through + noun"}, {"sentence": "We have a lot of data to get through.", "context": "analysis", "tense": "Infinitive", "grammar_note": "to + get + through + noun"}, {"sentence": "She got through the interview successfully.", "context": "hiring", "tense": "Past Simple", "grammar_note": "got + through + noun"}, {"sentence": "How can we get through to them?", "context": "persuasion", "tense": "Modal Question", "grammar_note": "can + get + through + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get together', 'To meet socially or for work.', 'spotkać się, zebrać się', 'general', '{social,meetings}', 'neutral', 'B2', '[{"sentence": "Let''s get together for a brainstorming session.", "context": "collaboration", "tense": "Imperative", "grammar_note": "get + together + noun"}, {"sentence": "They got together to sign the deal.", "context": "meeting", "tense": "Past Simple", "grammar_note": "got + together + noun"}, {"sentence": "We should get together more often.", "context": "team building", "tense": "Modal Advice", "grammar_note": "should + get + together + noun"}, {"sentence": "Getting everyone together is difficult.", "context": "scheduling", "tense": "Gerund", "grammar_note": "getting + noun + together (gerund) (separable)"}]');
