-- ============================================
-- Import phrasal verbs: ID 251-275 (25 wpisów)
-- Wklej ten SQL w Supabase SQL Editor i kliknij Run
-- ============================================

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('give back', 'To return something.', 'oddać, zwrócić', 'general', '{social,charity}', 'neutral', 'B2', '[{"sentence": "It''s time to give back to the community.", "context": "CSR (Corporate Social Responsibility)", "tense": "Infinitive", "grammar_note": "to + give + back + noun"}, {"sentence": "Please give back the signed copy.", "context": "admin", "tense": "Imperative", "grammar_note": "give + back + noun"}, {"sentence": "He gave back the award.", "context": "scandal", "tense": "Past Simple", "grammar_note": "gave + back + noun"}, {"sentence": "Giving back creates goodwill.", "context": "values", "tense": "Gerund", "grammar_note": "giving + back + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go after', 'To pursue something.', 'ścigać, dążyć do czegoś', 'general', '{ambition,strategy}', 'neutral', 'B2', '[{"sentence": "We decided to go after the youth market.", "context": "targeting", "tense": "Infinitive", "grammar_note": "to + go + after + noun"}, {"sentence": "She went after the promotion aggressively.", "context": "career", "tense": "Past Simple", "grammar_note": "went + after + noun"}, {"sentence": "Go after your goals.", "context": "advice", "tense": "Imperative", "grammar_note": "Imperative: go + after + noun"}, {"sentence": "Are they going after our clients?", "context": "competition", "tense": "Present Continuous", "grammar_note": "be + going + after + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('go off', 'To explode/ring OR turn bad (food).', 'włączyć się (alarm), zepsuć się (jedzenie)', 'general', '{safety,daily}', 'neutral', 'B2', '[{"sentence": "The fire alarm went off at noon.", "context": "safety drill", "tense": "Past Simple", "grammar_note": "went + off + noun"}, {"sentence": "My presentation went off well.", "context": "success (idiom ''went off well'')", "tense": "Past Simple", "grammar_note": "went + off + noun"}, {"sentence": "The milk has gone off.", "context": "kitchen", "tense": "Present Perfect", "grammar_note": "has + gone + off + noun"}, {"sentence": "Did the meeting go off as planned?", "context": "review", "tense": "Past Simple Question", "grammar_note": "go + off + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hang on', 'To wait.', 'czekać (chwilę)', 'general', '{phone,requests}', 'informal', 'B2', '[{"sentence": "Hang on a second, please.", "context": "interruption", "tense": "Imperative", "grammar_note": "Imperative: hang + on + noun"}, {"sentence": "Can you hang on while I check?", "context": "phone", "tense": "Modal Request", "grammar_note": "can + hang + on + noun"}, {"sentence": "Everything hangs on this decision.", "context": "dependence (alt meaning)", "tense": "Present Simple", "grammar_note": "hang + on + noun"}, {"sentence": "Hanging on for too long is risky.", "context": "delay", "tense": "Gerund", "grammar_note": "hanging + on + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('join in', 'To participate.', 'dołączyć, przyłączyć się', 'general', '{teamwork,social}', 'neutral', 'B2', '[{"sentence": "Please join in the discussion.", "context": "meeting facilitation", "tense": "Imperative", "grammar_note": "join + in + noun"}, {"sentence": "Everyone joined in to help.", "context": "collaboration", "tense": "Past Simple", "grammar_note": "joined + in + noun"}, {"sentence": "Feel free to join in anytime.", "context": "invitation", "tense": "Infinitive", "grammar_note": "to + join + in + noun"}, {"sentence": "Joining in shows commitment.", "context": "team spirit", "tense": "Gerund", "grammar_note": "joining + in + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('keep out', 'To stop someone entering.', 'nie wchodzić, trzymać (kogoś) z daleka', 'general', '{security,safety}', 'neutral', 'B2', '[{"sentence": "Unauthorized personnel must keep out.", "context": "warning sign", "tense": "Modal Obligation", "grammar_note": "must + keep + out + noun"}, {"sentence": "We need to keep competitors out of this market.", "context": "strategy", "tense": "Infinitive", "grammar_note": "to + keep + noun + out (separable)"}, {"sentence": "Keep out of the discussion if you don''t have facts.", "context": "advice", "tense": "Imperative", "grammar_note": "Imperative: keep + out + noun"}, {"sentence": "The login system keeps hackers out.", "context": "cybersecurity", "tense": "Present Simple", "grammar_note": "keep + noun + out (separable)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('log in', 'To access a computer system.', 'zalogować się', 'general', '{technology,daily}', 'neutral', 'B2', '[{"sentence": "Please log in with your credentials.", "context": "instructions", "tense": "Imperative", "grammar_note": "log + in + noun"}, {"sentence": "I can''t log in to the network.", "context": "IT support", "tense": "Modal Negative", "grammar_note": "not + log + in + noun"}, {"sentence": "He logged in remotely.", "context": "remote work", "tense": "Past Simple", "grammar_note": "logged + in + noun"}, {"sentence": "Logging in takes too long.", "context": "complaint", "tense": "Gerund", "grammar_note": "Imperative: log + in + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('log off', 'To exit a computer system.', 'wylogować się', 'general', '{technology,security}', 'neutral', 'B2', '[{"sentence": "Remember to log off before you leave.", "context": "security policy", "tense": "Imperative", "grammar_note": "to + log + off + noun"}, {"sentence": "The system logs off automatically.", "context": "feature", "tense": "Present Simple", "grammar_note": "log + off + noun"}, {"sentence": "She logged off at 5 PM.", "context": "routine", "tense": "Past Simple", "grammar_note": "logged + off + noun"}, {"sentence": "Why did you log off?", "context": "inquiry", "tense": "Past Simple Question", "grammar_note": "log + off + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('look back', 'To think about the past.', 'wspominać, patrzeć wstecz', 'general', '{reflection,history}', 'neutral', 'B2', '[{"sentence": "Looking back, it was a good decision.", "context": "reflection", "tense": "Participle", "grammar_note": "looking + back + noun (gerund)"}, {"sentence": "Don''t look back in anger.", "context": "advice/idiom", "tense": "Negative Imperative", "grammar_note": "not + look + back + noun"}, {"sentence": "We looked back on our first year.", "context": "anniversary", "tense": "Past Simple", "grammar_note": "looked + back + noun"}, {"sentence": "Never look back.", "context": "motivation", "tense": "Imperative", "grammar_note": "look + back + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('look up to', 'To respect and admire someone.', 'podziwiać, brać przykład z kogoś', 'general', '{mentorship,respect}', 'neutral', 'B2', '[{"sentence": "I look up to my mentor.", "context": "admiration", "tense": "Present Simple", "grammar_note": "look + up to + noun"}, {"sentence": "Employees look up to a strong leader.", "context": "leadership", "tense": "Present Simple", "grammar_note": "look + up to + noun"}, {"sentence": "She is someone to look up to.", "context": "role model", "tense": "Infinitive", "grammar_note": "to + look + up to + noun"}, {"sentence": "He always looked up to his father.", "context": "family", "tense": "Past Simple", "grammar_note": "looked + up to + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('move on', 'To proceed to the next topic or stage.', 'przejść dalej (do kolejnego punktu)', 'business', '{meetings,progress}', 'neutral', 'B2', '[{"sentence": "Let''s move on to the next item.", "context": "meeting agenda", "tense": "Imperative", "grammar_note": "move + on + noun"}, {"sentence": "It''s time to move on.", "context": "change", "tense": "Infinitive", "grammar_note": "to + move + on + noun"}, {"sentence": "He moved on to a new company.", "context": "career change", "tense": "Past Simple", "grammar_note": "moved + on + noun"}, {"sentence": "Moving on...", "context": "transition phrase", "tense": "Participle", "grammar_note": "move on (contextual)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('print out', 'To produce a hard copy.', 'wydrukować', 'general', '{office,admin}', 'neutral', 'B2', '[{"sentence": "Can you print out the agenda?", "context": "meeting prep", "tense": "Modal Request", "grammar_note": "can + print + out + noun"}, {"sentence": "I printed out two copies.", "context": "documentation", "tense": "Past Simple", "grammar_note": "printed + out + noun"}, {"sentence": "Don''t print it out unless necessary.", "context": "eco-friendly policy", "tense": "Negative Imperative", "grammar_note": "not + print + pronoun + out (separable)"}, {"sentence": "Printing out emails is wasteful.", "context": "efficiency", "tense": "Gerund", "grammar_note": "printing + out + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('see off', 'To say goodbye to someone leaving.', 'odprowadzić (kogoś), pożegnać', 'general', '{travel,social}', 'neutral', 'B2', '[{"sentence": "I went to the airport to see him off.", "context": "farewell", "tense": "Infinitive", "grammar_note": "to + see + pronoun + off (separable)"}, {"sentence": "The team saw off the visitors.", "context": "hosting", "tense": "Past Simple", "grammar_note": "saw + off + noun"}, {"sentence": "Let''s see them off.", "context": "suggestion", "tense": "Imperative", "grammar_note": "see + pronoun + off (separable)"}, {"sentence": "Seeing off a colleague is polite.", "context": "etiquette", "tense": "Gerund", "grammar_note": "seeing + off + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('switch off', 'To turn off OR stop paying attention/relax.', 'wyłączyć, wyłączyć się (zrelaksować)', 'general', '{technology,relaxation}', 'neutral', 'B2', '[{"sentence": "Switch off the lights.", "context": "energy saving", "tense": "Imperative", "grammar_note": "Imperative: switch + off + noun"}, {"sentence": "It''s hard to switch off after work.", "context": "work-life balance", "tense": "Infinitive", "grammar_note": "to + switch + off + noun"}, {"sentence": "I just switched off and watched TV.", "context": "relaxing", "tense": "Past Simple", "grammar_note": "switched + off + noun"}, {"sentence": "He switched off during the lecture.", "context": "boredom", "tense": "Past Simple", "grammar_note": "switched + off + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('switch on', 'To activate something.', 'włączyć', 'general', '{technology,daily}', 'neutral', 'B2', '[{"sentence": "Switch on the projector.", "context": "presentation", "tense": "Imperative", "grammar_note": "Imperative: switch + on + noun"}, {"sentence": "The alarm switches on automatically.", "context": "feature", "tense": "Present Simple", "grammar_note": "switch + noun + on (separable)"}, {"sentence": "Can you switch on the air con?", "context": "office", "tense": "Modal Request", "grammar_note": "can + switch + on + noun"}, {"sentence": "He switched on his charm.", "context": "metaphor", "tense": "Past Simple", "grammar_note": "switched + on + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('take up', 'To start a hobby OR occupy space/time.', 'zacząć (hobby), zajmować (czas/miejsce)', 'general', '{hobbies,time mgmt}', 'neutral', 'B2', '[{"sentence": "I took up golf for networking.", "context": "hobby", "tense": "Past Simple", "grammar_note": "took + up + noun"}, {"sentence": "This project takes up all my time.", "context": "workload", "tense": "Present Simple", "grammar_note": "take + up + noun"}, {"sentence": "Do not take up too much space.", "context": "layout", "tense": "Negative Imperative", "grammar_note": "not + take + up + noun"}, {"sentence": "Taking up a new language is hard.", "context": "learning", "tense": "Gerund", "grammar_note": "taking + up + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('write down', 'To record in writing.', 'zapisać', 'general', '{admin,meetings}', 'neutral', 'B2', '[{"sentence": "Write down these instructions.", "context": "training", "tense": "Imperative", "grammar_note": "Imperative: write + down + noun"}, {"sentence": "I wrote it down somewhere.", "context": "memory", "tense": "Past Simple", "grammar_note": "wrote + pronoun + down (separable)"}, {"sentence": "Did you write down the address?", "context": "check", "tense": "Past Simple Question", "grammar_note": "write + down + noun"}, {"sentence": "A write-down of assets.", "context": "accounting (noun)", "tense": "Noun usage", "grammar_note": "writedown (noun/adjective)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('zoom in', 'To focus on details/magnify.', 'przybliżyć (obraz), skupić się na szczególe', 'general', '{technology,analysis}', 'neutral', 'B2', '[{"sentence": "Zoom in on this chart.", "context": "presentation", "tense": "Imperative", "grammar_note": "Imperative: zoom + in + noun"}, {"sentence": "Let''s zoom in on the specifics.", "context": "analysis", "tense": "Imperative", "grammar_note": "zoom + in + noun"}, {"sentence": "The camera zoomed in.", "context": "tech", "tense": "Past Simple", "grammar_note": "zoomed + in + noun"}, {"sentence": "Zooming in helps identify errors.", "context": "QA", "tense": "Gerund", "grammar_note": "zooming + in + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('zoom out', 'To view the bigger picture.', 'oddalić (obraz), spojrzeć szerszej', 'general', '{strategy,perspective}', 'neutral', 'B2', '[{"sentence": "We need to zoom out and look at the strategy.", "context": "management", "tense": "Infinitive", "grammar_note": "to + zoom + out + noun"}, {"sentence": "Zoom out to see the whole map.", "context": "navigation", "tense": "Imperative", "grammar_note": "Imperative: zoom + out + noun"}, {"sentence": "Zooming out gives perspective.", "context": "advice", "tense": "Gerund", "grammar_note": "zooming + out + noun (gerund)"}, {"sentence": "If you zoom out, the trend is clear.", "context": "analysis", "tense": "First Conditional", "grammar_note": "zoom + out + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('brush up on', 'To refresh one''s knowledge.', 'odświeżyć (wiedzę, umiejętności)', 'general', '{learning,skills}', 'neutral', 'C1', '[{"sentence": "I need to brush up on my Spanish.", "context": "learning", "tense": "Infinitive", "grammar_note": "to + brush + up on + noun"}, {"sentence": "Brush up on your excel skills.", "context": "advice", "tense": "Imperative", "grammar_note": "Imperative: brush + up on + noun"}, {"sentence": "He brushed up on the regulations.", "context": "compliance", "tense": "Past Simple", "grammar_note": "brushed + up on + noun"}, {"sentence": "Brushing up is always useful.", "context": "training", "tense": "Gerund", "grammar_note": "brushing + up on (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('come by', 'To visit OR acquire.', 'wpaść (do kogoś), zdobyć (coś)', 'general', '{social,acquisition}', 'neutral', 'C1', '[{"sentence": "Jobs are hard to come by.", "context": "economy", "tense": "Infinitive", "grammar_note": "to + come + by + noun"}, {"sentence": "Please come by my office.", "context": "invitation", "tense": "Imperative", "grammar_note": "come + by + noun"}, {"sentence": "How did you come by this info?", "context": "inquiry", "tense": "Past Simple Question", "grammar_note": "come + by + noun"}, {"sentence": "He came by some money unexpectedly.", "context": "inheritance", "tense": "Past Simple", "grammar_note": "came + by + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hold back', 'To restrain or keep secret.', 'powstrzymywać, zataić', 'general', '{negotiation,emotion}', 'neutral', 'B2', '[{"sentence": "Don''t hold back your ideas.", "context": "brainstorming", "tense": "Negative Imperative", "grammar_note": "hold back + noun (imperative)"}, {"sentence": "He held back his anger.", "context": "emotion control", "tense": "Past Simple", "grammar_note": "held back + noun"}, {"sentence": "They are holding back information.", "context": "secrecy", "tense": "Present Continuous", "grammar_note": "are holding back (present continuous)"}, {"sentence": "Something is holding back growth.", "context": "analysis", "tense": "Present Continuous", "grammar_note": "is holding back (present continuous)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('give off', 'To emit (smell/heat/vibes).', 'wydzielać (zapach, ciepło, atmosferę)', 'general', '{environment,impression}', 'neutral', 'B2', '[{"sentence": "The machine gives off heat.", "context": "machinery", "tense": "Present Simple", "grammar_note": "not + hold + back + noun"}, {"sentence": "He gives off a confident vibe.", "context": "impression", "tense": "Present Simple", "grammar_note": "hold back (contextual)"}, {"sentence": "This plant gives off a bad smell.", "context": "nature", "tense": "Present Simple", "grammar_note": "be + holding + back + noun"}, {"sentence": "Giving off mixed signals.", "context": "communication", "tense": "Gerund", "grammar_note": "be + holding + back + noun"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('grow on', 'To become liked gradually.', 'przekonać do siebie (z czasem)', 'general', '{preference,opinion}', 'neutral', 'C1', '[{"sentence": "This idea is growing on me.", "context": "decision making", "tense": "Present Continuous", "grammar_note": "give + off + noun"}, {"sentence": "The new office will grow on you.", "context": "change", "tense": "Future Simple", "grammar_note": "give + off + noun"}, {"sentence": "He eventually grew on the team.", "context": "relationships", "tense": "Past Simple", "grammar_note": "give + off + noun"}, {"sentence": "Acquired tastes grow on you.", "context": "proverb", "tense": "Present Simple", "grammar_note": "giving + off + noun (gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hand out', 'To distribute.', 'rozdać', 'general', '{meetings,training}', 'neutral', 'B2', '[{"sentence": "Please hand out the brochures.", "context": "event", "tense": "Imperative", "grammar_note": "be + growing + on + noun"}, {"sentence": "They handed out prizes.", "context": "ceremony", "tense": "Past Simple", "grammar_note": "will + grow + on + noun"}, {"sentence": "Handing out tasks effectively is a skill.", "context": "management", "tense": "Gerund", "grammar_note": "grow on (contextual)"}, {"sentence": "Hand-out materials.", "context": "training", "tense": "Noun usage", "grammar_note": "grow + on + noun"}]');
