-- ============================================
-- Import phrasal verbs: ID 151-200 (50 wpisów)
-- Wklej ten SQL w Supabase SQL Editor i kliknij Run
-- ============================================

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('put away', 'To place something in its proper storage location. Also means to save money for future use.', 'odkładać na miejsce; odkładać (pieniądze)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She put away all the dishes after dinner.", "context": "tidying the kitchen after a meal", "tense": "Past Simple", "grammar_note": "subject + put away + object (separable phrasal verb)"}, {"sentence": "I''ve been putting away a little money each month for a holiday.", "context": "saving money over a period of time", "tense": "Present Perfect Continuous", "grammar_note": "have been + putting away + object (continuous aspect for ongoing action)"}, {"sentence": "Put your toys away before you go outside!", "context": "parent instructing a child to tidy up", "tense": "Imperative", "grammar_note": "imperative + object + away (separated form with object between verb and particle)"}, {"sentence": "The groceries will be put away by the time you get home.", "context": "promising to finish a household task", "tense": "Future Simple", "grammar_note": "will be + past participle (passive voice, future)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('put on', 'To place clothing or accessories on your body. Also means to start a device or to stage an event.', 'zakładać (ubranie); włączać; organizować (wydarzenie)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "He put on his jacket and left the house.", "context": "getting ready to go outside in cold weather", "tense": "Past Simple", "grammar_note": "subject + put on + object (inseparable in this usage)"}, {"sentence": "She is putting on a brave face despite the bad news.", "context": "hiding emotions in a difficult situation", "tense": "Present Continuous", "grammar_note": "is + putting on + noun phrase (idiomatic expression)"}, {"sentence": "The school has put on a wonderful play this year.", "context": "a school producing a theatrical performance", "tense": "Present Perfect", "grammar_note": "has + past participle + object (present perfect for recent event)"}, {"sentence": "You should put on some sunscreen before going to the beach.", "context": "advising someone about sun protection", "tense": "Conditional", "grammar_note": "should + put on + object (modal verb for advice)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('put out', 'To extinguish a fire or light. Also means to publish or release something, or to inconvenience someone.', 'gasić (ogień); wydawać (publikację); sprawiać kłopot', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "The firefighters put out the blaze within an hour.", "context": "emergency response to a building fire", "tense": "Past Simple", "grammar_note": "subject + put out + object (separable phrasal verb)"}, {"sentence": "The company has put out a statement regarding the incident.", "context": "a business issuing an official response", "tense": "Present Perfect", "grammar_note": "has + put out + object (present perfect for recent action with current relevance)"}, {"sentence": "I hope I''m not putting you out by arriving so early.", "context": "a guest worried about inconveniencing the host", "tense": "Present Continuous", "grammar_note": "am not + putting out + object (continuous for current action)"}, {"sentence": "Make sure the campfire is put out before you leave.", "context": "safety instructions at a campsite", "tense": "Passive Voice", "grammar_note": "is + past participle (passive imperative construction)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('put up with', 'To tolerate or endure something unpleasant without complaining.', 'znosić, tolerować', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She put up with his bad behaviour for years before leaving.", "context": "enduring a difficult relationship", "tense": "Past Simple", "grammar_note": "subject + put up with + object (three-part inseparable phrasal verb)"}, {"sentence": "I can''t put up with this noise any longer!", "context": "complaining about loud neighbours", "tense": "Present Simple", "grammar_note": "can''t + put up with + object (modal verb for inability)"}, {"sentence": "They have been putting up with poor service for months.", "context": "customers frustrated with a utility provider", "tense": "Present Perfect Continuous", "grammar_note": "have been + putting up with (continuous for ongoing situation)"}, {"sentence": "Why should we put up with such unfair treatment?", "context": "questioning an unjust policy at work", "tense": "Conditional", "grammar_note": "should + put up with (modal in rhetorical question)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('run away', 'To leave a place quickly in order to escape from someone or something.', 'uciekać, zbiec', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "The dog ran away when the fireworks started.", "context": "a pet frightened by loud noises", "tense": "Past Simple", "grammar_note": "subject + ran away + time clause (intransitive phrasal verb)"}, {"sentence": "Don''t run away from your problems; face them.", "context": "encouraging someone to deal with difficulties", "tense": "Imperative", "grammar_note": "don''t + run away + from (negative imperative with preposition)"}, {"sentence": "He has run away from home three times this year.", "context": "a troubled teenager leaving home repeatedly", "tense": "Present Perfect", "grammar_note": "has + past participle + frequency adverb (present perfect for repeated past actions)"}, {"sentence": "If I saw a bear, I would probably run away immediately.", "context": "imagining an encounter with a wild animal", "tense": "Conditional", "grammar_note": "would + run away (second conditional for hypothetical situation)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('run over', 'To hit someone or something with a vehicle. Also means to exceed an allotted time or to review something quickly.', 'przejechać (kogoś); przekroczyć (czas); przejrzeć pobieżnie', 'both', '{daily,meetings}', 'neutral', 'B2', '[{"sentence": "A car nearly ran over the cat on our street last night.", "context": "a dangerous incident involving a pet", "tense": "Past Simple", "grammar_note": "subject + ran over + object (separable, but kept together here)"}, {"sentence": "The meeting is running over by twenty minutes.", "context": "a meeting exceeding its scheduled time", "tense": "Present Continuous", "grammar_note": "is + running over + by (continuous for action happening now)"}, {"sentence": "Could we run over the main points one more time?", "context": "requesting a quick review before a presentation", "tense": "Conditional", "grammar_note": "could + run over + object (polite request with modal)"}, {"sentence": "The details had been run over briefly before the final decision was made.", "context": "reviewing information prior to an important choice", "tense": "Past Perfect", "grammar_note": "had been + past participle (past perfect passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('set off', 'To begin a journey. Also means to cause something to explode or to trigger an alarm or reaction.', 'wyruszać (w podróż); uruchamiać (alarm); detonować', 'general', '{daily,travel}', 'neutral', 'B2', '[{"sentence": "We set off early in the morning to avoid the traffic.", "context": "starting a road trip at dawn", "tense": "Past Simple", "grammar_note": "subject + set off + adverb of time (intransitive, no object needed)"}, {"sentence": "The smoke from the kitchen has set off the fire alarm.", "context": "cooking accident triggering a safety device", "tense": "Present Perfect", "grammar_note": "has + set off + object (present perfect for result visible now)"}, {"sentence": "They will be setting off for Paris tomorrow afternoon.", "context": "planning a trip to France", "tense": "Future Continuous", "grammar_note": "will be + setting off (future continuous for planned arrangement)"}, {"sentence": "Setting off firecrackers in the city centre is strictly prohibited.", "context": "a public safety regulation about fireworks", "tense": "Gerund", "grammar_note": "gerund as subject + is + adjective (gerund clause as subject of sentence)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('settle down', 'To become calm and quiet after a period of excitement. Also means to start living a stable, routine life, often in one place.', 'uspokajać się; osiedlać się; ustatkować się', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "The children eventually settled down after the party.", "context": "kids calming down after excitement", "tense": "Past Simple", "grammar_note": "subject + settled down + time adverb (intransitive phrasal verb)"}, {"sentence": "He''s thinking about settling down and buying a house.", "context": "considering a more permanent lifestyle", "tense": "Gerund", "grammar_note": "thinking about + settling down (gerund after preposition)"}, {"sentence": "Once you have settled down in your new city, invite us to visit.", "context": "friends discussing a relocation", "tense": "Present Perfect", "grammar_note": "once + present perfect (time clause for future completion)"}, {"sentence": "Settle down, everyone — the lesson is about to begin.", "context": "a teacher addressing a noisy classroom", "tense": "Imperative", "grammar_note": "imperative form + vocative (direct command)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('show off', 'To behave in a way that is intended to attract attention and impress others. Also means to display something proudly.', 'popisywać się; chwalić się (czymś)', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "He was showing off his new car to all the neighbours.", "context": "proudly displaying a recent purchase", "tense": "Past Continuous", "grammar_note": "was + showing off + object (continuous for ongoing past action)"}, {"sentence": "Stop showing off — nobody is impressed.", "context": "telling someone their boasting is unwelcome", "tense": "Imperative", "grammar_note": "stop + gerund (imperative with gerund complement)"}, {"sentence": "She has always shown off her cooking skills at family gatherings.", "context": "someone who regularly demonstrates talent at events", "tense": "Present Perfect", "grammar_note": "has always + past participle (present perfect with frequency adverb)"}, {"sentence": "The new gallery will show off the artist''s latest collection.", "context": "an upcoming exhibition at a gallery", "tense": "Future Simple", "grammar_note": "will + show off + object (future simple for scheduled event)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('show up', 'To arrive or appear at a place, sometimes unexpectedly. Also means to become visible or to embarrass someone by performing better.', 'pojawiać się; przyjść; zjawić się', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "He showed up at the party without being invited.", "context": "an unexpected guest at a social event", "tense": "Past Simple", "grammar_note": "subject + showed up + prepositional phrase (intransitive)"}, {"sentence": "She hasn''t shown up for work in three days.", "context": "an employee absent without notice", "tense": "Present Perfect", "grammar_note": "hasn''t + past participle + duration (present perfect negative)"}, {"sentence": "If he doesn''t show up by noon, we''ll leave without him.", "context": "waiting for a late friend before a trip", "tense": "Conditional", "grammar_note": "if + present simple, will + infinitive (first conditional)"}, {"sentence": "The stain kept showing up even after several washes.", "context": "trying to remove a mark from clothing", "tense": "Past Simple", "grammar_note": "kept + gerund (past simple with ''keep'' + gerund for repeated action)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('shut down', 'To stop operating or to close a business, machine, or system completely.', 'zamykać (firmę); wyłączać (system/maszynę)', 'both', '{daily,finance}', 'neutral', 'B2', '[{"sentence": "The factory was shut down due to safety violations.", "context": "authorities closing an unsafe workplace", "tense": "Passive Voice", "grammar_note": "was + past participle + reason clause (passive with due to)"}, {"sentence": "Please shut down your computer before leaving the office.", "context": "an office instruction at the end of the day", "tense": "Imperative", "grammar_note": "imperative + object + time clause (polite command)"}, {"sentence": "The website has been shutting down intermittently all week.", "context": "recurring technical problems with a server", "tense": "Present Perfect Continuous", "grammar_note": "has been + shutting down + adverb (continuous for repeated interruptions)"}, {"sentence": "If sales continue to drop, they will shut down the branch.", "context": "a business considering closing a location", "tense": "Future Simple", "grammar_note": "if + present simple, will + shut down (first conditional)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('sit down', 'To move from a standing position to a seated one. Also used to mean having a serious discussion.', 'siadać; usiąść', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Please sit down and make yourself comfortable.", "context": "welcoming a guest into your home", "tense": "Imperative", "grammar_note": "imperative + coordinated clause (polite instruction)"}, {"sentence": "We sat down together and discussed the problem calmly.", "context": "resolving a disagreement between friends", "tense": "Past Simple", "grammar_note": "subject + sat down + adverb (intransitive with coordinated verbs)"}, {"sentence": "I was just sitting down to eat when the phone rang.", "context": "being interrupted during mealtime", "tense": "Past Continuous", "grammar_note": "was + sitting down + when clause (interrupted action in the past)"}, {"sentence": "We need to sit down with the team and sort this out.", "context": "planning a meeting to resolve an issue at work", "tense": "Infinitive", "grammar_note": "need + to sit down + with (infinitive of purpose)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('stand up', 'To rise to a standing position from sitting or lying down. Also means to defend or support something, or to fail to meet someone as planned.', 'wstawać; stawać w obronie; wystawić kogoś (nie przyjść na spotkanie)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Everyone stood up when the judge entered the courtroom.", "context": "showing respect in a legal setting", "tense": "Past Simple", "grammar_note": "subject + stood up + when clause (intransitive with time clause)"}, {"sentence": "You should stand up for what you believe in.", "context": "encouraging someone to defend their values", "tense": "Conditional", "grammar_note": "should + stand up for (modal verb for advice with preposition)"}, {"sentence": "He has stood her up twice — she won''t give him another chance.", "context": "someone repeatedly failing to show up for a date", "tense": "Present Perfect", "grammar_note": "has + past participle + object + frequency adverb (transitive, informal meaning)"}, {"sentence": "Standing up too quickly can make you feel dizzy.", "context": "explaining a common physical reaction", "tense": "Gerund", "grammar_note": "gerund as subject + can + infinitive (gerund clause as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('stick to', 'To continue doing or using something and not change to anything else. To follow a plan, promise, or decision without deviating.', 'trzymać się (planu); pozostać wiernym (czemuś)', 'both', '{daily,meetings}', 'neutral', 'B2', '[{"sentence": "She stuck to her diet even during the holiday season.", "context": "maintaining healthy eating despite temptation", "tense": "Past Simple", "grammar_note": "subject + stuck to + object (inseparable phrasal verb)"}, {"sentence": "Let''s stick to the agenda so we finish on time.", "context": "keeping a meeting focused and efficient", "tense": "Imperative", "grammar_note": "let''s + stick to + object (suggestion with let''s)"}, {"sentence": "He has always stuck to his principles, no matter what.", "context": "describing someone with strong moral character", "tense": "Present Perfect", "grammar_note": "has always + past participle (present perfect with adverb of frequency)"}, {"sentence": "If you stick to the plan, everything will work out fine.", "context": "reassuring someone about a strategy", "tense": "Conditional", "grammar_note": "if + present simple, will + infinitive (first conditional)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('take away', 'To remove something from a place or person. Also means to subtract, or to buy food to eat elsewhere.', 'zabierać; odejmować; zamawiać na wynos', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "The waiter took away our plates before we had finished.", "context": "dining at a restaurant with rushed service", "tense": "Past Simple", "grammar_note": "subject + took away + object + time clause (separable phrasal verb)"}, {"sentence": "Nothing can take away the joy of that moment.", "context": "reflecting on a precious memory", "tense": "Present Simple", "grammar_note": "nothing + can + take away + object (modal with negative subject)"}, {"sentence": "The key message to take away from this lecture is the importance of practice.", "context": "summarising the main point of a lesson", "tense": "Infinitive", "grammar_note": "to take away + from (infinitive as modifier of noun)"}, {"sentence": "Two pizzas had been taken away by the previous customers.", "context": "ordering food at a busy pizzeria", "tense": "Past Perfect", "grammar_note": "had been + past participle (past perfect passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('take back', 'To return something to where it came from. Also means to retract a statement or to accept a returned item.', 'zwracać; cofać (słowa); odbierać', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "I took the faulty product back to the shop for a refund.", "context": "returning a defective item to a store", "tense": "Past Simple", "grammar_note": "subject + took + object + back (separated form)"}, {"sentence": "He refuses to take back what he said about her.", "context": "someone stubbornly standing by hurtful comments", "tense": "Present Simple", "grammar_note": "refuses + to take back + object clause (infinitive complement)"}, {"sentence": "That song really takes me back to my university days.", "context": "a piece of music evoking old memories", "tense": "Present Simple", "grammar_note": "subject + takes + pronoun + back (idiomatic: to evoke nostalgia)"}, {"sentence": "If I could take back those words, I would.", "context": "regretting something said in anger", "tense": "Conditional", "grammar_note": "if + could + infinitive (second conditional for regret)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('take out', 'To remove something from a place. Also means to go on a date with someone, to obtain an official document, or to order food for eating elsewhere.', 'wyjmować; zabrać (kogoś gdzieś); wykupić (polisę); zamawiać na wynos', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "He took out his wallet and paid for the meal.", "context": "paying the bill at a restaurant", "tense": "Past Simple", "grammar_note": "subject + took out + object (separable phrasal verb)"}, {"sentence": "She''s been taking out a new insurance policy for her car.", "context": "arranging vehicle insurance", "tense": "Present Perfect Continuous", "grammar_note": "has been + taking out (continuous for a process in progress)"}, {"sentence": "I''d like to take you out for dinner this Friday.", "context": "inviting someone on a date", "tense": "Conditional", "grammar_note": "would like + to take out + object (polite offer with would)"}, {"sentence": "Don''t forget to take out the rubbish before you go to bed.", "context": "a household reminder in the evening", "tense": "Imperative", "grammar_note": "don''t forget + to take out + object (imperative with infinitive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('think about', 'To consider something carefully or to have something in your mind. To reflect on a subject before making a decision.', 'myśleć o; zastanawiać się nad; rozważać', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "I''ve been thinking about changing careers recently.", "context": "considering a major life decision", "tense": "Present Perfect Continuous", "grammar_note": "have been + thinking about + gerund (continuous for ongoing reflection)"}, {"sentence": "She thought about his offer for days before accepting.", "context": "carefully weighing a job proposal", "tense": "Past Simple", "grammar_note": "subject + thought about + object + duration (past simple with time phrase)"}, {"sentence": "Think about what you really want before you decide.", "context": "advising someone to reflect before acting", "tense": "Imperative", "grammar_note": "imperative + about + wh-clause (command with embedded question)"}, {"sentence": "It''s worth thinking about the long-term consequences.", "context": "urging caution in a planning discussion", "tense": "Gerund", "grammar_note": "it''s worth + gerund (fixed expression with gerund)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('throw away', 'To discard something by putting it in the bin. Also means to waste an opportunity or advantage.', 'wyrzucać; marnować (szansę)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She threw away all the expired food from the fridge.", "context": "cleaning out old groceries", "tense": "Past Simple", "grammar_note": "subject + threw away + object (separable phrasal verb)"}, {"sentence": "Don''t throw away this opportunity — it won''t come again.", "context": "encouraging someone to seize a rare chance", "tense": "Imperative", "grammar_note": "don''t + throw away + object (negative imperative)"}, {"sentence": "Tons of plastic are thrown away every single day around the world.", "context": "discussing the global waste problem", "tense": "Passive Voice", "grammar_note": "are + past participle (present passive for general truth)"}, {"sentence": "He had thrown away the receipt, so he couldn''t return the item.", "context": "regretting the disposal of an important document", "tense": "Past Perfect", "grammar_note": "had + past participle (past perfect for earlier of two past actions)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('try on', 'To put on a piece of clothing to see if it fits or suits you before buying it.', 'przymierzać (ubranie)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She tried on five dresses before finding the perfect one.", "context": "shopping for a special occasion outfit", "tense": "Past Simple", "grammar_note": "subject + tried on + object (separable phrasal verb)"}, {"sentence": "Can I try this jacket on in a larger size?", "context": "asking a shop assistant for help", "tense": "Present Simple", "grammar_note": "can + subject + try + object + on (question with separated verb and particle)"}, {"sentence": "He is trying on shoes at the moment and will be out shortly.", "context": "waiting for someone in a shoe shop", "tense": "Present Continuous", "grammar_note": "is + trying on + object (continuous for action in progress)"}, {"sentence": "I would recommend trying on several options before you decide.", "context": "a sales assistant offering advice", "tense": "Gerund", "grammar_note": "recommend + gerund (verb + gerund complement)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('try out', 'To test something to see how well it works or how much you like it.', 'wypróbowywać; testować', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "We tried out the new restaurant on the corner last weekend.", "context": "testing a recently opened dining place", "tense": "Past Simple", "grammar_note": "subject + tried out + object (separable phrasal verb)"}, {"sentence": "I''ve been trying out different recipes for banana bread.", "context": "experimenting with baking at home", "tense": "Present Perfect Continuous", "grammar_note": "have been + trying out (continuous for ongoing experimentation)"}, {"sentence": "Would you like to try out the software before purchasing it?", "context": "a salesperson offering a product demonstration", "tense": "Conditional", "grammar_note": "would like + to try out (polite offer with infinitive)"}, {"sentence": "The new system is being tried out by a small group of users.", "context": "a pilot test of a technology solution", "tense": "Passive Voice", "grammar_note": "is being + past participle (present continuous passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('turn off', 'To stop a device or machine from working by pressing a switch or button. Also means to cause someone to lose interest.', 'wyłączać (urządzenie); zniechęcać', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Please turn off your mobile phones during the performance.", "context": "an announcement at a theatre before a show", "tense": "Imperative", "grammar_note": "imperative + off + object (polite instruction)"}, {"sentence": "She turned off the lights and went to sleep.", "context": "going to bed at the end of the day", "tense": "Past Simple", "grammar_note": "subject + turned off + object + coordinated clause (sequence of actions)"}, {"sentence": "His arrogance really turns people off.", "context": "describing a personality trait that repels others", "tense": "Present Simple", "grammar_note": "subject + turns off + object (present simple for habitual effect)"}, {"sentence": "The heating should have been turned off before we left.", "context": "realising a mistake after leaving the house", "tense": "Passive Voice", "grammar_note": "should have been + past participle (modal perfect passive for past obligation)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('turn on', 'To start a device, machine, or system by pressing a switch or button. Also means to suddenly attack or become hostile.', 'włączać (urządzenie); zwrócić się przeciwko komuś', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "I turned on the TV just in time for the news.", "context": "watching television in the evening", "tense": "Past Simple", "grammar_note": "subject + turned on + object (separable phrasal verb)"}, {"sentence": "Could you turn on the air conditioning? It''s boiling in here.", "context": "asking someone to cool down a warm room", "tense": "Conditional", "grammar_note": "could + subject + turn on (polite request with modal)"}, {"sentence": "The dog turned on its owner without warning.", "context": "an unexpected attack by a pet", "tense": "Past Simple", "grammar_note": "subject + turned on + object (inseparable, meaning ''attacked'')"}, {"sentence": "The lights are being turned on across the city for the festival.", "context": "preparations for a holiday lighting ceremony", "tense": "Passive Voice", "grammar_note": "are being + past participle (present continuous passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('turn up', 'To arrive at a place, often unexpectedly. Also means to increase the volume, temperature, or level of something.', 'pojawiać się; zjawić się; podkręcać (głośność/temperaturę)', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "He turned up an hour late without any explanation.", "context": "someone arriving very late to a social gathering", "tense": "Past Simple", "grammar_note": "subject + turned up + time phrase (intransitive, meaning ''arrived'')"}, {"sentence": "Can you turn up the volume? I can barely hear the music.", "context": "listening to music with friends", "tense": "Imperative", "grammar_note": "can + subject + turn up + object (request form)"}, {"sentence": "Something will turn up eventually — don''t lose hope.", "context": "encouraging someone during a job search", "tense": "Future Simple", "grammar_note": "will + turn up (future simple for prediction)"}, {"sentence": "My lost keys have finally turned up behind the sofa.", "context": "finding a missing item at home", "tense": "Present Perfect", "grammar_note": "have + past participle + adverb (present perfect for recent discovery)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('use up', 'To consume or exhaust the entire supply of something so that none is left.', 'zużywać (do końca); wyczerpywać (zapasy)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "We''ve used up all the milk — someone needs to go shopping.", "context": "running out of a kitchen staple", "tense": "Present Perfect", "grammar_note": "have + past participle + object (present perfect for result visible now)"}, {"sentence": "She used up her entire savings on the renovation.", "context": "spending all money on a home improvement project", "tense": "Past Simple", "grammar_note": "subject + used up + object + on (separable with prepositional phrase)"}, {"sentence": "Try not to use up all the hot water before everyone showers.", "context": "sharing a bathroom in a busy household", "tense": "Infinitive", "grammar_note": "try + not + to use up (negative infinitive complement)"}, {"sentence": "All the printer ink had been used up by the end of the month.", "context": "office supplies running out at work", "tense": "Past Perfect", "grammar_note": "had been + past participle (past perfect passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('wake up', 'To stop sleeping and become conscious. Also means to become aware of something or to alert someone to a fact.', 'budzić się; obudzić (kogoś); uświadomić sobie', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "I woke up at 5 a.m. because of the thunderstorm.", "context": "being disturbed by bad weather at night", "tense": "Past Simple", "grammar_note": "subject + woke up + time (intransitive phrasal verb)"}, {"sentence": "She usually wakes up before her alarm goes off.", "context": "describing a morning routine habit", "tense": "Present Simple", "grammar_note": "subject + wakes up + time clause (present simple for habitual action)"}, {"sentence": "Wake up! You need to face reality and stop dreaming.", "context": "urging someone to be more realistic", "tense": "Imperative", "grammar_note": "imperative (figurative meaning: become aware)"}, {"sentence": "By the time you wake up tomorrow, I will have already left for the airport.", "context": "explaining early morning travel plans", "tense": "Future Perfect", "grammar_note": "by the time + present simple, will have + past participle (future perfect in time clause)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('watch out', 'To be careful or to pay attention to potential danger.', 'uważać; mieć się na baczności', 'general', '{daily,travel}', 'neutral', 'B2', '[{"sentence": "Watch out! There''s a car coming!", "context": "warning someone crossing the road", "tense": "Imperative", "grammar_note": "imperative (urgent warning, exclamatory)"}, {"sentence": "You need to watch out for pickpockets in crowded tourist areas.", "context": "travel advice about staying safe abroad", "tense": "Infinitive", "grammar_note": "need + to watch out for (infinitive with prepositional complement)"}, {"sentence": "She was watching out for any signs of trouble during the protest.", "context": "observing a public gathering for potential problems", "tense": "Past Continuous", "grammar_note": "was + watching out for (past continuous for ongoing vigilance)"}, {"sentence": "If you had watched out, you wouldn''t have tripped over the step.", "context": "commenting on someone''s minor accident", "tense": "Conditional", "grammar_note": "if + past perfect, would + have + past participle (third conditional for regret)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('wear out', 'To become damaged or useless through prolonged use. Also means to make someone extremely tired.', 'zużywać się; niszczyć (przez użytkowanie); wyczerpywać (kogoś)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "My running shoes have completely worn out after two years.", "context": "needing to replace old sports equipment", "tense": "Present Perfect", "grammar_note": "have + past participle (present perfect for current result of past use)"}, {"sentence": "The long hike wore everyone out by the afternoon.", "context": "a group of friends exhausted after a day of walking", "tense": "Past Simple", "grammar_note": "subject + wore out + object (transitive, meaning ''exhausted'')"}, {"sentence": "These tyres are wearing out faster than expected.", "context": "noticing rapid deterioration of car tyres", "tense": "Present Continuous", "grammar_note": "are + wearing out (continuous for gradual process)"}, {"sentence": "Cheap materials tend to wear out more quickly.", "context": "comparing product quality when shopping", "tense": "Present Simple", "grammar_note": "tend + to wear out (infinitive with ''tend to'' for general tendency)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('work on', 'To spend time and effort trying to improve, fix, or complete something.', 'pracować nad; zajmować się (czymś)', 'both', '{daily,meetings}', 'neutral', 'B2', '[{"sentence": "She has been working on her thesis for over a year.", "context": "a university student doing long-term research", "tense": "Present Perfect Continuous", "grammar_note": "has been + working on + object (continuous for duration)"}, {"sentence": "We worked on the report until midnight to meet the deadline.", "context": "finishing a project under time pressure at work", "tense": "Past Simple", "grammar_note": "subject + worked on + object + until (past simple with time limit)"}, {"sentence": "I need to work on my pronunciation before the interview.", "context": "preparing for a job interview in a foreign language", "tense": "Infinitive", "grammar_note": "need + to work on (infinitive complement for necessity)"}, {"sentence": "The new feature is currently being worked on by the development team.", "context": "a software update in progress", "tense": "Passive Voice", "grammar_note": "is being + past participle + by (present continuous passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('blow up', 'To explode or to destroy something by an explosion. Also means to suddenly become very angry, or to inflate something.', 'eksplodować; wysadzać; wściekać się; nadmuchiwać', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "The old building was blown up to make room for a park.", "context": "controlled demolition of a structure", "tense": "Passive Voice", "grammar_note": "was + past participle + infinitive of purpose (passive with purpose clause)"}, {"sentence": "She blew up at him for forgetting their anniversary.", "context": "an angry reaction to a partner''s forgetfulness", "tense": "Past Simple", "grammar_note": "subject + blew up + at + object (intransitive with preposition, meaning ''got angry'')"}, {"sentence": "Can you help me blow up these balloons for the party?", "context": "preparing decorations for a celebration", "tense": "Infinitive", "grammar_note": "help + object + blow up (infinitive without ''to'' after help)"}, {"sentence": "The story has blown up on social media overnight.", "context": "a piece of news going viral online", "tense": "Present Perfect", "grammar_note": "has + past participle (present perfect for recent development)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('break in', 'To enter a building illegally by force. Also means to wear new shoes or equipment until they become comfortable, or to interrupt a conversation.', 'włamywać się; rozchowywaź (buty); wtrącać się (do rozmowy)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Someone broke in while we were on holiday and stole the television.", "context": "discovering a burglary after returning home", "tense": "Past Simple", "grammar_note": "subject + broke in + time clause (intransitive for forced entry)"}, {"sentence": "I need to break in these new boots before the hiking trip.", "context": "preparing footwear for comfortable use", "tense": "Infinitive", "grammar_note": "need + to break in + object (infinitive complement, transitive)"}, {"sentence": "Sorry to break in, but there''s an urgent phone call for you.", "context": "interrupting a meeting with important news", "tense": "Infinitive", "grammar_note": "sorry + to break in (infinitive of apology for interruption)"}, {"sentence": "The house had been broken into several times before they installed an alarm.", "context": "repeated burglaries prompting a security upgrade", "tense": "Past Perfect", "grammar_note": "had been + past participle + into (past perfect passive with dangling preposition)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('bring back', 'To return something to its original place or owner. Also means to cause someone to remember something or to reintroduce something.', 'przywracać; zwracać; przywoływać (wspomnienia)', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Please bring back the books when you''ve finished reading them.", "context": "lending items to a friend", "tense": "Imperative", "grammar_note": "imperative + back + object + time clause (polite request)"}, {"sentence": "The smell of fresh bread always brings back childhood memories.", "context": "a scent triggering nostalgia", "tense": "Present Simple", "grammar_note": "subject + brings back + object (present simple for habitual effect)"}, {"sentence": "The government has brought back the old tax policy.", "context": "a political decision to reintroduce a former regulation", "tense": "Present Perfect", "grammar_note": "has + past participle + back (present perfect for recent action)"}, {"sentence": "If they brought back the original recipe, sales would probably increase.", "context": "speculating about a product change", "tense": "Conditional", "grammar_note": "if + past simple, would + infinitive (second conditional)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('burn out', 'To become physically or emotionally exhausted from overwork or stress. Also means to stop burning or functioning because of excessive use.', 'wypalać się (zawodowo/emocjonalnie); przepalać się', 'both', '{daily,hr}', 'neutral', 'C1', '[{"sentence": "After working 80-hour weeks for months, she completely burned out.", "context": "a professional reaching physical and mental exhaustion", "tense": "Past Simple", "grammar_note": "subject + burned out + adverb (intransitive, complete action)"}, {"sentence": "Many young teachers are burning out within their first five years.", "context": "a worrying trend in the education sector", "tense": "Present Continuous", "grammar_note": "are + burning out (continuous for current trend)"}, {"sentence": "The light bulb has burned out and needs replacing.", "context": "a broken light in the house", "tense": "Present Perfect", "grammar_note": "has + past participle (present perfect for result visible now)"}, {"sentence": "To avoid burning out, you should take regular breaks.", "context": "health advice about maintaining work-life balance", "tense": "Gerund", "grammar_note": "to avoid + gerund (gerund after preposition ''to avoid'')"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('carry away', 'To become so excited or enthusiastic about something that you lose control or forget other things. Often used in passive voice.', 'ponosić (o emocjach); dać się ponieść', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She got carried away at the auction and spent far too much money.", "context": "overspending due to excitement at a bidding event", "tense": "Past Simple", "grammar_note": "got + past participle (get passive for change of state)"}, {"sentence": "Don''t get carried away — we still have a limited budget.", "context": "warning a colleague during project planning", "tense": "Imperative", "grammar_note": "don''t + get carried away (negative imperative with get passive)"}, {"sentence": "He tends to get carried away when talking about his favourite topic.", "context": "describing someone who becomes overly enthusiastic", "tense": "Present Simple", "grammar_note": "tends + to get carried away (infinitive with ''tend to'')"}, {"sentence": "If you hadn''t been carried away by the excitement, you would have noticed the error.", "context": "reflecting on a mistake caused by excessive enthusiasm", "tense": "Conditional", "grammar_note": "if + past perfect passive, would have + past participle (third conditional passive)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('come over', 'To visit someone at their home, usually informally. Also means to suddenly experience a feeling or to seem a certain way.', 'wpaść (z wizytą); nachodzić (o uczuciu); sprawiać wrażenie', 'general', '{daily}', 'informal', 'B2', '[{"sentence": "Why don''t you come over for dinner on Saturday?", "context": "inviting a friend for a casual meal", "tense": "Present Simple", "grammar_note": "why don''t you + come over (suggestion with ''why don''t you'')"}, {"sentence": "A strange feeling came over me as I entered the old house.", "context": "experiencing an eerie sensation in an unfamiliar place", "tense": "Past Simple", "grammar_note": "subject + came over + object (intransitive with ''feeling'' as subject)"}, {"sentence": "She has been coming over every weekend to help with the garden.", "context": "a neighbour regularly visiting to assist", "tense": "Present Perfect Continuous", "grammar_note": "has been + coming over (continuous for repeated recent visits)"}, {"sentence": "You came over really well in the interview — they were impressed.", "context": "giving feedback after a job interview", "tense": "Past Simple", "grammar_note": "subject + came over + adverb (meaning ''appeared'' or ''seemed'')"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('cool down', 'To become less hot in temperature. Also means to become calmer after being angry or excited.', 'ochładzać się; studzić się; uspokajać się', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "Let the soup cool down before you eat it.", "context": "advising someone about hot food", "tense": "Imperative", "grammar_note": "let + object + cool down (imperative with ''let'' + bare infinitive)"}, {"sentence": "He needed some time to cool down after the argument.", "context": "recovering from a heated disagreement", "tense": "Past Simple", "grammar_note": "needed + to cool down (infinitive complement for purpose)"}, {"sentence": "The weather is finally cooling down after weeks of intense heat.", "context": "a change in weather conditions at the end of summer", "tense": "Present Continuous", "grammar_note": "is + cooling down (continuous for gradual change)"}, {"sentence": "Once you''ve cooled down, we can talk about what happened.", "context": "asking someone to calm down before a discussion", "tense": "Present Perfect", "grammar_note": "once + present perfect (time clause for future completion)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('drop out', 'To leave a course, competition, or group before it is finished, especially without completing it.', 'rezygnować; porzucać (studia/kurs); wycofywać się', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "He dropped out of university in his second year to start a business.", "context": "leaving education to pursue entrepreneurship", "tense": "Past Simple", "grammar_note": "subject + dropped out + of + object (intransitive with preposition)"}, {"sentence": "Three runners have already dropped out of the marathon due to injuries.", "context": "athletes withdrawing from a race", "tense": "Present Perfect", "grammar_note": "have + past participle + of (present perfect for recent events)"}, {"sentence": "If you drop out now, you''ll lose your place on the course.", "context": "warning a student about consequences of leaving", "tense": "Conditional", "grammar_note": "if + present simple, will + infinitive (first conditional for warning)"}, {"sentence": "She was thinking about dropping out, but her tutor persuaded her to stay.", "context": "a student reconsidering her education", "tense": "Past Continuous", "grammar_note": "was + thinking about + gerund (past continuous with gerund complement)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('end up', 'To eventually arrive at a place, situation, or condition that was not planned or expected.', 'skończyć (gdzieś/jakoś); ostatecznie trafić', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "We got lost and ended up in a completely different town.", "context": "an unplanned detour during a road trip", "tense": "Past Simple", "grammar_note": "subject + ended up + prepositional phrase (intransitive with location)"}, {"sentence": "If you don''t study, you''ll end up failing the exam.", "context": "warning a student about poor preparation", "tense": "Future Simple", "grammar_note": "will + end up + gerund (future with gerund complement)"}, {"sentence": "She always ends up doing all the work herself.", "context": "someone who consistently takes on too much responsibility", "tense": "Present Simple", "grammar_note": "always + ends up + gerund (present simple with frequency adverb)"}, {"sentence": "He had ended up in hospital after ignoring his symptoms for weeks.", "context": "a health emergency caused by neglecting warning signs", "tense": "Past Perfect", "grammar_note": "had + ended up + in (past perfect for event before another past event)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get along with', 'To have a friendly relationship with someone. To be able to work or live together in a harmonious way.', 'dogadywać się z; być w dobrych stosunkach z', 'both', '{daily,hr}', 'neutral', 'B2', '[{"sentence": "She gets along with everyone in the office.", "context": "describing a popular and sociable colleague", "tense": "Present Simple", "grammar_note": "subject + gets along with + object (three-part inseparable phrasal verb)"}, {"sentence": "We didn''t get along with each other at first, but now we''re great friends.", "context": "a friendship that developed over time", "tense": "Past Simple", "grammar_note": "didn''t + get along with (negative past simple)"}, {"sentence": "It''s essential to get along with your teammates in a collaborative project.", "context": "advice about teamwork in a professional setting", "tense": "Infinitive", "grammar_note": "it''s essential + to get along with (infinitive as subject complement)"}, {"sentence": "They had been getting along with the neighbours well until the fence dispute started.", "context": "a neighbourly relationship disrupted by a disagreement", "tense": "Past Perfect Continuous", "grammar_note": "had been + getting along with (past perfect continuous for duration before disruption)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('hold on', 'To wait for a short time. Also means to grip something tightly or to persist through a difficult situation.', 'czekać; trzymać się; wytrzymać', 'both', '{daily,meetings}', 'neutral', 'B2', '[{"sentence": "Hold on a moment — I need to check something.", "context": "asking someone to wait briefly during a conversation", "tense": "Imperative", "grammar_note": "imperative + time expression (direct command)"}, {"sentence": "She held on to the railing as the boat rocked violently.", "context": "gripping for safety on a boat in rough seas", "tense": "Past Simple", "grammar_note": "subject + held on + to + object (intransitive with preposition)"}, {"sentence": "The business managed to hold on through the recession.", "context": "a company surviving a period of economic downturn", "tense": "Past Simple", "grammar_note": "managed + to hold on (infinitive complement, meaning ''survived'')"}, {"sentence": "If you can hold on for a few more weeks, things will get better.", "context": "encouraging patience during a challenging period", "tense": "Conditional", "grammar_note": "if + can + hold on, will + infinitive (first conditional for encouragement)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('keep on', 'To continue doing something without stopping. Also means to continue employing someone.', 'kontynuować; nie przestawać; dalej zatrudniać', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "She kept on working despite feeling unwell.", "context": "persevering with work during illness", "tense": "Past Simple", "grammar_note": "subject + kept on + gerund (past simple with gerund complement)"}, {"sentence": "If you keep on making the same mistakes, you won''t improve.", "context": "warning someone about repeated errors", "tense": "Conditional", "grammar_note": "if + keep on + gerund, will + not + infinitive (first conditional)"}, {"sentence": "Keep on trying — you''ll get it right eventually.", "context": "motivating someone who is struggling with a task", "tense": "Imperative", "grammar_note": "imperative + gerund (encouragement)"}, {"sentence": "He has been kept on past his retirement age because of his expertise.", "context": "an experienced employee retained by the company", "tense": "Passive Voice", "grammar_note": "has been + past participle (present perfect passive, meaning ''retained'')"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('make up', 'To invent a story, excuse, or lie. Also means to reconcile after a quarrel, to constitute or form something, or to apply cosmetics.', 'wymyślać (historię); godzić się; stanowić; malować się', 'general', '{daily}', 'neutral', 'B2', '[{"sentence": "He made up an excuse for being late to the meeting.", "context": "inventing a false reason for tardiness", "tense": "Past Simple", "grammar_note": "subject + made up + object (separable, meaning ''invented'')"}, {"sentence": "They had a terrible fight but made up the next day.", "context": "friends reconciling after a disagreement", "tense": "Past Simple", "grammar_note": "subject + made up (intransitive, meaning ''reconciled'')"}, {"sentence": "Women make up nearly 60% of university graduates in this country.", "context": "discussing demographic statistics in education", "tense": "Present Simple", "grammar_note": "subject + make up + percentage (present simple for factual statement)"}, {"sentence": "You''ll need to make up the lost time by working overtime.", "context": "compensating for missed work hours", "tense": "Future Simple", "grammar_note": "will need + to make up + object (future with infinitive complement)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('opt out', 'To choose not to participate in something or to withdraw from an arrangement.', 'wycofywać się; rezygnować; zrezygnować z uczestnictwa', 'both', '{daily,emails}', 'neutral', 'C1', '[{"sentence": "Several employees opted out of the company pension scheme.", "context": "workers choosing not to join a retirement plan", "tense": "Past Simple", "grammar_note": "subject + opted out + of + object (intransitive with preposition)"}, {"sentence": "You can opt out of receiving marketing emails at any time.", "context": "information about unsubscribing from a mailing list", "tense": "Present Simple", "grammar_note": "can + opt out + of + gerund (modal with gerund complement)"}, {"sentence": "More parents have been opting out of standardised testing for their children.", "context": "a growing trend in education", "tense": "Present Perfect Continuous", "grammar_note": "have been + opting out (continuous for increasing trend)"}, {"sentence": "If you opt out now, you will not be able to rejoin until next year.", "context": "terms and conditions of a membership programme", "tense": "Conditional", "grammar_note": "if + present simple, will + not + infinitive (first conditional for consequence)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('pull through', 'To recover from a serious illness, injury, or difficult situation. To succeed despite great difficulty.', 'wyzdrowieć; wyjść z trudnej sytuacji; przetrwać', 'general', '{daily}', 'neutral', 'C1', '[{"sentence": "The doctors were worried, but she managed to pull through.", "context": "recovering from a critical medical condition", "tense": "Past Simple", "grammar_note": "managed + to pull through (infinitive complement for success)"}, {"sentence": "The company is expected to pull through the financial crisis.", "context": "analysts predicting a business will survive tough times", "tense": "Infinitive", "grammar_note": "is expected + to pull through (passive infinitive construction)"}, {"sentence": "If we all work together, we''ll pull through this difficult period.", "context": "encouraging teamwork during a community hardship", "tense": "Future Simple", "grammar_note": "will + pull through (first conditional for optimistic prediction)"}, {"sentence": "He had pulled through worse situations before and remained confident.", "context": "drawing on past resilience in a new challenge", "tense": "Past Perfect", "grammar_note": "had + past participle (past perfect for experience before another past event)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('rule out', 'To decide that something is not possible or to exclude it from consideration.', 'wykluczać; odrzucać (możliwość)', 'both', '{daily,meetings}', 'neutral', 'C1', '[{"sentence": "The police have not ruled out the possibility of foul play.", "context": "a criminal investigation considering all scenarios", "tense": "Present Perfect", "grammar_note": "have not + past participle + object (present perfect negative)"}, {"sentence": "We can''t rule out further delays due to the weather.", "context": "acknowledging potential problems with a construction project", "tense": "Present Simple", "grammar_note": "can''t + rule out + object (modal negative with noun complement)"}, {"sentence": "The doctor ruled out any serious illness after running the tests.", "context": "a medical examination confirming no major health issue", "tense": "Past Simple", "grammar_note": "subject + ruled out + object + after clause (past simple with time clause)"}, {"sentence": "Nothing should be ruled out until all the evidence has been examined.", "context": "insisting on a thorough investigation", "tense": "Passive Voice", "grammar_note": "should be + past participle + until clause (modal passive with time clause)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('set apart', 'To make someone or something different from or superior to others. To distinguish one thing from another.', 'wyróżniać; odróżniać; oddzielać', 'both', '{daily,presentations}', 'neutral', 'C1', '[{"sentence": "Her creativity is what sets her apart from the other candidates.", "context": "discussing why someone is the best applicant for a role", "tense": "Present Simple", "grammar_note": "what + sets + object + apart (present simple in cleft sentence)"}, {"sentence": "The quality of the materials set this brand apart from its competitors.", "context": "comparing a premium product to cheaper alternatives", "tense": "Past Simple", "grammar_note": "subject + set apart + object + from (past simple, separable)"}, {"sentence": "What has always set this school apart is its focus on critical thinking.", "context": "highlighting the unique strength of an educational institution", "tense": "Present Perfect", "grammar_note": "what + has + past participle (present perfect in cleft structure)"}, {"sentence": "Being set apart by a unique selling point is essential for any business.", "context": "business advice about market differentiation", "tense": "Gerund", "grammar_note": "being + past participle (passive gerund as subject)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('speak up', 'To talk more loudly so that people can hear you. Also means to express your opinion openly, especially in defence of something.', 'mówić głośniej; zabierać głos; odzywać się', 'both', '{daily,meetings}', 'neutral', 'B2', '[{"sentence": "Could you speak up, please? We can''t hear you at the back.", "context": "asking a speaker to increase their volume in a large room", "tense": "Conditional", "grammar_note": "could + subject + speak up (polite request with modal)"}, {"sentence": "She spoke up against the unfair policy at the staff meeting.", "context": "an employee voicing opposition to a workplace rule", "tense": "Past Simple", "grammar_note": "subject + spoke up + against (intransitive with preposition)"}, {"sentence": "More people need to speak up about this issue.", "context": "encouraging public discourse on an important topic", "tense": "Infinitive", "grammar_note": "need + to speak up + about (infinitive with preposition)"}, {"sentence": "He has never spoken up in meetings before, so everyone was surprised.", "context": "a quiet person suddenly sharing their views", "tense": "Present Perfect", "grammar_note": "has never + past participle (present perfect negative with adverb)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('wind down', 'To gradually relax after a period of activity or excitement. Also means to slowly bring something to an end.', 'wyciszać się; relaksować się; stopniowo kończyć', 'both', '{daily,meetings}', 'neutral', 'C1', '[{"sentence": "I like to wind down with a good book before going to bed.", "context": "a relaxing evening routine", "tense": "Present Simple", "grammar_note": "subject + like + to wind down (infinitive complement with habitual action)"}, {"sentence": "The project is winding down and should be completed by Friday.", "context": "a task approaching its conclusion", "tense": "Present Continuous", "grammar_note": "is + winding down (continuous for gradual process)"}, {"sentence": "After the conference wound down, we went out for dinner together.", "context": "socialising after a professional event", "tense": "Past Simple", "grammar_note": "after + past simple, past simple (time clause with past simple)"}, {"sentence": "The operations had been winding down for months before the official closure.", "context": "a business gradually reducing activity before shutting", "tense": "Past Perfect Continuous", "grammar_note": "had been + winding down (past perfect continuous for duration before a past event)"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('zero in on', 'To focus attention or efforts on a particular thing or person. To move towards a target with precision.', 'skupiać się na; koncentrować się na; namierzać', 'both', '{daily,meetings}', 'neutral', 'C1', '[{"sentence": "The detective zeroed in on the main suspect after reviewing the evidence.", "context": "a police investigation narrowing its focus", "tense": "Past Simple", "grammar_note": "subject + zeroed in on + object (three-part inseparable phrasal verb)"}, {"sentence": "We need to zero in on the root cause of the problem.", "context": "a team meeting about solving a persistent issue", "tense": "Infinitive", "grammar_note": "need + to zero in on + object (infinitive complement for necessity)"}, {"sentence": "The media has zeroed in on the scandal, ignoring other important news.", "context": "criticism of press coverage priorities", "tense": "Present Perfect", "grammar_note": "has + past participle + on (present perfect for recent focus)"}, {"sentence": "Once the researchers zero in on the right variables, a breakthrough will follow.", "context": "predicting progress in scientific research", "tense": "Conditional", "grammar_note": "once + present simple, will + infinitive (first conditional with ''once'')"}]');

INSERT INTO public.phrasal_verbs (verb, definition_en, translation_pl, category, tags, register, difficulty, examples)
VALUES ('get across', 'To successfully communicate an idea or message.', 'przekazać (myśl, ideę)', 'business', '{communication,presentations}', 'neutral', 'B2', '[{"sentence": "He struggled to get his point across during the debate.", "context": "meeting feedback", "tense": "Past Simple", "grammar_note": "to + get + noun + across (separable)"}, {"sentence": "We need to get the message across that safety comes first.", "context": "company policy", "tense": "Infinitive", "grammar_note": "to + get + noun + across (separable)"}, {"sentence": "The presentation really got the value proposition across.", "context": "sales pitch", "tense": "Past Simple", "grammar_note": "got + noun + across (separable)"}, {"sentence": "How can we best get this concept across to the team?", "context": "training strategy", "tense": "Modal Interrogative", "grammar_note": "can + get + noun + across (separable)"}]');
